Repository antvis/S2, pull requests merged in 2021-12, with the labels that each got.

#850 docs: optimize tooltip docs
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(documentation)

#851 feat(components): add switcher header config
  package.json
  packages/s2-react/__tests__/unit/components/header/index.spec.tsx
  packages/s2-react/__tests__/unit/components/switcher/headerUtil.spec.ts
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/header/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/components/switcher/headerUtil.ts
  packages/s2-react/tsconfig.json
  s2-site/docs/api/components/header.zh.md
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/common/header.zh.md
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/examples/react-component/header/index.en.md
  s2-site/examples/react-component/header/index.zh.md
  s2-site/examples/react-component/switcher/demo/meta.json
  s2-site/examples/react-component/switcher/demo/pivot-header.tsx
  s2-site/examples/react-component/switcher/index.en.md
  s2-site/examples/react-component/switcher/index.zh.md
  s2-site/examples/react-component/tooltip/index.en.md
  s2-site/examples/react-component/tooltip/index.zh.md
  yarn.lock
Labels: pr(feature)

#853 refactor(components): reduce options and dataCfg
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/bugs/issue-285-spec.tsx
  packages/s2-react/__tests__/spreadsheet/condition-usage-spec.tsx
  packages/s2-react/__tests__/spreadsheet/custom-interaction-spec.tsx
  packages/s2-react/__tests__/spreadsheet/custom-tree-header-spec.tsx
  packages/s2-react/__tests__/spreadsheet/grid-analysis-sheet-spec.tsx
  packages/s2-react/__tests__/spreadsheet/hidden-columns-spec.tsx
  packages/s2-react/__tests__/spreadsheet/link-fields-spec.tsx
  packages/s2-react/__tests__/spreadsheet/merge-cells-spec.tsx
  packages/s2-react/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-react/__tests__/spreadsheet/sheet-custom-tooltip-spec.tsx
  packages/s2-react/__tests__/spreadsheet/sort-sheet-spec.tsx
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-react/__tests__/spreadsheet/switcher-spec.tsx
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/__tests__/unit/utils/build-table-hierarchy-spec.tsx
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/playground/sheet-entry.tsx
  packages/s2-react/src/common/constant/options.ts
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/grid-analysis-data-cell.ts
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/utils/index.ts
  packages/s2-react/src/utils/merge.ts
  packages/s2-react/src/utils/options.ts
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(refactor)

#861 fix: only omit undefined row cell
  packages/s2-core/__tests__/bugs/issue-860-spec.ts
  packages/s2-core/__tests__/data/data-issue-860.json
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
Labels: pr(fix)

#858 fix: fix series resize area
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/common/interface/node.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/interaction/row-column-resize.ts
Labels: pr(fix)

#859 fix(cell): border width issue
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/cell.spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/cell/table-corner-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/theme/palette/default.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
Labels: pr(fix)

#856 fix(export): export corner bug
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#857 fix: the order of multiple selection of cells is wrong
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell.spec.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/index.ts
  packages/s2-core/src/interaction/base-interaction/click/merged-cell-click.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/index.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-core/src/utils/interaction/state-controller.ts
  s2-site/docs/api/components/header.zh.md
  s2-site/docs/common/header.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/interaction/advanced/demo/merge-cell.ts
  s2-site/examples/interaction/advanced/demo/meta.json
Labels: pr(fix)

#863 fix(theme): revert default palette change
  packages/s2-core/src/theme/palette/default.ts
Labels: pr(fix)

#865 docs(export): add export func docs
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/manual/basic/analysis/export.zh.md
Labels: pr(documentation)

#862 feat(tooltip): enhance tooltip
  CONTRIBUTING.md
  README.en-US.md
  README.md
  packages/s2-core/README.md
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/common/interface/events.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/components/tooltip/components/operator/index.tsx
  packages/s2-react/src/components/tooltip/custom-tooltip.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-react/src/components/tooltip/interface.ts
  s2-site/docs/api/basic-class/base-cell.en.md
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/api/basic-class/interaction.en.md
  s2-site/docs/api/basic-class/node.zh.md
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/manual/advanced/custom/category-tree.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/examples/interaction/custom/demo/meta.json
  s2-site/examples/interaction/custom/demo/row-col-hover-tooltip.ts
  s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/meta.json
Labels: pr(feature)

#864 feat(resize): add resize active options, close #855
  packages/s2-core/__tests__/bugs/issue-860-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-react/__tests__/unit/components/header/index.spec.tsx
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/index.less
  packages/s2-react/playground/index.tsx
  packages/s2-react/playground/resize.tsx
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/resize-active.ts
Labels: pr(feature)

#866 chore: 🤖 auto sync site s2 lock and changelog [skip ci]
  .github/workflows/auto-release.yml
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#867 docs: :memo: update the doc of S2DataConfig
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/custom/customTreeItem.zh.md
Labels: pr(documentation)

#871 fix: 🐛 solve the issue that the measure does not shown when the type of dimensions are number
  packages/s2-core/__tests__/bugs/issue-868-spec.ts
  packages/s2-core/__tests__/data/data-issue-868.json
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(fix)

#876 docs: :memo: fix crashed demos
  packages/s2-core/src/cell/col-cell.ts
  s2-site/examples/analysis/sort/demo/meta.json
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
  s2-site/examples/react-component/sheet/demo/table.tsx
  s2-site/examples/theme/custom/demo/custom-schema.ts
Labels: pr(documentation)

#878 fix(components): add empty fragment close #873
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/__tests__/unit/components/header/index.spec.tsx
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/src/components/tooltip/components/operator/index.tsx
Labels: pr(fix)

#880 docs(performance): table compare size
  s2-site/docs/manual/advanced/performance.zh.md
Labels: pr(documentation)

#877 fix(export): export link problem
  packages/s2-react/src/components/export/index.tsx
Labels: pr(fix)

#884 feat: ✨ show the sortIcon when the hideMeasureColumn is set
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/utils/sort-action.ts
  packages/s2-react/playground/index.tsx
Labels: pr(feature)

#885 fix: 🐛 solve the wrong data after drilling down twice
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/interaction/shift-multi-selection.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-react/__tests__/unit/components/header/index-spec.tsx
  packages/s2-react/__tests__/unit/components/switcher/headerUtil-spec.ts
  packages/s2-react/__tests__/unit/components/switcher/util-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/utils/drill-down.ts
Labels: pr(fix)

#888 chore: rename the release branch [skip ci]
  .github/workflows/auto-release.yml
Labels: pr(chore)

#892 chore: 同步 lock 和 changelog
  .github/workflows/sync-site-lock-changelog-with-pr.yml
  .releaserc.js
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#896 fix(table): 修复明细表 onDataCellHover 无法触发
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(fix)

#890 feat(interaction): 透视表支持隐藏列头
  .github/workflows/sync-site-lock-changelog-with-pr.yml
  .releaserc.js
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/data/simple-table-data.json
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  s2-site/docs/common/header.zh.md
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(feature)

#898 fix(frame): incorrect viewport splitline shadow
  packages/s2-core/src/common/interface/frame.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/frame.ts
Labels: pr(fix)

#906 test: ✅ 修复单测&统一单测命名
  packages/s2-core/__tests__/unit/common/i18n/index-spec.ts
  packages/s2-core/__tests__/unit/common/store/index-spec.ts
  packages/s2-core/__tests__/unit/facet/bbox/cornerBBox-spec.ts
  packages/s2-core/__tests__/unit/utils/attrs-action-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/condition/conditions-spec.ts
  packages/s2-core/__tests__/unit/utils/condition/state-controller-spec.ts
  packages/s2-core/__tests__/unit/utils/data-item-type-checker-spec.ts
  packages/s2-core/__tests__/unit/utils/get-all-children-node-height-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/unit/utils/name-generator-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/__tests__/unit/utils/veen-arr-spec.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
Labels: pr(test)

#905 feat(strategy-sheet): 自定义趋势分析表 tooltip
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/__tests__/data/strategy-data.json
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/common/i18n/en_US.ts
  packages/s2-react/src/common/i18n/zh_CN.ts
  packages/s2-react/src/components/index.ts
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.module.less
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/strategy-data-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/strategy-theme.ts
  packages/s2-react/src/components/tooltip/index.tsx
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(feature), 🚨 test failed

#902 fix(interactive): global selected event emit
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/shift-multi-selection.ts
Labels: pr(fix)

#907 chore: 更新CI中英文翻译
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/lint.yml
  .github/workflows/pr-labeled.yml
  .github/workflows/test.yml
Labels: pr(chore)

#908 feat(interaction): 支持禁用刷选功能
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/interaction/index.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(feature)

#910 fix: 修复错误修改DefaultOptions问题 close #886
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/src/hooks/usePaginationEffect.ts
Labels: pr(fix)

#916 feat: ✨ 增加对象型数值单元格宽度和文本条件的映射
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/grid-analysis-data.ts
  packages/s2-react/__tests__/data/strategy-data.json
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/strategy-theme.ts
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
Labels: pr(feature)

#912 fix: :bug: 修复指标列头 hover 行为和维值列头不一致问题
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
Labels: pr(fix)

#918 chore(ci): 简化发布通知 action
  .github/workflows/auto-release-notify.yml
  .github/workflows/auto-release.yml
  .github/workflows/release-notify.yml
  .github/workflows/sync-site-lock-changelog-with-pr.yml
Labels: pr(chore)

#913 feat: 新增趋势分析表hover列头显示指标名
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/lint.yml
  .github/workflows/pr-labeled.yml
  .github/workflows/test.yml
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/frame.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/shift-multi-selection.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/strategy-data-cell.ts
  packages/s2-react/src/hooks/usePaginationEffect.ts
Labels: pr(feature)

#914 fix(scroll): 修复滚动表格后, 鼠标移动会重置已选中单元格 close #904
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#919 feat(strategy-sheet): 趋势分析表禁用多选和快捷多选
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/index.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/examples/case/kpi-strategy/demo/basic.tsx
Labels: pr(feature)

#909 feat(facet): 明细表增加行高 resize 调整 && 行高 resize 增加选项
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/constant/resize.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/facet.ts
  packages/s2-core/src/utils/interaction/resize.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/resize.tsx
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/interaction.zh.md
Labels: pr(feature)

#923 docs: 修复字段标记明细表demo错误的数据地址
  s2-site/examples/analysis/conditions/demo/table-text.ts
Labels: pr(documentation)

#922 fix: event-controller 重复注册事件
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#925 feat: 新增字段描述功能
  packages/s2-core/__tests__/unit/data-set/custom-tree-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-react/__tests__/data/strategy-data.json
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(feature), 🚨 test failed

#927 fix: 🐛 修复趋势分析表和网格分析表无法自定义主题
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix)

#926 docs: 新增theme主题配置文档 close #872
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/basic/theme.en.md
  s2-site/docs/manual/basic/theme.zh.md
Labels: pr(documentation)

#929 fix(startegysheet): 趋势分析表列头文字根据数值坐标动态计算
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix), 🚨 test failed

#931 fix(components): 修复配置的宽度超过浏览器可视窗口宽度无法滚动的问题 close #889
  .github/workflows/test.yml
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.less
Labels: pr(fix)

#930 docs: 更新截图/润色文档
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/gatsby-config.js
Labels: pr(documentation)

#932 fix(facet): table adaptive layout
  packages/s2-core/__tests__/unit/data-process/table-spec.tsx
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#935 docs: 修复维度切换组件 demo 的错误数据链接
  s2-site/examples/react-component/switcher/demo/pivot-header.tsx
  s2-site/examples/react-component/switcher/demo/pivot.tsx
Labels: pr(documentation)

#936 docs: 增加常见问题, 修复部分文档错误链接
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/interaction/custom-header-action-icon.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
Labels: pr(documentation)

#937 docs: 完善文档
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(documentation)

#934 fix: :bug: 修复列头小计总计位置漂移问题， close #836
  packages/s2-core/__tests__/bugs/issue-368-spec.ts
  packages/s2-core/__tests__/bugs/issue-836-spec.ts
  packages/s2-core/__tests__/data/data-issue-836.json
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#933 fix(table): add frozen opts validation & frozen col resize fix
  packages/s2-core/__tests__/unit/utils/frozen-util-spec.ts
  packages/s2-core/__tests__/unit/utils/get-all-child-cells-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/get-all-child-cells.ts
  packages/s2-core/src/utils/getAllPanelDataCell.ts
  packages/s2-core/src/utils/layout/frozen.ts
Labels: pr(fix)

#894 feat(table filter): add custom filter function
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/table-data-set.ts
  s2-site/docs/manual/advanced/data-process/table.zh.md
Labels: pr(feature), 🙏 need test cases or docs

#944 feat(interaction): 新增 hoverFocus 配置项
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#946 fix: 修复未配置 label时, hover 数值单元格报错, 并且列头文字上移的问题
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
Labels: pr(fix)

#940 feat: 自适应机制优化: 开启 adaptive 读取容器宽高, 关闭情况下再读取配置项
  packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/hooks/useResizeEffect.ts
  s2-site/docs/manual/advanced/adaptive.zh.md
Labels: pr(feature), 🚨 test failed

#947 fix(table): 明细表数据为空时添加兜底
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), 🚨 test failed

#948 docs: :memo: 更新 README 和官网文档首页头图
  README.en-US.md
  README.md
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(documentation)

#950 chore: 官网增加 docs search 配置
  s2-site/gatsby-config.js
Labels: pr(chore), 🚨 test failed

#951 docs: 📝 增加场景demo「想如何度过一天」
  s2-site/examples/analysis/sort/demo/custom-measure.ts
  s2-site/examples/analysis/sort/demo/meta.json
  s2-site/examples/case/comparison/demo/meta.json
  s2-site/examples/case/comparison/demo/time-spend.tsx
  s2-site/examples/data/time-spend.json
Labels: pr(documentation)

#952 fix(components): adaptive getContainer 类型修改为可选, 并优化相关文档
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/hooks/useResizeEffect.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
Labels: pr(fix)

#955 fix: bug: 修复交叉表手动设置滚动不生效问题
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#958 refactor: ♻️ 自定义目录树优化
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/facet/header/index.ts
  packages/s2-core/src/index.ts
  packages/s2-react/__tests__/data/custom-tree-fields.ts
  packages/s2-react/__tests__/data/custom-tree-items.ts
  packages/s2-react/__tests__/data/data-custom-trees.ts
  packages/s2-react/__tests__/data/strategy-data.json
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(refactor)

#960 fix(test): table facet 测试小数取整
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
Labels: pr(fix), 🚨 test failed
