Repository antvis/S2, pull requests merged in 2021-11, with the labels that each got.

#596 fix: :bug: refactor the csvString
  packages/s2-core/__tests__/bugs/issue-446-spec.tsx
  packages/s2-core/__tests__/bugs/issue-565-spec.tsx
  packages/s2-core/src/utils/export/export-worker.ts
Labels: pr(fix)

#597 docs: init measure comparison sheet demo
  s2-site/examples/case/measure-comparison/API.en.md
  s2-site/examples/case/measure-comparison/API.zh.md
  s2-site/examples/case/measure-comparison/demo/basic.tsx
  s2-site/examples/case/measure-comparison/demo/meta.json
  s2-site/examples/case/measure-comparison/index.en.md
  s2-site/examples/case/measure-comparison/index.zh.md
  s2-site/examples/data/index-comparison.json
Labels: pr(documentation)

#598 chore(release): 🔖 publish the version 1.0.0-beta.5
  packages/s2-core/package.json
Labels: pr(chore)

#600 chore(release): 1.0.0-beta.6
  packages/s2-core/package.json
Labels: pr(chore)

#604 docs(demo): remove ts interface in custom demo
  s2-site/examples/custom/header-action-icon/demo/basic.ts
  s2-site/examples/custom/layout-arrange/demo/basic.ts
  s2-site/examples/custom/layout-coordinate/demo/basic.ts
  s2-site/examples/custom/layout-data-position/demo/basic.ts
  s2-site/examples/custom/layout-hierarchy/demo/basic.ts
Labels: pr(documentation)

#599 fix(resize): fix corner resize blank
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/resize-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/resize.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/interaction/resize.ts
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(fix)

#603 fix(interaction): cancel data cell hover focus timer when row or col mousemove
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/ui/tooltip/index.tsx
Labels: pr(fix)

#607 chore(ci): support prerelease notify
  .github/workflows/auto-release.yml
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#610 feat(table): add shadow for frozen line
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/theme/index.ts
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(feature)

#611 chore: fix circular dependencies and close #605
  packages/s2-core/rollup.config.js
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/frame.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/components/sheets/tabular-sheet/tabular-theme.ts
  packages/s2-core/src/components/switcher/item/single-item.tsx
  packages/s2-core/src/facet/header/base.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-core/src/utils/tooltip.ts
Labels: pr(chore)

#613 docs: :sparkles: add the custom theme demos
  s2-site/examples/theme/custom/API.en.md
  s2-site/examples/theme/custom/API.zh.md
  s2-site/examples/theme/custom/demo/custom-palette.ts
  s2-site/examples/theme/custom/demo/custom-schema.ts
  s2-site/examples/theme/custom/demo/meta.json
  s2-site/examples/theme/custom/design.en.md
  s2-site/examples/theme/custom/design.zh.md
  s2-site/examples/theme/custom/index.en.md
  s2-site/examples/theme/custom/index.zh.md
Labels: pr(documentation)

#614 refactor: support forward ref
  packages/s2-core/__tests__/bugs/issue-522-spec.tsx
  packages/s2-core/__tests__/bugs/issue-594-spec.tsx
  packages/s2-core/__tests__/data/simple-data.json
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/package.json
  packages/s2-core/src/components/index.ts
  packages/s2-core/src/components/index.tsx
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/index.tsx
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/components/sheets/table-sheet/index.tsx
  packages/s2-core/src/components/sheets/tabular-sheet/index.tsx
  yarn.lock
Labels: pr(refactor)

#608 feat: perfect and repair merged cells
  .eslintrc
  packages/s2-core/__tests__/spreadsheet/merge-cells-spec.tsx
  packages/s2-core/src/cell/merged-cells.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/utils/interaction/merge-cells.ts
  s2-site/examples/interaction/advanced/demo/merge-cells.ts
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/site/pages/index.zh.tsx
Labels: pr(feature), 🙏 need test cases or docs

#615 docs: add get sheet instance doc
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/advanced/get-instance.en.md
  s2-site/docs/manual/advanced/get-instance.zh.md
Labels: pr(documentation)

#620 fix(component): fix not use container width when enable adaptive and first rendered
  packages/s2-core/__tests__/bugs/issue-609-spec.tsx
  packages/s2-core/src/components/sheets/hooks.ts
Labels: pr(fix)

#619 test(export): add export test
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/index.ts
Labels: pr(test)

#622 fix(scroll): set scroll move event target to body
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/ui/scrollbar/index.ts
Labels: pr(fix)

#618 docs(faq): add faq for performance & compatibility
  s2-site/docs/manual/faq.en.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/gatsby-config.js
  yarn.lock
Labels: pr(documentation)

#624 fix(interaction): hide tooltip and clear hover highlight if mouseleave the cell
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/common/constant/events/origin.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/interaction/event-controller.ts
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(fix)

#625 docs(interaction): add update scroll speed ratio example
  .github/PULL_REQUEST_TEMPLATE.md
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/scroll-speed-ratio.ts
  s2-site/examples/react-component/tooltip/demo/custom.tsx
  s2-site/examples/react-component/tooltip/demo/meta.json
  s2-site/examples/react-component/tooltip/demo/render-tooltip.tsx
  s2-site/examples/theme/default/demo/meta.json
  s2-site/package.json
  s2-site/site/pages/index.zh.tsx
  s2-site/yarn.lock
Labels: pr(documentation)

#626 docs: add index-comparison sheet's demo
  s2-site/examples/case/measure-comparison/demo/basic.tsx
  s2-site/examples/data/index-comparison.json
Labels: pr(documentation)

#633 feat: :art: only show the header cell tooltip when the text is omitted
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
Labels: pr(feature)

#632 refactor: :fire: remove the derivedValues in the export process
  .github/PULL_REQUEST_TEMPLATE.md
  packages/s2-core/src/utils/export/index.ts
Labels: pr(refactor)

#635 fix(interaction): wrong hidden action tooltip when mouse outside the cell
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/common/constant/events/origin.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#634 docs(compare-demo): performance compare demo
  s2-site/examples/case/performance-compare/API.en.md
  s2-site/examples/case/performance-compare/API.zh.md
  s2-site/examples/case/performance-compare/demo/basic.tsx
  s2-site/examples/case/performance-compare/demo/meta.json
  s2-site/examples/case/performance-compare/index.en.md
  s2-site/examples/case/performance-compare/index.zh.md
  s2-site/examples/data/compare.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#630 refactor: ♻️ optimize the logic of tabularSheet and change the name to gridAnalysisSheet
  packages/s2-core/__tests__/data/grid-analysis-data.ts
  packages/s2-core/__tests__/data/tabular-data.ts
  packages/s2-core/__tests__/spreadsheet/grid-analysis-sheet-spec.tsx
  packages/s2-core/__tests__/spreadsheet/merge-cells-spec.tsx
  packages/s2-core/__tests__/spreadsheet/tabularSheet-spec.tsx
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/merged-cells.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/cell/table-corner-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/custom-cell.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/grid-analysis-data-cell.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/grid-analysis-theme.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-core/src/components/sheets/index.tsx
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/components/sheets/tabular-sheet/tabular-theme.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(refactor)

#640 chore(release): 1.0.0-beta.7
  packages/s2-core/package.json
Labels: pr(chore)

#648 chore: :wrench: add the GATrackingId for the s2-site
  s2-site/gatsby-config.js
Labels: pr(chore)

#647 fix(table): frozen trailing col render issue
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#639 docs: change demos screenshot and refactor measure comparison demo code
  s2-site/examples/analysis/sort/demo/meta.json
  s2-site/examples/case/measure-comparison/demo/basic.tsx
  s2-site/examples/case/measure-comparison/demo/meta.json
Labels: pr(documentation)

#650 fix: fix linkField config path
  packages/s2-core/__tests__/spreadsheet/link-fields-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#646 chore(doc): add doc for table && update frozen demo
  s2-site/docs/manual/advanced/data-process/table.zh.md
  s2-site/docs/manual/advanced/layout/table.zh.md
  s2-site/examples/interaction/basic/demo/frozen.ts
  s2-site/examples/interaction/basic/demo/frozen.tsx
  s2-site/examples/interaction/basic/demo/meta.json
Labels: pr(chore)

#649 refactor: tweak alignment
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/icons/svg/index.ts
  packages/s2-core/src/common/icons/svg/svgs.ts
Labels: pr(refactor)

#654 fix: fix internal svg icon disappear issue in official website
  packages/s2-core/src/common/icons/factory.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/common/icons/index.ts
  packages/s2-core/src/common/icons/svg/index.ts
Labels: pr(fix)

#645 feat: add resize area highlight for whole rows and columns
  package.json
  packages/s2-core/__tests__/unit/facet/bbox/cornerBBox.spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/resize-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/resize.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/baseBBox.ts
  packages/s2-core/src/facet/bbox/cornerBBox.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
  packages/s2-core/src/facet/header/base.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/header/interface.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/interaction/resize.ts
  yarn.lock
Labels: pr(feature)

#653 fix(components): fix component render crash with empty options
  packages/s2-core/__tests__/bugs/issue-652-spec.tsx
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-core/src/components/sheets/hooks.ts
  packages/s2-core/src/components/sheets/table-sheet/index.tsx
Labels: pr(fix)

#656 docs: update resize area docs
  packages/s2-core/src/theme/index.ts
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(documentation), ✅ test passed

#655 refactor: optimize sortedDimensionValues's structure by change map to object for saving repeat value and modify test
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-row-value-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/util.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(refactor), ✅ test passed

#657 docs: add the demo of performance
  README.en-US.md
  README.md
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  s2-site/docs/manual/advanced/data-process/pivot.zh.md
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/sort/basic.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/examples/analysis/conditions/demo/gradient-interval.ts
  s2-site/examples/analysis/conditions/demo/icon.ts
  s2-site/examples/analysis/conditions/demo/interval.ts
  s2-site/examples/analysis/conditions/demo/table-text.ts
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/examples/analysis/sort/demo/custom-list.ts
  s2-site/examples/analysis/sort/demo/custom-measure.ts
  s2-site/examples/analysis/sort/demo/custom-method.ts
  s2-site/examples/analysis/sort/demo/custom-sort-func.ts
  s2-site/examples/analysis/sort/demo/custom-totals.ts
  s2-site/examples/analysis/totals/demo/multiple-values.ts
  s2-site/examples/case/measure-comparison/demo/basic.tsx
  s2-site/examples/case/performance-compare/API.en.md
  s2-site/examples/case/performance-compare/API.zh.md
  s2-site/examples/case/performance-compare/demo/basic.tsx
  s2-site/examples/case/performance-compare/demo/meta.json
  s2-site/examples/case/performance-compare/demo/pivot.tsx
  s2-site/examples/case/performance-compare/demo/table.tsx
  s2-site/examples/case/performance-compare/design.en.md
  s2-site/examples/case/performance-compare/design.zh.md
  s2-site/examples/interaction/advanced/demo/hide-columns.ts
  s2-site/examples/interaction/advanced/demo/merge-cells.ts
  s2-site/examples/interaction/advanced/demo/pivot-link-jump.ts
  s2-site/examples/interaction/advanced/demo/table-link-jump.ts
  s2-site/examples/interaction/basic/demo/basic.ts
  s2-site/examples/react-component/drill-dwon/demo/drill-dwon-for-pivot.tsx
  s2-site/examples/react-component/export/demo/export.tsx
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/examples/react-component/switcher/demo/pivot-with-children.tsx
  s2-site/examples/react-component/switcher/demo/pivot.tsx
  s2-site/examples/react-component/switcher/demo/table.tsx
  s2-site/examples/theme/custom/demo/custom-palette.ts
  s2-site/examples/theme/default/demo/meta.json
Labels: pr(documentation), ✅ test passed

#660 chore: unfix peerDep versions
  packages/s2-core/package.json
Labels: pr(chore)

#663 docs: add multiple group comparison demo
  packages/s2-core/src/theme/index.ts
  s2-site/examples/case/multiple-people-comparison/API.en.md
  s2-site/examples/case/multiple-people-comparison/API.zh.md
  s2-site/examples/case/multiple-people-comparison/demo/basic.tsx
  s2-site/examples/case/multiple-people-comparison/demo/meta.json
  s2-site/examples/case/multiple-people-comparison/design.en.md
  s2-site/examples/case/multiple-people-comparison/design.zh.md
  s2-site/examples/case/multiple-people-comparison/index.en.md
  s2-site/examples/case/multiple-people-comparison/index.zh.md
  s2-site/examples/case/performance-compare/index.en.md
  s2-site/examples/case/performance-compare/index.zh.md
  s2-site/examples/data/multiple-people-comparison.json
Labels: pr(documentation), ✅ test passed

#666 feat(custom-tree): fix custom-tree mode & custom-tree test
  packages/s2-core/__tests__/data/data-custom-trees.ts
  packages/s2-core/__tests__/spreadsheet/custom-tree-header-spec.tsx
  packages/s2-core/__tests__/unit/dataset/custom-tree-dataset-spec.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/layout/index.ts
  s2-site/docs/manual/advanced/custom/hook.zh.md
  s2-site/docs/manual/basic/base-concept.zh.md
Labels: pr(feature), ✅ test passed

#664 feat: 🎸 修复interactionState的borderWidth和borderColor不生效问题
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/theme.ts
Labels: pr(feature)

#665 docs: add index comparison demo's design
  s2-site/examples/case/measure-comparison/API.en.md
  s2-site/examples/case/measure-comparison/API.zh.md
  s2-site/examples/case/measure-comparison/design.en.md
  s2-site/examples/case/measure-comparison/design.zh.md
  s2-site/examples/case/measure-comparison/index.en.md
  s2-site/examples/case/measure-comparison/index.zh.md
Labels: pr(documentation), ✅ test passed

#662 fix: pivot sheet sort icon's show
  packages/s2-core/src/cell/header-cell.ts
Labels: pr(fix), ✅ test passed

#658 feat(options): add empty cell placeholder options
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/utils/text.ts
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(feature), 🙏 need test cases or docs, ✅ test passed

#668 docs: optimize docs
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/examples/react-component/tooltip/demo/render-tooltip.tsx
Labels: pr(documentation), ✅ test passed

#669 chore(ci): fix cannot get user name
  .github/workflows/pr-labeled.yml
  .github/workflows/test.yml
Labels: pr(chore), 🙏 need test cases or docs

#673 refactor: unify frozen options name
  packages/s2-core/__tests__/spreadsheet/custom-tree-header-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-core/__tests__/spreadsheet/merge-cells-spec.tsx
  packages/s2-core/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-core/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-core/__tests__/spreadsheet/pressure-test-spec.tsx
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/examples/case/measure-comparison/demo/basic.tsx
Labels: pr(refactor)

#676 docs(custom-tree): finish custom-tree demo & api
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/custom/customTreeItem.en.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/manual/advanced/custom/category-tree.zh.md
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
  s2-site/examples/custom/custom-cell/index.en.md
  s2-site/examples/custom/custom-cell/index.zh.md
  s2-site/examples/custom/custom-tree/API.en.md
  s2-site/examples/custom/custom-tree/API.zh.md
  s2-site/examples/custom/custom-tree/demo/custom-tree.ts
  s2-site/examples/custom/custom-tree/demo/meta.json
  s2-site/examples/custom/custom-tree/index.en.md
  s2-site/examples/custom/custom-tree/index.zh.md
Labels: pr(documentation)

#674 fix(copy): copy with format data
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/utils/export/copy.ts
  s2-site/docs/common/interaction.zh.md
Labels: pr(fix)

#677 fix(table): fix expand column icon cover text and sort icon
  packages/s2-core/__tests__/bugs/issue-609-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/grid-analysis-theme.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-core/src/utils/text.ts
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(fix)

#683 chore(release): 🔖 publish the version 1.0.0-beta.9
  packages/s2-core/package.json
Labels: pr(chore)

#685 fix(facet): render v scrollbar close #681
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#682 feat: ♻️ refactor the layout logic and provide tree layout-widths
  packages/s2-core/__tests__/data/grid-analysis-data.ts
  packages/s2-core/__tests__/spreadsheet/custom-tree-header-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/spreadsheet/filter-sheet-spec.tsx
  packages/s2-core/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-core/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-core/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-core/__tests__/spreadsheet/pressure-test-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/build-table-hierarchy-spec.tsx
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(feature)

#691 docs: fix measure-comparison demo's corner cell's style and last col's line style
  s2-site/examples/case/measure-comparison/demo/basic.tsx
Labels: pr(documentation)

#695 chore: upgrage the s2 version for the site
  s2-site/examples/case/group-drill-down/demo/meta.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#697 test(interaction): add data cell multi selection test
  .gitignore
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  s2-site/docs/manual/getting-started.zh.md
Labels: pr(test)

#699 docs: 使用文档走查
  s2-site/docs/manual/advanced/performance.zh.md
  s2-site/docs/manual/basic/base-concept.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/basic.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/site/pages/index.zh.tsx
Labels: pr(documentation)

#698 fix(scroll): fix cannot scroll by mouse or touch tablet
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/cornerBBox.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
  packages/s2-core/src/facet/header/col.ts
Labels: pr(fix)

#701 feat: :sparkles: make the head width change with the width of the sheet
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/components/header/index.less
  packages/s2-core/src/components/header/index.tsx
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
Labels: pr(feature)

#704 fix: :bug: solve the issue that the selectedCellsSpotlight does not work
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#703 fix(copy): fix copy data format problem
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#708 docs(interaction): add custom interaction example
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/custom/API.en.md
  s2-site/examples/interaction/custom/API.zh.md
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
  s2-site/examples/interaction/custom/demo/meta.json
  s2-site/examples/interaction/custom/index.en.md
  s2-site/examples/interaction/custom/index.zh.md
Labels: pr(documentation)

#706 fix(hd-adapter): fix wrong container style when zoom scale changed
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-core/src/utils/is-mobile.ts
Labels: pr(fix)

#709 fix(facet): adjustXY in pagination
  packages/s2-core/src/components/sheets/table-sheet/index.tsx
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#707 fix(facet): scrollbar offset
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  packages/s2-core/src/ui/scrollbar/interface.ts
Labels: pr(fix)

#702 feat: merged cell related documents, tests and some refactoring
  packages/s2-core/__tests__/spreadsheet/merge-cells-spec.tsx
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cells.spec.ts
  packages/s2-core/src/cell/index.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/merge-cells.ts
  s2-site/docs/manual/advanced/interaction/merge-cell.en.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/interaction/advanced/demo/merge-cells.ts
  s2-site/examples/interaction/advanced/demo/merge-cells.tsx
  s2-site/examples/interaction/advanced/demo/meta.json
Labels: pr(feature)

#710 test: fix hd tests
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
Labels: pr(test)

#712 docs: homepage and header UI
  s2-site/docs/api/components/header.zh.md
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/site/pages/index.less
  s2-site/site/pages/index.zh.tsx
Labels: pr(fix)

#713 chore: add codeql and update README
  .github/workflows/codeql-analysis.yml
  README.en-US.md
  README.md
Labels: pr(chore)

#715 fix(components): switcher support receive antd popover props for resolve scroling with the page
  packages/s2-core/__tests__/spreadsheet/switcher-spec.tsx
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/src/components/switcher/index.tsx
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/examples/react-component/switcher/demo/table.tsx
Labels: pr(fix)

#720 fix(scroll): sync row scroll offset when corner cell resized
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#719 docs: optimize advanced sort's style
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/gatsby-browser.js
Labels: pr(documentation)

#721 docs: complete single-population-proportion demo
  .markdownlint.json
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  s2-site/examples/case/performance-compare/index.en.md
  s2-site/examples/case/performance-compare/index.zh.md
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/case/proportion/demo/meta.json
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/case/proportion/design.zh.md
  s2-site/examples/data/single-population-proportion.json
Labels: pr(documentation)

#724 docs: optimize the demo of the group drill-down sheet
  packages/s2-core/__tests__/data/grid-analysis-data.ts
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
  s2-site/examples/case/comparison/demo/meta.json
  s2-site/examples/case/comparison/demo/multiple-people-comparison.tsx
  s2-site/examples/case/kpi-strategy/demo/basic.tsx
  s2-site/examples/case/kpi-strategy/demo/meta.json
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/case/proportion/demo/meta.json
Labels: pr(documentation), 🚨 test failed

#726 docs: change index comparison sheet width and height
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
Labels: pr(documentation), 🚨 test failed

#722 fix(table): table sort fix && col layout fix
  packages/s2-core/__tests__/unit/utils/cell/cell.spec.ts
  packages/s2-core/__tests__/unit/utils/cell/table-col-cell.spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/cell/table-corner-cell.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/cell/header-cell.ts
  packages/s2-core/src/utils/cell/table-col-cell.ts
  packages/s2-core/src/utils/layout/add-detail-type-sort-icon.ts
Labels: pr(fix), 🚨 test failed

#727 fix(scroll): scroll by group
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#729 test: add scroll group test
  packages/s2-core/__tests__/bugs/issue-565-spec.tsx
  packages/s2-core/__tests__/spreadsheet/scroll-spec.tsx
Labels: pr(test)

#730 test: add reset row scroll when corner cell resized test
  packages/s2-core/__tests__/bugs/issue-720-spec.tsx
  packages/s2-core/__tests__/unit/ui/hd-adapter-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
Labels: pr(test)

#733 chore: update less loader
  package.json
  yarn.lock
Labels: pr(chore), 🚨 test failed

#731 fix: difficult to select the tooltip after click then merged cell
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/interaction/base-interaction/click/merged-cells-click.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/interaction/merge-cells.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/interaction/advanced/demo/merge-cells.tsx
Labels: pr(fix), 🚨 test failed

#735 test: fix scroll test case
  package.json
  packages/s2-core/__tests__/bugs/issue-720-spec.tsx
  packages/s2-core/__tests__/spreadsheet/scroll-spec.tsx
  packages/s2-core/scripts/test-live.mjs
Labels: pr(test)

#736 chore: add the mirror.yml
  .github/workflows/mirror.yml
Labels: pr(chore)

#734 docs(useage): 使用文档图片优化
  s2-site/docs/manual/advanced/data-process/pivot.zh.md
  s2-site/docs/manual/advanced/hd-adapter.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/custom-header-action-icon.zh.md
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/docs/manual/advanced/layout/pivot.zh.md
  s2-site/docs/manual/advanced/layout/table.zh.md
  s2-site/docs/manual/advanced/performance.zh.md
  s2-site/docs/manual/basic/analysis/export.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/base-concept.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/gatsby-config.js
  s2-site/site/pages/index.zh.tsx
Labels: pr(documentation)

#705 fix: 🐛 interactorBorder宽度自适应
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#737 fix: multi measure render wrong and optimize sortedDimensionValues
  packages/s2-core/__tests__/bugs/issue-725-spec.tsx
  packages/s2-core/__tests__/data/data-issue-725.json
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-row-value-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/sort-action.ts
Labels: pr(fix)

#732 feat(interaction): shift interval select
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/shift-multi-selection.ts
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#740 chore(release): 1.0.0-beta.10
  packages/s2-core/package.json
Labels: pr(chore)

#739 refactor: rename demissions to dimensions in advanced sort's code and…
  packages/s2-core/src/components/advanced-sort/index.less
  packages/s2-core/src/components/advanced-sort/index.tsx
  s2-site/docs/api/components/advanced-sort.zh.md
Labels: pr(refactor)

#741 docs: update cases module style of the homepage
  packages/s2-core/__tests__/data/mock-dataset.json
  packages/s2-core/__tests__/unit/data-process/README_zh.md
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/custom/headerActionIcons.zh.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/manual/advanced/performance.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/base-concept.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/examples/case/comparison/design.zh.md
  s2-site/examples/case/kpi-strategy/design.zh.md
  s2-site/examples/react-component/drill-dwon/demo/meta.json
  s2-site/examples/react-component/switcher/demo/meta.json
  s2-site/site/pages/index.less
  s2-site/site/pages/index.zh.tsx
Labels: pr(documentation)

#743 docs(custom-tree): use transformCustomTreeItems of antv/s2
  s2-site/examples/custom/custom-tree/demo/custom-tree.ts
Labels: pr(documentation)

#744 fix: 🐛 修复1px边框错位的问题
  packages/s2-core/src/cell/base-cell.ts
Labels: pr(fix)

#742 fix(placeholder): placeholder issue
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/utils/text.spec.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#748 chore(release): 1.0.0-beta.11
  packages/s2-core/package.json
Labels: pr(chore)

#749 fix(tooltip): tooltip don't show
  packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/shift-multi-selection-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/shift-multi-selection.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
Labels: pr(fix)

#750 feat: 🎸 demo添加筛选排序
  s2-site/examples/case/data-preview/demo/index.tsx
Labels: pr(feature)

#752 fix(copy): do not copy when no cell selected
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#753 docs: 💄 update the screenshot and tweak the demos
  packages/s2-react/__tests__/spreadsheet/sheet-custom-tooltip-spec.tsx
  s2-site/docs/manual/advanced/performance.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/analysis/conditions/demo/background.ts
  s2-site/examples/analysis/conditions/demo/gradient-interval.ts
  s2-site/examples/analysis/conditions/demo/icon.ts
  s2-site/examples/analysis/conditions/demo/interval.ts
  s2-site/examples/analysis/conditions/demo/multi-background.ts
  s2-site/examples/analysis/conditions/demo/table-text.ts
  s2-site/examples/analysis/conditions/demo/text.ts
  s2-site/examples/basic/pivot/demo/grid.ts
  s2-site/examples/basic/pivot/demo/meta.json
  s2-site/examples/basic/pivot/demo/tree.ts
  s2-site/examples/basic/pivot/design.en.md
  s2-site/examples/basic/pivot/design.zh.md
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/case/comparison/demo/meta.json
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/case/data-preview/demo/meta.json
  s2-site/examples/case/performance-compare/demo/basic.tsx
  s2-site/examples/case/performance-compare/demo/meta.json
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/case/proportion/demo/meta.json
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/case/proportion/index.en.md
  s2-site/examples/case/proportion/index.zh.md
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
  s2-site/examples/data/compare.json
  s2-site/examples/interaction/advanced/demo/merge-cells.tsx
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/pivot-link-jump.ts
  s2-site/examples/interaction/advanced/demo/table-link-jump.ts
  s2-site/examples/interaction/basic/demo/auto-reset-sheet-style.ts
  s2-site/examples/interaction/basic/demo/click-highlight.ts
  s2-site/examples/interaction/basic/demo/hover.ts
  s2-site/examples/interaction/basic/demo/meta.json
  s2-site/examples/interaction/basic/demo/resize.ts
  s2-site/examples/interaction/basic/demo/select-highlight.ts
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
  s2-site/examples/react-component/switcher/demo/pivot.tsx
  s2-site/examples/react-component/switcher/demo/table.tsx
  s2-site/examples/react-component/tooltip/demo/basic.ts
  s2-site/examples/react-component/tooltip/demo/custom.tsx
  s2-site/examples/react-component/tooltip/demo/operation.ts
  s2-site/examples/react-component/tooltip/demo/render-tooltip.tsx
  s2-site/examples/theme/custom/demo/custom-schema.ts
  s2-site/examples/theme/custom/demo/meta.json
  s2-site/examples/theme/default/demo/meta.json
  s2-site/examples/theme/default/index.en.md
  s2-site/examples/theme/default/index.zh.md
  s2-site/package.json
  s2-site/site/pages/index.zh.tsx
  s2-site/yarn.lock
Labels: pr(documentation)

#758 chore: fix build deps
  package.json
Labels: pr(chore)

#759 chore: test lint
  .github/workflows/lint.yml
Labels: pr(chore)

#763 fix(table): table sheet sort
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#760 chore: fix bundle faild
  .eslintrc
  .github/workflows/auto-release.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  lerna.json
  packages/s2-core/__tests__/unit/ui/hd-adapter-spec.ts
  packages/s2-react/package.json
  packages/s2-react/src/components/tooltip/components/divider.tsx
  packages/s2-react/src/components/tooltip/components/head-info.tsx
  packages/s2-react/src/components/tooltip/components/interpretation.tsx
  packages/s2-react/src/components/tooltip/components/simple-tips.tsx
  packages/s2-react/vite.config.ts
  yarn.lock
Labels: pr(chore)

#764 chore: fix bundle faild
  .eslintrc
  .github/workflows/auto-release.yml
  .github/workflows/lint.yml
  .github/workflows/site-deploy.yml
  .github/workflows/test.yml
  lerna.json
  packages/s2-core/__tests__/unit/ui/hd-adapter-spec.ts
  packages/s2-react/package.json
  packages/s2-react/src/components/tooltip/components/divider.tsx
  packages/s2-react/src/components/tooltip/components/head-info.tsx
  packages/s2-react/src/components/tooltip/components/interpretation.tsx
  packages/s2-react/src/components/tooltip/components/simple-tips.tsx
  packages/s2-react/vite.config.ts
  yarn.lock
Labels: pr(chore)

#761 docs: tooltip and sort docs and demos update
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/basic.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/analysis/sort/demo/group-sort.tsx
  s2-site/examples/analysis/sort/demo/meta.json
  s2-site/examples/react-component/tooltip/demo/basic.tsx
  s2-site/examples/react-component/tooltip/demo/custom-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom.tsx
  s2-site/examples/react-component/tooltip/demo/meta.json
  s2-site/examples/react-component/tooltip/demo/operation.tsx
  s2-site/examples/react-component/tooltip/demo/render-tooltip.tsx
Labels: pr(documentation)

#762 docs: 📝 update the screenshot and tweak the demos
  s2-site/examples/analysis/conditions/demo/background.ts
  s2-site/examples/analysis/conditions/demo/gradient-interval.ts
  s2-site/examples/analysis/conditions/demo/icon.ts
  s2-site/examples/analysis/conditions/demo/interval.ts
  s2-site/examples/analysis/conditions/demo/meta.json
  s2-site/examples/analysis/conditions/demo/multi-background.ts
  s2-site/examples/analysis/conditions/demo/text.ts
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/examples/analysis/sort/demo/custom-list.ts
  s2-site/examples/analysis/sort/demo/custom-measure.ts
  s2-site/examples/analysis/sort/demo/custom-method.ts
  s2-site/examples/analysis/sort/demo/custom-sort-func.ts
  s2-site/examples/analysis/sort/demo/custom-totals.ts
  s2-site/examples/analysis/sort/demo/group-sort.tsx
  s2-site/examples/analysis/sort/demo/meta.json
  s2-site/examples/analysis/sort/demo/table-sort.ts
  s2-site/examples/analysis/totals/demo/meta.json
  s2-site/examples/analysis/totals/demo/tree.ts
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/case/proportion/demo/meta.json
  s2-site/examples/case/proportion/index.en.md
  s2-site/examples/case/proportion/index.zh.md
  s2-site/examples/custom/custom-cell/demo/meta.json
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
  s2-site/examples/custom/custom-icon/demo/meta.json
  s2-site/examples/custom/custom-layout/demo/custom-coordinate.ts
  s2-site/examples/custom/custom-layout/demo/meta.json
  s2-site/examples/custom/custom-tree/demo/meta.json
  s2-site/examples/interaction/custom/demo/meta.json
  s2-site/examples/react-component/drill-dwon/demo/meta.json
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/examples/react-component/header/demo/meta.json
  s2-site/examples/react-component/sheet/demo/meta.json
  s2-site/examples/react-component/sheet/demo/pivot.tsx
  s2-site/examples/react-component/switcher/demo/meta.json
  s2-site/examples/react-component/switcher/demo/pure-switcher.tsx
  s2-site/examples/react-component/tooltip/demo/meta.json
  s2-site/examples/react-component/tooltip/demo/render-tooltip.tsx
Labels: pr(documentation)

#765 chore(release): s2@1.0.0 s2-react@1.0.0
  CHANGELOG.md
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/unit/ui/hd-adapter-spec.ts
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#766 docs: update packages
  README.en-US.md
  README.md
  packages/s2-core/README.md
  packages/s2-react/README.md
Labels: pr(documentation)

#768 docs: tweak all documents table style
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/components/advanced-sort.zh.md
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/common/conditions.zh.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/common/sort-params.zh.md
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/advanced/custom/hook.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/gatsby-browser.js
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#769 docs: update tooltip docs
  s2-site/examples/react-component/tooltip/demo/meta.json
  s2-site/examples/react-component/tooltip/demo/render-tooltip.tsx
Labels: pr(documentation)

#770 chore: external antd
  packages/s2-react/package.json
  packages/s2-react/vite.config.ts
Labels: pr(chore)

#771 chore(release): @antv/s2@1.0.2 @antv/s2-react@1.0.2
  CHANGELOG.md
  package.json
  packages/s2-core/CHANGELOG.md
  packages/s2-core/jest.config.json
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-react/vite.config.ts
  s2-site/package.json
Labels: pr(chore)

#773 docs: update site lock
  s2-site/yarn.lock
Labels: pr(documentation)

#774 chore: cancel auto deploy site
  .github/workflows/auto-release.yml
  .github/workflows/site-deploy.yml
  s2-site/site/pages/index.zh.tsx
Labels: pr(chore)

#776 chore: update the README.en-US.md
  README.en-US.md
Labels: pr(chore)

#775 chore: add the contact info and update the README
  README.md
Labels: pr(chore)

#778 chore: replace ts-jest with @swc/jest
  package.json
  packages/s2-core/jest.config.json
  packages/s2-react/jest.config.json
  yarn.lock
Labels: pr(chore)

#779 chore: support auto release latest
  .github/workflows/auto-release.yml
  .github/workflows/lint.yml
  .releaserc.js
  README.en-US.md
  README.md
  package.json
  packages/s2-core/README.md
  packages/s2-react/README.md
Labels: pr(chore)

#781 fix(copy): copy data with data sorted or filtered
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#782 test: add tooltip tests
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
Labels: pr(test)

#780 chore: only build s2-core esm for s2-react
  .github/workflows/compressed-size.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  package.json
Labels: pr(chore)

#783 docs: add tooltip note for s2-core
  packages/s2-core/README.md
  s2-site/docs/manual/getting-started.zh.md
Labels: pr(documentation)

#784 feat: add util export
  packages/s2-core/src/utils/index.ts
Labels: pr(feature)

#786 fix(interaction): move hideColumns method to interaction scope
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
Labels: pr(fix)

#787 docs: add the demo of Custom Click Tooltip and upgrade the gatsby-theme
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
  s2-site/examples/react-component/tooltip/demo/custom-interaction-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/meta.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#789 chore(release): s2-core@1.0.3-beta.1 s2-react@1.0.3-beta.1
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#785 fix: optimize handleGroupSort and add pivot sheet basic class tests
  packages/s2-core/__tests__/unit/common/store/index.spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/common/store/index.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
Labels: pr(fix)

#793 chore: fix typos and update the main script
  package.json
  packages/s2-react/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/utils/drill-down.ts
Labels: pr(chore)

#788 docs: tweak tooltips in merge-cells
  packages/s2-core/src/ui/tooltip/index.ts
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/interaction/advanced/demo/merge-cells.tsx
Labels: pr(documentation)

#795 fix: remove exports config close #790
  packages/s2-react/package.json
Labels: pr(fix)

#798 fix: solve the wrong collapse status and tweak the default icon size for the corner cell and close #791
  package.json
  packages/s2-core/package.json
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#800 refactor: s2-react default options and add merge test
  packages/s2-react/__tests__/spreadsheet/merge-cells-spec.tsx
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-react/__tests__/unit/utils/merge-spec.ts
  packages/s2-react/src/common/constant/options.ts
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/utils/index.ts
  packages/s2-react/src/utils/merge.ts
  packages/s2-react/src/utils/tooltip.tsx
Labels: pr(refactor)

#802 docs: add adaptive docs
  s2-site/docs/manual/advanced/adaptive.en.md
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/get-instance.en.md
  s2-site/docs/manual/advanced/hd-adapter.en.md
Labels: pr(documentation)

#796 fix(components): fix cannot update table size by container resized
  .eslintrc
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/bugs/issue-609-spec.tsx
  packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.less
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/hooks.ts
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/hooks/index.ts
  packages/s2-react/src/hooks/usePaginationEffect.ts
  packages/s2-react/src/hooks/useResizeEffect.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: pr(fix)

#803 fix: tooltip childNode repete show and add test
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/src/ui/tooltip/index.ts
Labels: pr(fix)

#805 chore: add public ding talk group notify
  .github/workflows/auto-release.yml
  README.en-US.md
  README.md
Labels: pr(chore)

#809 chore: update the scripts
  package.json
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#810 chore(release): 🔖 publish the new version [ci skip]
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#811 docs: update CHANGELOG
  CHANGELOG.md
  packages/s2-core/CHANGELOG.md
  packages/s2-react/CHANGELOG.md
Labels: pr(documentation)

#814 chore: optimize release commit msg
  .github/workflows/auto-release.yml
  .github/workflows/lint.yml
  .github/workflows/manual-release-notify.yml
  .github/workflows/release-notify.yml
  .github/workflows/test.yml
  .releaserc.js
  lerna.json
  s2-site/docs/manual/faq.zh.md
Labels: pr(chore)

#815 chore: update the lock for the site
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#817 fix(copy): remove '' on copied data
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#816 fix(facet): getAdjustedScrollY add negative check
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#823 docs: markdown link not work
  s2-site/docs/api/components/header.en.md
  s2-site/docs/manual/advanced/adaptive.en.md
  s2-site/docs/manual/advanced/interaction/merge-cell.en.md
  s2-site/docs/manual/advanced/layout/pivot.en.md
  s2-site/docs/manual/advanced/layout/table.en.md
  s2-site/docs/manual/basic/analysis/export.en.md
  s2-site/docs/manual/basic/analysis/switcher.en.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/examples/interaction/advanced/demo/merge-cells.tsx
Labels: pr(documentation)

#824 fix(facet): remove extra row node if row fields is empty
  package.json
  packages/s2-core/__tests__/bugs/issue-292-spec.ts
  packages/s2-core/__tests__/bugs/issue-368-spec.ts
  packages/s2-core/__tests__/bugs/issue-372-spec.ts
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/bugs/issue-507-spec.ts
  packages/s2-core/__tests__/bugs/issue-511-spec.ts
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/bugs/issue-720-spec.ts
  packages/s2-core/__tests__/bugs/issue-725-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/build-header-hierarchy.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#827 docs(switcher): fix switcher docs example
  s2-site/docs/manual/basic/analysis/export.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/examples/react-component/switcher/demo/table.tsx
Labels: pr(documentation)

#826 chore: 🤖 auto sync site s2 lock
  .github/workflows/auto-release.yml
  .github/workflows/sync-site-lock-with-pr.yml
  package.json
  s2-site/package.json
Labels: pr(chore)

#829 docs: fix invalid contributing step
  .github/workflows/sync-site-lock-with-pr.yml
  README.en-US.md
  README.md
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/sort-params.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(documentation)

#830 test: add merge-cells.ts test
  packages/s2-core/__tests__/unit/utils/merge-cells.spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/utils/interaction/merge-cells.ts
Labels: pr(test)
