Repository antvis/S2, pull requests merged in 2021-10, with the labels that each got.

#398 🐛 fix(layout): layout performance optimization, issue #388
  packages/s2-core/src/facet/layout/node.ts
Labels: 🐛 bug

#397 test(interaction): add base interaction tests
  .github/workflows/emoji-helper.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .gitignore
  lerna.json
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/event-controller.ts
  s2-site/docs/manual/advanced/interaction/custom.zh.md
Labels: pr(test)

#399 feat: ✨ part drill down based on the new data process
  packages/s2-core/__tests__/data/data-drill-down.ts
  packages/s2-core/__tests__/data/mock-dataset.json
  packages/s2-core/__tests__/data/mock-drill-down-dataset.json
  packages/s2-core/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-process/table-spec.tsx
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-row-value-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/node-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/util.ts
  packages/s2-core/__tests__/unit/utils/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/drill-down.ts
  packages/s2-core/src/utils/drill-down/drill-down-layout.ts
  packages/s2-core/src/utils/drill-down/helper.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/text.ts
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(feature)

#407 chore(release): 🔖 publish the new version of v0.1.14
  CHANGELOG.md
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#408 fix: expand corner cell width, make it nowrap initially
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#413 docs: add graphic style docs
  .markdownlint.json
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/api/graphic.en.md
  s2-site/docs/api/graphic.zh.md
  s2-site/docs/common/conditions.zh.md
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/common/view-meta.zh.md
Labels: pr(documentation)

#414 refactor(interaction): simplify logic
  .github/workflows/release-helper.yml
  .github/workflows/release-notify.yml
  .husky/pre-push
  packages/s2-core/__tests__/spreadsheet/custom/custom-interaction.tsx
  packages/s2-core/__tests__/unit/interaction/base-event-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/base-event.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/row-col-resize.ts
  s2-site/docs/api/basic-class/interaction.zh.md
Labels: pr(refactor)

#412 fix(export): export feature
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#431 fix(interaction): invalid "hiddenColumnFields" config close #417
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/hide-columns.ts
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/examples/interaction/demo/custom.ts
  s2-site/examples/interaction/demo/hide-columns.ts
Labels: pr(fix)

#439 fix(interaction): support batch hidden columns
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/unit/common/store/index.spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/store/index.ts
  packages/s2-core/src/components/index.tsx
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(fix)

#441 fix(interaction): optimize reset state logic
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/components/index.tsx
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#443 chore: update core lib version
  s2-site/package.json
Labels: pr(chore)

#442 chore(release): :bookmark: publish the new version [ci skip]
  .github/workflows/release-notify.yml
  CHANGELOG.md
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/package.json
Labels: pr(chore)

#445 fix: :bug: solve the wrong numbers of headerActionIcons config in drill-down mode
  packages/s2-core/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-core/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/utils/drill-down.ts
Labels: pr(fix)

#449 chore(examples): 🏗️ reorganize the file structure of examples
  s2-site/examples/analysis/switcher/demo/pivot-with-children.tsx
  s2-site/examples/analysis/switcher/demo/pivot.tsx
  s2-site/examples/analysis/switcher/demo/table.tsx
  s2-site/examples/basic/pivot/demo/grid.ts
  s2-site/examples/basic/pivot/demo/meta.json
  s2-site/examples/basic/pivot/demo/tree.ts
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/conditions/advanced/demo/gradient-interval.ts
  s2-site/examples/conditions/advanced/demo/meta.json
  s2-site/examples/conditions/advanced/demo/multi-background.ts
  s2-site/examples/conditions/basic/demo/background.ts
  s2-site/examples/conditions/basic/demo/icon.ts
  s2-site/examples/conditions/basic/demo/interval.ts
  s2-site/examples/conditions/basic/demo/meta.json
  s2-site/examples/conditions/basic/demo/table-text.ts
  s2-site/examples/conditions/basic/demo/text.ts
  s2-site/examples/config/theme/API.en.md
  s2-site/examples/config/theme/API.zh.md
  s2-site/examples/config/theme/demo/colorful-blue.ts
  s2-site/examples/config/theme/demo/default.ts
  s2-site/examples/config/theme/demo/meta.json
  s2-site/examples/config/theme/demo/simple-blue.ts
  s2-site/examples/config/theme/index.en.md
  s2-site/examples/config/theme/index.zh.md
  s2-site/examples/config/totals/API.en.md
  s2-site/examples/config/totals/API.zh.md
  s2-site/examples/config/totals/demo/basic.ts
  s2-site/examples/config/totals/demo/meta.json
  s2-site/examples/config/totals/demo/multiple-values.ts
  s2-site/examples/config/totals/demo/tree.ts
  s2-site/examples/config/totals/index.en.md
  s2-site/examples/config/totals/index.zh.md
  s2-site/examples/data/basic.json
  s2-site/examples/interaction/advanced/API.en.md
  s2-site/examples/interaction/advanced/API.zh.md
  s2-site/examples/interaction/advanced/demo/custom.ts
  s2-site/examples/interaction/advanced/demo/hide-columns.ts
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/pivot-link-jump.ts
  s2-site/examples/interaction/advanced/demo/table-link-jump.ts
  s2-site/examples/interaction/advanced/index.en.md
  s2-site/examples/interaction/advanced/index.zh.md
  s2-site/examples/interaction/basic/API.en.md
  s2-site/examples/interaction/basic/API.zh.md
  s2-site/examples/interaction/basic/demo/basic.ts
  s2-site/examples/interaction/basic/demo/meta.json
  s2-site/examples/interaction/basic/index.en.md
  s2-site/examples/interaction/basic/index.zh.md
  s2-site/examples/interaction/design.en.md
  s2-site/examples/interaction/design.zh.md
  s2-site/examples/interaction/index.en.md
  s2-site/examples/interaction/index.zh.md
  s2-site/gatsby-config.js
Labels: pr(chore)

#356 feat: 🎸 added ability to filter field values
  packages/s2-core/__tests__/spreadsheet/filter-sheet-spec.tsx
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: pr(feature)

#454 refactor: ♻️optimize the logic of the pagination component close #382
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/components/drill-down/index.tsx
  packages/s2-core/src/components/export/index.tsx
  packages/s2-core/src/components/pagination/index.tsx
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/hooks.ts
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/components/sheets/table-sheet/index.tsx
Labels: pr(refactor)

#455 fix: :bug: correct the condition of the function adustTotalNodesCoordinate and close #448
  packages/s2-core/rollup.config.js
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#456 chore: :pencil2: fix typos for the id of dataCell
  packages/s2-core/src/utils/cell/data-cell.ts
Labels: pr(chore)

#457 docs: 📝 add the document and example of custom header action icons
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/header-action-icon.en.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/manual/advanced/interaction/custom-header-action-icon.en.md
  s2-site/docs/manual/advanced/interaction/custom-header-action-icon.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.en.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/docs/manual/advanced/interaction/link-jump.en.md
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/examples/interaction/advanced/API.zh.md
  s2-site/examples/interaction/advanced/demo/custom-header-action-icon.tsx
  s2-site/examples/interaction/advanced/demo/meta.json
Labels: pr(documentation)

#466 fix(export): 🐛 solve the table sheet export problem and close #446
  packages/s2-core/__tests__/bugs/issue-446-spec.tsx
  packages/s2-core/__tests__/data/data-issue-446.json
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#459 fix(table): scroll position issue when re-render
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
Labels: pr(fix)

#471 fix: fix merged cells can't be sorted and dragged
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/utils/interaction/merge-cells.ts
Labels: pr(fix)

#483 docs: :recycle: optimism the structure of docs and fix the typos
  s2-site/docs/manual/basic/analysis/export.en.md
  s2-site/docs/manual/basic/analysis/export.zh.md
  s2-site/docs/manual/basic/copy.en.md
  s2-site/docs/manual/contribution.en.md
  s2-site/docs/manual/getting-started.en.md
  s2-site/examples/analysis/export/API.en.md
  s2-site/examples/analysis/export/API.zh.md
  s2-site/examples/analysis/export/demo/export.tsx
  s2-site/examples/analysis/export/demo/meta.json
  s2-site/examples/analysis/export/demo/table.tsx
  s2-site/examples/analysis/export/index.en.md
  s2-site/examples/analysis/export/index.zh.md
  s2-site/examples/analysis/table/index.zh.md
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#488 feat(util): add generateId export function
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/layout/index.ts
Labels: ⚡ enhancement, pr(feature)

#486 fix: :bug: correct the wrong condition to show the default headerActionIcons for the detail table
  packages/s2-core/src/cell/table-col-cell.ts
Labels: pr(fix)

#489 fix: :bug: prevent the cell click event when clicking the HeaderActionIcon and close #409 #452
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/drill-down.ts
Labels: pr(fix)

#491 fix: cannot hidden columns
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(fix)

#493 fix: 🐛 event disposal on facet destroy
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#500 fix: :bug: set the default page and close #473
  packages/s2-core/src/components/pagination/index.tsx
Labels: pr(fix)
