Repository antvis/S2, pull requests merged in 2021-09, with the labels that each got.

#269 fix(data-cell): cycle dependence bugs
  packages/s2-core/src/cell/data-cell.ts
Labels: bug, PR: unreviewed

#270 feat: add pointer cursor for link field text
  packages/s2-core/src/cell/base-cell.ts
Labels: pr(feature)

#268 chore(ci): ci enhance
  .eslintignore
  .github/workflows/ci.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/lint.yml
  .github/workflows/pr-auto-assign-reviewer.yml
  .github/workflows/pr-auto-set-label.yml
  .github/workflows/pr-notify.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/preview-start.yml
  .github/workflows/preview.yml
  .github/workflows/rebase.yml
  README.md
  package.json
  packages/s2-core/__tests__/data/data-accuracy.ts
  packages/s2-core/__tests__/data/data-drill-down.ts
  packages/s2-core/__tests__/unit/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/package.json
  packages/s2-core/src/utils/export/index.ts
  s2-site/gatsby-config.js
  s2-site/package.json
  s2-site/site/pages/playground.en.tsx
  s2-site/site/pages/playground.zh.tsx
  tsconfig.json
  yarn.lock
Labels: PR: unreviewed, pr(chore), 🗓 weekly

#271 fix: replace circular deps
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/multi-click.ts
Labels: PR: reviewed-approved, pr(fix), 🗓 weekly

#272 docs: update badge
  .github/workflows/ci.yml
  README.en-US.md
  README.md
Labels: PR: unreviewed, pr(chore), 🗓 weekly

#265 test(dataset): finish dataset test
  packages/s2-core/__tests__/core/README_zh.md
  packages/s2-core/__tests__/core/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/core/data-process/table-spec.tsx
  packages/s2-core/__tests__/data/mock-dataset.json
  packages/s2-core/__tests__/data/standard-config.ts
  packages/s2-core/__tests__/data/standard-spreadsheet-data.json
  packages/s2-core/__tests__/data/standard-total-data.json
  packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
  packages/s2-core/__tests__/unit/core/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/core/data-process/table-spec.tsx
  packages/s2-core/__tests__/unit/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-row-value-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-sort-data-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-tree-dataset-spec.ts
  packages/s2-core/__tests__/unit/dataset/split-total-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/__tests__/unit/utils/split-total-spec.ts
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/jest.config.json
  packages/s2-core/tsconfig.json
Labels: PR: unreviewed, pr(test), 🗓 weekly

#274 test: add test timeout
  .github/workflows/ci.yml
  .github/workflows/pr-auto-assign-reviewer.yml
  .github/workflows/pr-auto-set-label.yml
  README.en-US.md
  README.md
  package.json
  packages/s2-core/jest.config.json
  packages/s2-core/package.json
  packages/s2-core/src/cell/base-cell.ts
  yarn.lock
Labels: PR: unreviewed, pr(test)

#276 fix: bundle file declaration generation
  .eslintignore
  .eslintrc
  .github/workflows/ci.yml
  .github/workflows/pr-auto-assign-reviewer.yml
  .github/workflows/pr-auto-set-label.yml
  package.json
  packages/s2-core/__tests__/core/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/core/data-process/table-spec.tsx
  packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-row-value-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-event-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/split-total-spec.ts
  packages/s2-core/externals.d.ts
  packages/s2-core/jest.config.json
  packages/s2-core/package.json
  packages/s2-core/rollup.config.js
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/utils/layout/get-dims-condition-by-node.ts
  packages/s2-core/tsconfig.json
  yarn.lock
Labels: PR: partially-approved, pr(fix)

#277 fix: 🐛 solve the issue that the 'customHeaders' does not work
  .github/PULL_REQUEST_TEMPLATE.md
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
Labels: PR: unreviewed, pr(fix)

#283 fix: table mode pagination issue
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/layout/interface.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: PR: reviewed-approved, pr(fix)

#288 fix: table dataset spec
  packages/s2-core/src/data-set/table-data-set.ts
Labels: PR: reviewed-approved, pr(fix)

#280 feat: :sparkles: init examples gallery for the site
  s2-site/README.md
  s2-site/docs/api/general/dataCfg.zh.md
  s2-site/docs/api/general/options.zh.md
  s2-site/examples/basic/pivot/API.en.md
  s2-site/examples/basic/pivot/API.zh.md
  s2-site/examples/basic/pivot/demo/grid.ts
  s2-site/examples/basic/pivot/demo/meta.json
  s2-site/examples/basic/pivot/demo/tree.ts
  s2-site/examples/basic/pivot/design.en.md
  s2-site/examples/basic/pivot/design.zh.md
  s2-site/examples/basic/pivot/index.en.md
  s2-site/examples/basic/pivot/index.zh.md
  s2-site/examples/data/basic.json
  s2-site/examples/gallery/index.en.md
  s2-site/examples/gallery/index.zh.md
  s2-site/gatsby-browser.js
  s2-site/gatsby-config.js
  s2-site/package.json
  s2-site/yarn.lock
Labels: PR: reviewed-approved, 🗓 weekly

#281 refactor: remove indicateConditionValues related codes
  .github/workflows/pr-auto-assign-reviewer.yml
  README.en-US.md
  README.md
  packages/s2-core/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-core/__tests__/unit/utils/condition.spec.ts
  packages/s2-core/__tests__/unit/utils/condition/conditions-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/sheet-type/index.ts
  packages/s2-core/src/utils/condition/condition.ts
  packages/s2-core/src/utils/condition/generate-condition.ts
  packages/s2-core/src/utils/merge.ts
Labels: PR: reviewed-approved, pr(refactor)

#284 feat: add group sort in col's values and refactor tooltip's style
  .github/workflows/pr-auto-assign-reviewer.yml
  packages/s2-core/__tests__/data/mock-dataset.json
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/facet/header/base.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/ui/tooltip/components/detail.tsx
  packages/s2-core/src/ui/tooltip/components/icon.tsx
  packages/s2-core/src/ui/tooltip/components/interpretation.tsx
  packages/s2-core/src/ui/tooltip/components/operation.tsx
  packages/s2-core/src/ui/tooltip/components/operator/index.less
  packages/s2-core/src/ui/tooltip/components/operator/index.tsx
  packages/s2-core/src/ui/tooltip/index.tsx
  packages/s2-core/src/utils/sort-action.ts
Labels: PR: partially-approved, pr(feature)

#297 fix(facet): fix issue #291
  packages/s2-core/src/facet/base-facet.ts
Labels: PR: unreviewed, pr(fix)

#299 fix: 🐛 solve the wrong render state when updating the dataCfg and close #285
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/bugs/issue-285-spec.tsx
  packages/s2-core/__tests__/core/README_zh.md
  packages/s2-core/__tests__/data/issue-285-dataset.json
  packages/s2-core/__tests__/unit/data-process/README_zh.md
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-process/table-spec.tsx
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/sheet-type/index.ts
Labels: PR: partially-approved, pr(fix)

#275 fix(facet): frozen clip and resizer issue
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/cell/table-corner-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/sheet-type/index.ts
  packages/s2-core/src/ui/tooltip/components/operator/index.less
Labels: pr(fix)

#300 chore(release): 🔖 publish v0.1.6
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: PR: partially-approved, pr(chore)

#304 chore(build): update external using regex
  packages/s2-core/rollup.config.js
Labels: PR: partially-approved, pr(chore)

#305 chore: upgrade sharp version to support M1
  s2-site/package.json
Labels: PR: partially-approved, pr(chore)

#306 ci: create emoji-helper
  .github/workflows/emoji-helper.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/pr-auto-assign-reviewer.yml
Labels: PR: partially-approved

#309 feat: ✨ enable users to set the page size of the pagination configuration and close #302
  packages/s2-core/__tests__/bugs/issue-285-spec.tsx
  packages/s2-core/__tests__/data/data-issue-285/data-col-header.json
  packages/s2-core/__tests__/data/data-issue-285/data-without-col-header.json
  packages/s2-core/__tests__/data/issue-285-dataset.json
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/facet/header/frame.ts
Labels: PR: partially-approved, pr(feature)

#314 chore(release): :bookmark: publish v0.1.7
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: PR: partially-approved, pr(chore)

#296 feat(interaction): hidden columns
  .gitignore
  package.json
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/spreadsheet/spread-sheet-with-switcher-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/scripts/test-live.mjs
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/common/icons/svg/index.ts
  packages/s2-core/src/common/icons/svg/svgs.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/switcher/content/index.tsx
  packages/s2-core/src/components/switcher/dimension/index.tsx
  packages/s2-core/src/components/switcher/index.tsx
  packages/s2-core/src/components/switcher/interface.ts
  packages/s2-core/src/components/switcher/item/index.less
  packages/s2-core/src/components/switcher/item/index.tsx
  packages/s2-core/src/components/switcher/item/single-item.tsx
  packages/s2-core/src/components/switcher/util.ts
  packages/s2-core/src/facet/layout/build-header-hierarchy.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/ui/tooltip/components/icon.tsx
  packages/s2-core/src/ui/tooltip/components/operator/index.tsx
  packages/s2-core/src/ui/tooltip/index.tsx
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-core/src/utils/interaction/multi-click.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/api/general/options.zh.md
Labels: PR: partially-approved, pr(feature)

#318 chore(ci): ci enchance
  .github/ISSUE_TEMPLATE/ask-for-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/issue-labeled.yml
  .github/workflows/lint.yml
  .github/workflows/pr-auto-set-label.yml
  .github/workflows/test.yml
  README.en-US.md
  README.md
Labels: PR: partially-approved, pr(chore)

#319 fix(build): update d.ts path
  packages/s2-core/package.json
Labels: PR: partially-approved, pr(fix)

#320 feat: :sparkles: add column header labels for the corner header
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/theme/index.ts
Labels: PR: partially-approved, pr(feature)

#323 chore(ci): use codecov
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.en-US.md
  README.md
  package.json
  packages/s2-core/package.json
  yarn.lock
Labels: PR: partially-approved, pr(chore)

#325 fix(table): revert table fact clip code
  packages/s2-core/src/facet/table-facet.ts
Labels: PR: partially-approved, pr(fix)

#327 fix: row-col-click's show about pivot and table, formatter when showSingleTips
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/ui/tooltip/components/operator/index.less
  packages/s2-core/src/ui/tooltip/components/operator/index.tsx
  packages/s2-core/src/utils/tooltip.ts
Labels: PR: partially-approved, pr(fix)

#321 fix(interaction): add brush move distance validate
  package.json
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/interaction/brush-selection.ts
Labels: PR: partially-approved, pr(fix)

#326 test: add unit test for switcher and hidden columns
  packages/s2-core/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/unit/components/switcher/util.spec.ts
  packages/s2-core/__tests__/unit/utils/attrs-action.spec.ts
  packages/s2-core/__tests__/unit/utils/data-item-type-checker.spec.ts
  packages/s2-core/__tests__/unit/utils/get-all-children-node-height.spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
  packages/s2-core/__tests__/unit/utils/name-generator.spec.ts
  packages/s2-core/__tests__/unit/utils/veen-arr.spec.ts
  packages/s2-core/jest.config.json
  packages/s2-core/src/components/switcher/content/index.tsx
  packages/s2-core/src/components/switcher/util.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/utils/get-irregular-data.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-core/src/utils/is-header-cell-in-viewport.ts
  packages/s2-core/src/utils/selected.ts
Labels: PR: partially-approved, pr(test)

#329 fix(interaction): wrong hidden column icon position
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/components/sheets/table-sheet/index.tsx
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: PR: partially-approved, pr(fix)

#330 chore(ci): fix cannot upload coverage report
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGELOG.md
  package.json
  packages/s2-core/jest.config.json
  packages/s2-core/package.json
  yarn.lock
Labels: PR: partially-approved, pr(chore)

#332 refactor: delete aggregation and optimize doc
  packages/s2-core/src/common/interface/basic.ts
  s2-site/docs/api/general/dataCfg.zh.md
  s2-site/docs/api/general/options.zh.md
Labels: PR: unreviewed, pr(refactor)

#324 feat(interaction): select interaction imporement
  packages/s2-core/__tests__/spreadsheet/custom/custom-interaction.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-core/src/utils/tooltip.ts
Labels: PR: unreviewed, pr(feature)

#328 Feat: add Event doubleClick and contextMenu
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/events/origin.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/components/sheets/table-sheet/index.tsx
  packages/s2-core/src/components/sheets/tabular-sheet/index.tsx
  packages/s2-core/src/interaction/event-controller.ts
Labels: PR: partially-approved, pr(feature)

#331 feat: ✨ add custom header action icons
  packages/s2-core/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/icons/factory.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/common/icons/html-icon.tsx
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/components/drill-down/index.less
  packages/s2-core/src/components/sheets/base-sheet/index.tsx
  packages/s2-core/src/components/sheets/interface.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/ui/tooltip/components/icon.tsx
  packages/s2-core/src/utils/drill-down/helper.ts
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/layout/add-detail-type-sort-icon.ts
  packages/s2-core/src/utils/layout/generate-id.ts
  packages/s2-core/src/utils/merge.ts
Labels: PR: unreviewed, pr(feature)

#335 chore(release): :bookmark: publish v0.1.8
  CHANGELOG.md
  packages/s2-core/package.json
Labels: PR: partially-approved, pr(chore)

#337 test(interaction): add hidden columns tests
  packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: PR: partially-approved, pr(test)

#336 chore: add advanced sort demo
  packages/s2-core/__tests__/data/data-sort.json
  packages/s2-core/__tests__/spreadsheet/less/sort-sheet-spec.less
  packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
Labels: PR: reviewed-changes-requested, pr(chore)

#342 fix: 🐛 add the `spreadsheet` for the meta of the corner cell in tree mode and tweak the style of cell borders
  packages/s2-core/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-process/table-spec.tsx
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/components/dimension-switch/index.less
  packages/s2-core/src/components/dimension-switch/index.tsx
  packages/s2-core/src/components/drill-down/index.less
  packages/s2-core/src/components/drill-down/index.tsx
  packages/s2-core/src/components/icons/index.less
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  s2-site/gatsby-browser.js
Labels: PR: partially-approved, pr(fix)

#338 fix(table): frozen pagination issue
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/utils/frozen-util-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
Labels: PR: unreviewed, pr(fix)

#350 chore: :wrench: fix the site preview
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  package.json
Labels: pr(chore)

#343 docs(interaction): add interaction example
  package.json
  packages/s2-core/__tests__/spreadsheet/link-fields-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/events/index.ts
  packages/s2-core/src/common/constant/events/resize.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/interface.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/interaction/base-event.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/row-col-resize.ts
  s2-site/docs/api/general/options.zh.md
  s2-site/docs/manual/interaction/basic.en.md
  s2-site/docs/manual/interaction/basic.zh.md
  s2-site/docs/manual/interaction/custom.en.md
  s2-site/docs/manual/interaction/custom.zh.md
  s2-site/docs/manual/interaction/hide-columns.en.md
  s2-site/docs/manual/interaction/hide-columns.zh.md
  s2-site/docs/manual/interaction/link-jump.en.md
  s2-site/docs/manual/interaction/link-jump.zh.md
  s2-site/examples/basic/pivot/index.en.md
  s2-site/examples/interaction/API.en.md
  s2-site/examples/interaction/API.zh.md
  s2-site/examples/interaction/demo/basic.ts
  s2-site/examples/interaction/demo/custom.ts
  s2-site/examples/interaction/demo/meta.json
  s2-site/examples/interaction/demo/pivot-link-jump.ts
  s2-site/examples/interaction/demo/table-link-jump.ts
  s2-site/examples/interaction/design.en.md
  s2-site/examples/interaction/design.zh.md
  s2-site/examples/interaction/index.en.md
  s2-site/examples/interaction/index.zh.md
  s2-site/gatsby-config.js
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#352 feat: :sparkles: allow users to set different display condition for headerActionIcons
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/util/sheet-entry.tsx
  packages/s2-core/src/cell/header-cell.ts
Labels: pr(feature)

#353 chore(release): 🔖 release the v0.1.10
  CHANGELOG.md
  package.json
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#354 fix(tooltip): fix cannot render tooltip element when first show
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/ui/tooltip/index.tsx
Labels: pr(fix)

#346 docs(base-concept): add docs for base-concept
  s2-site/docs/manual/base-concept.en.md
  s2-site/docs/manual/base-concept.zh.md
Labels: 📃 documentation, pr(documentation)

#360 docs(base-tutorial): doc for table
  s2-site/docs/manual/table-mode.en.md
  s2-site/docs/manual/table-mode.zh.md
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/basic/table/demo/table.ts
  s2-site/examples/basic/table/index.en.md
  s2-site/examples/basic/table/index.zh.md
Labels: pr(documentation)

#344 docs(conditions): add examples for conditions
  .github/workflows/compressed-size.yml
  .github/workflows/lint.yml
  .markdownlint.json
  .markdownlintignore
  README.en-US.md
  README.md
  package.json
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/__tests__/unit/data-process/README_zh.md
  packages/s2-core/__tests__/unit/utils/condition/conditions.spec.ts
  packages/s2-core/src/cell/data-cell.ts
  s2-site/README.md
  s2-site/docs/api/general/dataCfg.zh.md
  s2-site/docs/api/general/options.zh.md
  s2-site/docs/common/conditions.en.md
  s2-site/docs/common/conditions.zh.md
  s2-site/docs/manual/base-concept.en.md
  s2-site/docs/manual/base-concept.zh.md
  s2-site/docs/manual/basic/conditions.en.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/interaction/basic.zh.md
  s2-site/examples/conditions/advanced/API.en.md
  s2-site/examples/conditions/advanced/API.zh.md
  s2-site/examples/conditions/advanced/demo/gradient-interval.ts
  s2-site/examples/conditions/advanced/demo/meta.json
  s2-site/examples/conditions/advanced/demo/multi-background.ts
  s2-site/examples/conditions/advanced/design.en.md
  s2-site/examples/conditions/advanced/design.zh.md
  s2-site/examples/conditions/advanced/index.en.md
  s2-site/examples/conditions/advanced/index.zh.md
  s2-site/examples/conditions/basic/API.en.md
  s2-site/examples/conditions/basic/API.zh.md
  s2-site/examples/conditions/basic/demo/background.ts
  s2-site/examples/conditions/basic/demo/icon.ts
  s2-site/examples/conditions/basic/demo/interval.ts
  s2-site/examples/conditions/basic/demo/meta.json
  s2-site/examples/conditions/basic/demo/table-text.ts
  s2-site/examples/conditions/basic/demo/text.ts
  s2-site/examples/conditions/basic/design.en.md
  s2-site/examples/conditions/basic/design.zh.md
  s2-site/examples/conditions/basic/index.en.md
  s2-site/examples/conditions/basic/index.zh.md
  s2-site/examples/data/basic.json
  s2-site/gatsby-config.js
  s2-site/site/locale.json
  yarn.lock
Labels: pr(documentation)

#366 fix(tooltip): fix cannot show sort menu when icon first clicked
  .github/workflows/release-helper.yml
  README.md
  package.json
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/interaction/row-col-resize.ts
  packages/s2-core/src/ui/tooltip/components/operator/index.less
  packages/s2-core/src/ui/tooltip/index.tsx
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/manual/table-mode.zh.md
  s2-site/yarn.lock
Labels: pr(fix)

#369 docs(conditions): disable hover highlight
  .github/workflows/compressed-size.yml
  s2-site/docs/common/conditions.en.md
  s2-site/docs/manual/table-mode.zh.md
  s2-site/examples/conditions/advanced/demo/gradient-interval.ts
  s2-site/examples/conditions/advanced/demo/multi-background.ts
  s2-site/examples/conditions/basic/demo/background.ts
  s2-site/examples/conditions/basic/demo/icon.ts
  s2-site/examples/conditions/basic/demo/interval.ts
  s2-site/examples/conditions/basic/demo/table-text.ts
  s2-site/examples/conditions/basic/demo/text.ts
  s2-site/examples/conditions/basic/index.en.md
  s2-site/examples/conditions/basic/index.zh.md
Labels: pr(documentation)

#370 fix(tooltip): tooltip will hide if clicked
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  s2-site/docs/api/general/options.zh.md
Labels: pr(fix)

#365 chore: add the doc of S2Theme
  package.json
  packages/s2-core/__tests__/data/data-sort.json
  packages/s2-core/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-core/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-core/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-core/__tests__/spreadsheet/part-drill-down-spec.tsx
  packages/s2-core/__tests__/spreadsheet/sort-sheet-spec.tsx
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-core/__tests__/spreadsheet/spread-sheet-with-switcher-spec.tsx
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/utils/build-table-hierarchy-spec.tsx
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/components/sheets/tabular-sheet/tabular-theme.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/layout/layout-hooks.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/theme/palette/colorful-blue.ts
  packages/s2-core/src/theme/palette/default.ts
  packages/s2-core/src/theme/palette/simple-blue.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-core/src/utils/theme.ts
  s2-site/docs/api/general/S2DataConfig.en.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/api/general/S2Options.en.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/api/general/dataCfg.en.md
  s2-site/docs/api/general/options.en.md
  s2-site/docs/manual/total.zh.md
  s2-site/package.json
  yarn.lock
Labels: pr(chore)

#358 refactor(pivot-dataset): recode the process of pivot-data-set
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(refactor)

#377 chore(ci): fix cannot trigger action
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: pr(chore)

#379 fix(povit-table): resolve scroll shake issue close #374 #361
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#381 chore: add s2 css in s2-site
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  s2-site/gatsby-browser.js
  s2-site/gatsby-config.js
Labels: pr(chore)

#383 chore(release): v0.1.12
  CHANGELOG.md
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#378 test(facet): finish pivot & table facet test case
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/util.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(test)

#390 chore: optimize totals docs
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/util.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/totals.en.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/total.en.md
  s2-site/docs/manual/basic/total.zh.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/data/basic-totals.json
  s2-site/examples/data/multiple-values-totals.json
  s2-site/examples/total/API.en.md
  s2-site/examples/total/index.en.md
  s2-site/examples/totals/API.en.md
  s2-site/examples/totals/API.zh.md
  s2-site/examples/totals/demo/basic.ts
  s2-site/examples/totals/demo/meta.json
  s2-site/examples/totals/demo/multiple-values.ts
  s2-site/examples/totals/demo/tree.ts
  s2-site/examples/totals/index.en.md
  s2-site/examples/totals/index.zh.md
  s2-site/gatsby-config.js
Labels: pr(chore)

#391 test(interaction): add full event controller test cases
  .github/ISSUE_TEMPLATE/ask-for-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  CHANGELOG.md
  package.json
  packages/s2-core/__tests__/setup.js
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns.spec.ts
  packages/s2-core/jest.config.json
  packages/s2-core/package.json
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/getAllPanelDataCell.ts
Labels: pr(test)

#392 docs: add issues-helper badge
  README.en-US.md
  README.md
Labels: pr(documentation)

#394 fix(pivot-table): fix render apply font crash on ios15
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/components/sheets/tabular-sheet/tabular-theme.ts
  packages/s2-core/src/ui/tooltip/index.less
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(fix)

#386 docs(switcher): add manual and demos for switcher component
  package.json
  packages/s2-core/__tests__/unit/components/switcher/util.spec.ts
  packages/s2-core/rollup.config.js
  packages/s2-core/src/components/icons/index.less
  packages/s2-core/src/components/switcher/content/index.tsx
  packages/s2-core/src/components/switcher/dimension/index.tsx
  packages/s2-core/src/components/switcher/item/index.tsx
  packages/s2-core/src/components/switcher/item/single-item.tsx
  packages/s2-core/src/components/switcher/util.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/manual/basic/analysis/switcher.en.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/examples/analysis/switcher/API.en.md
  s2-site/examples/analysis/switcher/API.zh.md
  s2-site/examples/analysis/switcher/demo/meta.json
  s2-site/examples/analysis/switcher/demo/pivot-with-children.tsx
  s2-site/examples/analysis/switcher/demo/pivot.tsx
  s2-site/examples/analysis/switcher/demo/pure-switcher.tsx
  s2-site/examples/analysis/switcher/demo/table.tsx
  s2-site/examples/analysis/switcher/design.en.md
  s2-site/examples/analysis/switcher/design.zh.md
  s2-site/examples/analysis/switcher/index.en.md
  s2-site/examples/analysis/switcher/index.zh.md
  s2-site/gatsby-config.js
  s2-site/package.json
  s2-site/yarn.lock
  yarn.lock
Labels: pr(documentation)

#395 chore: release 0.1.13
  CHANGELOG.md
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  s2-site/package.json
Labels: pr(chore)

#396 fix(table): table mode corner width err
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#387 feat: copy with row and col
  packages/s2-core/__tests__/unit/utils/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(feature)
