Repository antvis/S2, pull requests merged in 2022-07, with the labels that each got.

#1510 chore: 更新 gitee 账号信息
  .github/workflows/mirror.yml
Labels: pr(chore)

#1512 docs: fix some factual mistakes
  README.en-US.md
  README.md
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/__tests__/data/sort-advanced.ts
  packages/s2-core/__tests__/unit/facet/layout/build-row-tree-hierarchy-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-react/README.md
  packages/s2-react/__tests__/data/data-sort.json
  packages/s2-react/__tests__/data/tableau-supermarket.csv
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/examples/analysis/sort/demo/custom-list.ts
  s2-site/examples/analysis/sort/demo/table-sort.tsx
  s2-site/examples/data/basic-table-mode.json
  s2-site/examples/data/basic-totals.json
  s2-site/examples/data/basic.json
  s2-site/examples/data/multiple-values-totals.json
Labels: pr(documentation)

#1517 docs: 更新线上json文件中行政区域
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/examples/analysis/sort/demo/custom-totals.ts
  s2-site/examples/analysis/sort/demo/group-sort.tsx
  s2-site/examples/analysis/totals/demo/basic.ts
  s2-site/examples/analysis/totals/demo/multiple-values.ts
  s2-site/examples/analysis/totals/demo/tree.ts
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
  s2-site/examples/react-component/switcher/demo/pivot-header.tsx
  s2-site/examples/react-component/switcher/demo/pivot-with-children.tsx
  s2-site/examples/react-component/switcher/demo/pivot.tsx
  s2-site/examples/theme/custom/demo/custom-palette.ts
  s2-site/examples/theme/custom/demo/custom-schema.ts
  s2-site/examples/theme/default/demo/colorful.ts
  s2-site/examples/theme/default/demo/default.ts
  s2-site/examples/theme/default/demo/gray.ts
Labels: pr(documentation)

#1519 refactor(strategysheet): 取消内置的子弹图 Tooltip
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/kpi-columns/custom-bullet-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/utils/index.ts
Labels: pr(refactor)

#1515 fix: 列头文字&icon无法正确对齐
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/canvas.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#1526 refactor: 重构趋势分析表条件格式解析逻辑
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/examples/react-component/sheet/demo/strategy.tsx
Labels: pr(refactor)

#1523 fix(strategysheet): 修复趋势分析表无法自定义 Tooltip
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix)

#1531 fix: 修复大量数据下，行列总计单元格计算时耗时和内存问题
  packages/s2-core/src/utils/data-set-operate.ts
Labels: pr(fix), 🚨 test failed

#1530 docs: 添加 vue 版的下钻组件
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/manual/basic/analysis/vue.zh.md
Labels: pr(documentation)

#1540 feat(strategysheet): 趋势分析表 Tooltip 增加 label 属性用于自定义标题
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
  packages/s2-react/src/components/index.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(feature)

#1535 fix(drill-down): values 配置为空时未显示下钻 icon
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-shared/src/utils/drill-down.ts
Labels: pr(fix)

#1537 fix: 趋势分析表 conditions 增加容错能力
  packages/s2-core/src/utils/text.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
Labels: pr(fix), 🚨 test failed

#1534 fix: 优化 mini 图坐标计算逻辑
  packages/s2-core/__tests__/unit/utils/g-mini-charts-spec.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-react/__tests__/data/strategy-data.ts
Labels: pr(fix)

#1543 fix(theme): 修复调整序号列后色板丢失 close #1538
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(fix)

#1546 feat(tooltip): 支持设置多个class类名
  .github/workflows/sync-site-lock-changelog-with-pr.yml
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-react/__tests__/util/helpers.ts
Labels: pr(feature)

#1549 fix: 修复移动端滚动没有prevent问题
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), 🚨 test failed

#1548 chore: 手动同步 S2 Lock 和 Changelog
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#1552 feat(strategysheet): 趋势分析表允许对行头和列头的 tooltip 做自定义
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/utils/index.ts
  s2-site/docs/manual/basic/analysis/strategy.zh.md
Labels: pr(feature)

#1550 fix: 维度按指标汇总值排序时结果错误
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/utils/sort-action.ts
Labels: pr(fix)

#1553 fix: 修复趋势分析表导出问题
  .eslintrc.js
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
Labels: pr(fix)

#1555 fix: 去除 vue prop warning 信息
  packages/s2-vue/src/hooks/useEvents.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  packages/s2-vue/src/utils/traverse.ts
Labels: pr(fix)

#1557 fix: 下钻个数为-1时应展示全部下钻数据
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-shared/src/utils/drill-down.ts
Labels: pr(fix)

#1556 fix(strategysheet): 修复趋势分析表错误的标题
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix)

#1559 fix(s2-vue): 修复表头排序交互不起作用的问题
  packages/s2-vue/src/components/tooltip/components/operator/index.vue
  packages/s2-vue/src/components/tooltip/components/operator/menu.vue
Labels: pr(fix)

#1562 fix: 修复明细表最左侧边框绘制问题
  packages/s2-core/__tests__/bugs/issue-1539-spec.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/group/grid-group.ts
Labels: pr(fix)

#1558 feat: 增加允许/禁用指标在行列维度中相互切换的能力
  packages/s2-react/__tests__/unit/components/switcher/util-spec.ts
  packages/s2-react/src/components/switcher/constant.ts
  packages/s2-react/src/components/switcher/content/index.tsx
  packages/s2-react/src/components/switcher/dimension/index.tsx
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/components/switcher/index.tsx
  packages/s2-react/src/components/switcher/util.ts
  packages/s2-vue/src/interface.ts
  s2-site/docs/api/components/switcher.zh.md
  s2-site/examples/react-component/switcher/demo/pivot-with-children.tsx
Labels: pr(feature)

#1569 fix: 修复合并单元格被grid边框覆盖的问题
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
Labels: pr(fix)

#1574 fix: 修复合并单元格临界情况被错误移除的问题
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
Labels: pr(fix)

#1573 docs: 增加 mini 图 demo
  s2-site/examples/react-component/sheet/demo/meta.json
  s2-site/examples/react-component/sheet/demo/strategy-mini-chart.tsx
Labels: pr(documentation)

#1566 fix: 修复 line 包围盒问题
  packages/s2-core/__tests__/bugs/issue-1539-spec.ts
  packages/s2-core/__tests__/bugs/issue-1561-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/group/grid-group.ts
Labels: pr(fix)

#1576 fix: s2-vue 保持和react组件一致的tooltip summary渲染逻辑
  packages/s2-vue/src/components/tooltip/components/summary.vue
Labels: pr(fix)

#1563 fix(strategysheet): 修复子弹图进度小于 1% 时显示错误的问题
  .github/workflows/lint.yml
  .github/workflows/test.yml
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/playground/config.ts
Labels: pr(fix)

#1581 fix: 修复初始化时, border不见的问题
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/group/grid-group.ts
  packages/s2-core/src/group/panel-scroll-group.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
Labels: pr(fix)

#1584 fix(strategysheet): 修复单元格宽度拖拽变小后子弹图宽度计算错误
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
Labels: pr(fix)

#1588 fix(strategysheet): 修复子弹图颜色显示错误 & 百分比精度问题
  packages/s2-core/__tests__/unit/utils/g-mini-charts-spec.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
Labels: pr(fix)

#1591 feat(layout): 支持自定义行/列单元格宽度 close #1585
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/examples/layout/custom/demo/custom-row-col-cell-width.ts
  s2-site/examples/layout/custom/demo/meta.json
Labels: pr(feature)

#1590 feat: 当前只能复制数值可带表头复制
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/utils/export/copy.ts
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/basic/analysis/export.zh.md
Labels: pr(feature)

#1599 fix(layout): 修复 Firefox 浏览器部分 icon 渲染失败 close #1571
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
Labels: pr(fix)

#1594 fix: 有冻结行且有垂直 scrollWidth 时冻结行无法 resize
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/src/cell/table-col-cell.ts
Labels: pr(fix), 🙏 need test cases or docs

#1601 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1606 fix: sortByFunc 排序后行列维度节点丢失
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/utils/sort-action.ts
Labels: pr(fix)

#1607 fix(interaction): 向左移动到不完全可见cell的时候，没有滚动过去
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
Labels: pr(fix)

#1610 fix: 明细表复制时无需使用formatter格式化列头label
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#1611 feat: 支持resize最右侧column
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(feature)

#1618 docs: 将 S2Event 提取到 API 文档中, 方便查看
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/api/general/S2Event.en.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/api/graphic.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(documentation)

#1616 fix(strategysheet): 修复趋势分析表列头格式化不生效
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(fix)
