Repository antvis/S2, pull requests merged in 2022-12, with the labels that each got.

#1947 feat: 明细表模式的"字段标记"，mapping 中第二个参数，返回整行信息
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/data-cell.ts
  s2-site/docs/manual/basic/conditions.zh.md
Labels: pr(feature)

#1964 docs: 替换过期二维码 & CNAME
  s2-site/docs/common/contact-us.en.md
  s2-site/docs/common/contact-us.zh.md
  s2-site/docs/manual/faq.en.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/introduction.en.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/package.json
Labels: pr(documentation)

#1948 feat(scroll): 增加滚动条最小尺寸配置 close #1892
  package.json
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/common/constant/index.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/scroll.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  packages/s2-core/src/ui/scrollbar/interface.ts
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  scripts/validate-deps.js
Labels: pr(feature)

#1951 docs: 新增自定义指标顺序示例 & 优化文档
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/issue-labeled.yml
  .github/workflows/pr-labeled.yml
  packages/s2-shared/package.json
  s2-site/docs/api/general/S2DataConfig.en.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/development.en.md
  s2-site/docs/common/development.zh.md
  s2-site/docs/common/mini-chart.zh.md
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/custom/cell-align.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/docs/manual/faq.en.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.en.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
  s2-site/examples/custom/custom-layout/demo/custom-value-order.ts
  s2-site/examples/custom/custom-layout/demo/meta.json
Labels: pr(documentation)

#1957 feat(header): 去除 antd PageHeader 组件依赖 & Header 组件重构 close #1981
  packages/s2-core/__tests__/util/index.ts
  packages/s2-react/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-react/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-react/__tests__/spreadsheet/pressure-test-spec.tsx
  packages/s2-react/__tests__/unit/components/advanced-sort/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/advanced-sort/index-spec.tsx
  packages/s2-react/__tests__/unit/components/drill-down/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/drill-down/index-spec.tsx
  packages/s2-react/__tests__/unit/components/export/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/export/index-spec.tsx
  packages/s2-react/__tests__/unit/components/header/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/header/index-spec.tsx
  packages/s2-react/__tests__/unit/components/pagination/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/pagination/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/switcher/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/switcher/index-spec.tsx
  packages/s2-react/__tests__/unit/components/tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
  packages/s2-react/src/components/advanced-sort/index.less
  packages/s2-react/src/components/export/index.tsx
  packages/s2-react/src/components/header/index.less
  packages/s2-react/src/components/header/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-shared/src/icons/col-icon.svg
  packages/s2-shared/src/icons/dot-icon.svg
  packages/s2-shared/src/icons/row-icon.svg
  packages/s2-shared/src/icons/sort-icon.svg
  packages/s2-shared/src/icons/switcher-icon.svg
  packages/s2-shared/src/icons/value-icon.svg
  s2-site/docs/api/components/advanced-sort.en.md
  s2-site/docs/api/components/advanced-sort.zh.md
  s2-site/docs/api/components/drill-down.en.md
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/api/components/export.en.md
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/api/components/header.en.md
  s2-site/docs/api/components/header.zh.md
  s2-site/docs/api/components/switcher.en.md
  s2-site/docs/common/header.zh.md
  s2-site/examples/react-component/header/demo/default.tsx
Labels: pr(feature)

#1961 fix(interaction): 修复趋势分析表选中高亮效果无效 close #1960
  packages/s2-core/__tests__/spreadsheet/interaction-spotlight-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-cell.ts
  s2-site/docs/api/basic-class/base-cell.en.md
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/common/mini-chart.zh.md
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/basic/analysis/strategy.en.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/docs/manual/basic/tooltip.en.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/case/kpi-strategy/demo/covid-trend.tsx
  s2-site/examples/react-component/sheet/demo/strategy-mini-chart.tsx
  s2-site/examples/react-component/sheet/demo/strategy.tsx
Labels: pr(fix)

#1966 refactor: 重构 series-number 逻辑，抽离出 series-number-cell，保持渲染逻辑一致
  packages/s2-core/__tests__/spreadsheet/spread-sheet-series-number-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/data-cell-spec.ts
  packages/s2-core/src/cell/index.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/hooks.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/interface.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/header/util.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/api/basic-class/base-facet.en.md
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/general/S2Options.en.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/examples/custom/custom-cell/demo/meta.json
  s2-site/examples/custom/custom-cell/demo/series-number-cell.ts
Labels: pr(refactor)

#1971 chore: 添加 latest 分支生成 release commit 脚本
  package.json
  scripts/latest-bump-version.js
  scripts/util.js
  scripts/validate-deps.js
Labels: pr(chore)

#1969 fix(tooltip): 修复自定义操作菜单传入自定义 ReactNode 不显示
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/src/common/react-element.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  packages/s2-react/src/components/tooltip/components/icon.tsx
  packages/s2-react/src/components/tooltip/components/operator.tsx
  packages/s2-react/src/components/tooltip/components/summary.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-react/src/components/tooltip/interface.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/components/tooltip/components/summary.vue
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(fix)

#1972 chore: 官网部署修复
  s2-site/package.json
Labels: pr(chore)

#1976 docs: 修复错误 API 文档格式
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/conditions.zh.md
  s2-site/docs/common/mini-chart.zh.md
  s2-site/docs/common/sort-param.zh.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(documentation)

#1984 fix: 修复 enableCopy 和 hideMeasureColumn 都开启为 true 时，复制报错问题
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1986 feat: 实现树状模式下可复制
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(feature)

#1983 feat: 适配链接跳转的判断方式
  packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(feature)

#1992 feat: 增加 linkFields 参数传入类型
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/utils/interaction/index.ts
  packages/s2-core/src/utils/interaction/link-field.ts
  s2-site/docs/common/interaction.zh.md
Labels: pr(feature)

#1988 fix: 解决S2.0next版本Vue报错bug
  packages/s2-vue/src/hooks/useResize.ts
Labels: pr(fix)

#2003 fix: 暂时修复g版本冲突问题
  packages/s2-core/package.json
  yarn.lock
Labels: pr(fix), 🚨 lint failed

#2001 docs: 官网自定义目录树链接跳转 demo
  s2-site/examples/interaction/advanced/demo/custom-tree-link-jump.ts
  s2-site/examples/interaction/advanced/demo/meta.json
Labels: pr(documentation)

#1996 chore: 更新 vue-tsc 版本，保持和 volar 一致
  packages/s2-vue/package.json
  packages/s2-vue/src/hooks/useResize.ts
  yarn.lock
Labels: pr(chore)

#1997 fix: gui icon 加载完成后，增加检测步骤，避免无意义的渲染 warning
  packages/s2-core/src/common/icons/gui-icon.ts
Labels: pr(fix)

#1998 docs: 更新列分组demo配图
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/basic/table/demo/table-column-group.ts
Labels: pr(documentation)

#2000 docs: 修复自定义 schema 示例demo
  s2-site/examples/theme/custom/demo/custom-schema.ts
Labels: pr(documentation)

#2002 feat: 添加字段标记中，定制柱状图的长度的功能 （filedValue）
  packages/s2-core/__tests__/unit/utils/__snapshots__/g-mini-charts-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/g-mini-charts-spec.ts
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/examples/analysis/conditions/demo/interval.ts
Labels: pr(feature)

#2006 fix: 明细表紧凑模式宽度计算错误
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#1981 feat: 单元格宽高配置增强 close #1895
  packages/s2-core/__tests__/bugs/issue-1668-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-cell-style-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-cell-style-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/resize-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/facet.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-core/src/utils/interaction/resize.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-react/__tests__/spreadsheet/pressure-test-spec.tsx
  packages/s2-react/playground/components/ResizeConfig.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-shared/__tests__/utils/options-spec.ts
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/examples/layout/custom/demo/custom-pivot-size.ts
  s2-site/examples/layout/custom/demo/custom-row-col-cell-width.ts
  s2-site/examples/layout/custom/demo/custom-table-size.ts
Labels: pr(feature), next

#2005 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2007 fix: 明细表linkField失效
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/src/utils/interaction/link-field.ts
Labels: pr(fix)

#2008 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2011 chore: 添加移动端demo
  packages/s2-core/src/common/constant/events/origin.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/components/Mobile.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
Labels: pr(chore)

#2010 feat: 子弹图为空时使用placeholder占位
  packages/s2-core/src/utils/g-mini-charts.ts
Labels: pr(feature), 🙏 need test cases or docs

#1990 fix: 列头label存在数组，复制导出列头层级补齐错误
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
Labels: pr(fix), 🙏 need test cases or docs

#2009 refactor: 简化 facet 构造参数
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/facet/header/corner-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/__tests__/util/index.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/facet.ts
  packages/s2-core/src/common/interface/frame.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/header/interface.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/build-header-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/layout/interface.ts
  packages/s2-core/src/facet/layout/layout-hooks.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-core/src/utils/layout/frozen.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/components/Mobile.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/chart-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-shared/src/utils/options.ts
  s2-site/examples/case/comparison/demo/time-spend.tsx
  s2-site/examples/custom/custom-layout/demo/custom-coordinate.ts
Labels: pr(refactor)

#1878 feat: selected cell highlight
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/interaction.zh.md
Labels: pr(feature)

#2022 fix: bullet占位符绘制错误
  packages/s2-core/src/utils/g-mini-charts.ts
Labels: pr(fix)
