Repository antvis/S2, pull requests merged in 2022-02, with the labels that each got.

#1045 feat: copy with grid pivot sheet
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(feature)

#1056 docs: 修复部分错误文档和示例配置
  packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/examples/analysis/totals/demo/basic.ts
  s2-site/examples/analysis/totals/demo/multiple-values.ts
  s2-site/examples/analysis/totals/demo/tree.ts
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/react-component/export/demo/export.tsx
  s2-site/examples/react-component/header/demo/default.tsx
Labels: pr(documentation)

#1058 feat(tooltip): 支持自定义 tooltip 操作项
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/src/common/constant/options.ts
  packages/s2-react/src/common/icons/html-icon.less
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/tooltip/components/operator/index.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/react-component/tooltip/demo/custom-operation.tsx
  s2-site/examples/react-component/tooltip/demo/custom-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/meta.json
Labels: pr(feature), 🚨 test failed

#1059 fix(tooltip): 修复不同类型的单元格配置合并问题
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/utils/tooltip.ts
Labels: pr(fix), 🚨 test failed

#1060 fix: 只在移动端绑定tap事件，防止多次触发 collapse 事件
  packages/s2-core/package.json
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/utils/g-renders.ts
Labels: pr(fix)

#1062 feat: 数据导出适配自定义目录树
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
Labels: pr(feature), 🚨 test failed

#1061 fix(scroll): refactor mobile scrolling
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#1063 fix(interaction): 修复刷选不显示预选框, 行列多选功能异常等交互问题
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/state-controller.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1067 feat(tooltip): tooltip 操作项支持动态显示
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/react-component/tooltip/demo/custom-operation.tsx
Labels: pr(feature), 🚨 test failed

#1069 refactor: 删除无用配置项customHeaderCells及相关逻辑
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/layout/generate-id.ts
  packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  s2-site/examples/custom/custom-layout/demo/custom-layout-hierarchy.ts
Labels: pr(refactor)

#1070 feat: 单元格内多指标支持分列导出
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/__tests__/data/strategy-data.ts
Labels: pr(feature), 🚨 test failed

#1073 feat(interaction): interaction增加点击行列头方法供外部调用
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/root.ts
  s2-site/docs/api/basic-class/interaction.zh.md
Labels: pr(feature), 🚨 test failed

#1074 fix: 修复子节点收起后角头全部展开收起不生效 close #1072
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1076 refactor: 删除无用代码及参数
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/events.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/hooks/useEvents.ts
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(refactor), 🚨 test failed

#1066 fix: 当不同父节点下存在相同子节点时高级排序出错 close #1065
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/utils/sort-action.ts
  packages/s2-react/src/components/advanced-sort/index.tsx
Labels: pr(fix)

#1075 feat(pivot): 新增组内排序时触发回调事件
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/utils/drill-down.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(feature), 🚨 test failed

#1077 test: 修复单测
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-react/__tests__/spreadsheet/adaptive.tsx
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
Labels: pr(test)

#1086 feat: 全量展示小计项
  packages/s2-core/src/utils/layout/add-totals.ts
Labels: pr(feature)

#1085 feat: Meta内formatter增加入参提供完整数据 close #994
  packages/s2-core/__tests__/unit/cell/data-cell.spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(feature)

#1090 fix: 初始化后更新dataCfg不触发分页total变化
  packages/s2-react/src/hooks/usePagination.ts
Labels: pr(fix)

#1091 fix: s2-react 事件在 react hooks 使用中事件改变后未及时更新
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(fix)

#1092 feat: s2-react 全量透出事件回调函数
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/hooks/useEvents.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
Labels: pr(feature)

#1095 refactor: 精简 usePagination hooks deps
  packages/s2-react/__tests__/unit/hooks/usePagination-spec.ts
  packages/s2-react/src/components/pagination/index.tsx
  packages/s2-react/src/hooks/usePagination.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(refactor)

#1096 fix(header): header props types
  packages/s2-react/src/components/header/index.tsx
Labels: pr(fix)

#1097 fix: 回退排序筛选事件变量名
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/hooks/useEvents.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/examples/case/data-preview/demo/index.tsx
Labels: pr(fix)

#1098 docs: 完善表组件文档,添加事件回调接口说明
  packages/s2-react/src/components/sheets/interface.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(documentation)

#1099 fix: 明细表增加排序事件回调 close#1087
  packages/s2-core/src/sheet-type/table-sheet.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(fix)

#1081 feat(interaction): 透视表支持隐藏列头
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/cell/table-col-cell.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/hooks/usePaginationEffect.ts
  packages/s2-react/src/hooks/usePrevious.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/pivot-hide-columns.ts
  s2-site/examples/interaction/advanced/demo/table-hide-columns.ts
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
Labels: pr(feature)

#1104 fix: 修复行头为空无默认角头指标文字问题
  packages/s2-core/__tests__/unit/cell/custom-tree-corner-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/i18n/en_US.ts
  packages/s2-core/src/common/i18n/zh_CN.ts
  packages/s2-react/playground/config.ts
Labels: pr(fix)

#1107 feat(tooltip): tooltip 自定义操作项点击事件透出 cell 信息 close #1106
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-react/src/components/tooltip/components/operator/index.tsx
  packages/s2-react/src/components/tooltip/custom-tooltip.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-react/src/components/tooltip/interface.ts
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/react-component/tooltip/demo/custom-operation.tsx
Labels: pr(feature)

#1111 fix: 不添加总计时错误地添加了小计节点
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/src/utils/layout/add-totals.ts
Labels: pr(fix)

#1117 docs: 新增获取单元格数据文档
  s2-site/docs/manual/advanced/get-cell-data.en.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/docs/manual/advanced/performance.zh.md
  s2-site/docs/manual/basic/analysis/export.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/examples/case/performance-compare/demo/meta.json
Labels: pr(documentation)

#1120 fix: 修复头部cell错误使用meta中formatter的问题，close #1014
  packages/s2-core/__tests__/bugs/issue-1014-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#1123 fix: 明细表锁行/列时分割线阴影显隐逻辑
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#1128 fix: 梳理单元格对齐方式, close #1084
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/theme/index.ts
  s2-site/docs/manual/advanced/custom/category-tree.en.md
  s2-site/docs/manual/advanced/custom/cell-align.en.md
  s2-site/docs/manual/advanced/custom/cell-align.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.en.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/advanced/custom/hook.en.md
Labels: pr(fix)

#1130 feat: :sparkles: 支持覆盖默认icon
  packages/s2-core/src/sheet-type/spread-sheet.ts
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
Labels: pr(feature)

#1131 fix: corner 事件监听失效
  packages/s2-core/src/cell/corner-cell.ts
Labels: pr(fix)

#1132 fix: 修复对全局鼠标按下事件的污染
  packages/s2-core/src/interaction/brush-selection.ts
Labels: pr(fix)

#1134 fix(interaction): 修复开启复制后, 无法复制表格外的文字
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-react/playground/index.tsx
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/case/data-preview/index.zh.md
Labels: pr(fix)

#1118 docs: 新增如何提问 faq
  .github/workflows/pr-auto-assign-reviewer.yml
  README.en-US.md
  README.md
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/__tests__/bugs/issue-292-spec.ts
  packages/s2-core/__tests__/bugs/issue-368-spec.ts
  packages/s2-core/__tests__/bugs/issue-372-spec.ts
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/bugs/issue-511-spec.ts
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/bugs/issue-720-spec.ts
  packages/s2-core/__tests__/bugs/issue-836-spec.ts
  packages/s2-core/__tests__/bugs/issue-840-spec.ts
  packages/s2-core/__tests__/bugs/issue-860-spec.ts
  packages/s2-core/__tests__/bugs/issue-868-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-react/README.md
  s2-site/docs/manual/advanced/custom/category-tree.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/docs/manual/basic/analysis/export.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/basic.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/interaction/advanced/demo/scroll-speed-ratio.ts
Labels: pr(documentation)

#1135 feat: :sparkles: 允许用户自定义行头单元格宽度
  packages/s2-core/__tests__/unit/facet/layout/row-node-width-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(feature)

#1136 feat: 维度切换组件增加allowEmpty配置 close #533
  packages/s2-react/src/components/switcher/dimension/index.tsx
  packages/s2-react/src/components/switcher/interface.ts
  packages/s2-react/src/components/switcher/item/index.less
  packages/s2-react/src/components/switcher/item/index.tsx
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/examples/react-component/switcher/demo/pure-switcher.tsx
Labels: pr(feature)

#1133 feat: adaptive 的 container 自适应包含 header 和 page
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
  packages/s2-react/src/components/sheets/base-sheet/index.less
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/hooks/useResize.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/hd-adapter.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(feature)

#1139 feat(tooltip): 支持自定义挂载节点
  packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
  packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(feature)

#1141 chore(release): @antv/s2@1.10.0 @antv/s2-react@1.10.0
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1143 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-react/CHANGELOG.md
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)
