Repository antvis/S2, pull requests merged in 2022-04, with the labels that each got.

#1223 feat: 支持自定义角头的虚拟数值字段文本 close #1212
  .gitignore
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(feature)

#1234 fix(copy): 修复因为header的key内带有‘-’字符串导致的row和col id识别错误
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1231 docs: 优化自定义目录和交互文档细节
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/manual/advanced/custom/category-tree.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/examples/custom/custom-cell/demo/col-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
  s2-site/examples/custom/custom-tree/demo/meta.json
  s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx
Labels: pr(documentation)

#1239 chore: 修复刷选测试用例稳定性问题
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
Labels: pr(chore)

#1238 chore: 新增相似issue提示action, 完善action模板
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-remove-inactive.yml
  .github/workflows/issues-similarity-analysis.yml
  .github/workflows/pr-labeled.yml
Labels: pr(chore)

#1244 fix: 修复 backgroundColorOpacity 不生效问题，close #1201
  packages/s2-core/__tests__/bugs/issue-1201-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/header/corner.ts
Labels: pr(fix)

#1245 fix: 修复官网在Safari环境下打不开的问题
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(fix)

#1246 fix: 更改remapping字段顺序
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
Labels: pr(fix)

#1247 chore(release): @antv/s2@1.14.0 @antv/s2-react@1.13.0
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1249 fix(s2): 如果是 table mode，列头不需要被格式化
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/src/cell/header-cell.ts
Labels: pr(fix)

#1250 fix(row-column-resize): 修复虚线宽度设置不生效问题
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/interaction/row-column-resize.ts
Labels: pr(fix)

#1251 chore(ci): 修复自动发布后不能自动更新版本号的问题
  .releaserc.base.js
Labels: pr(chore)

#1254 fix: headerActionIcons更新不应清除上一次下钻数据
  packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
Labels: pr(fix)

#1258 fix: 修复官网搜索功能
  s2-site/gatsby-config.js
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(fix)

#1253 feat(copy): 添加复制全部 复制行 复制列功能
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/constant/copy.ts
  packages/s2-core/src/common/constant/index.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(feature)

#1259 chore: 增加自动添加 issue&PR 到 project 的 action
  .github/workflows/auto-add-to-project.yml
  packages/s2-react/playground/resize.tsx
Labels: pr(chore)

#1256 feat(interaction): 支持行列头反选
  packages/s2-core/__tests__/spreadsheet/interaction-tooltip-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/root.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#1260 fix: 修复交叉表分页问题
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/src/utils/facet.ts
  packages/s2-react/src/hooks/usePagination.ts
Labels: pr(fix)

#1263 fix: 修复auto add to project action 语法错误
  .github/workflows/auto-add-to-project.yml
Labels: pr(fix)

#1262 feat(interaction): 支持透传 addEventListener 的可选参数
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#1267 fix: 添加当多个数值在行头显示时，小计展示被遮挡的问题
  packages/s2-core/__tests__/bugs/issue-368-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#1269 chore: 修复github event_name 判断问题
  .github/workflows/auto-add-to-project.yml
Labels: pr(chore)

#1257 fix: 解决明细表表头被格式化的问题
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/utils/cell/header-cell.ts
Labels: pr(fix)

#1261 fix(theme): 修复颜色主题配置对自定义 icon 不生效的问题
  packages/s2-core/__tests__/spreadsheet/icons-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/basic/theme.zh.md
Labels: pr(fix)

#1190 feat: 增加根据主题色生成对应主题风格色板功能
  packages/s2-core/__tests__/unit/utils/color-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/theme/palette/colorful.ts
  packages/s2-core/src/theme/palette/default.ts
  packages/s2-core/src/theme/palette/gray.ts
  packages/s2-core/src/utils/color.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/theme.ts
  packages/s2-react/package.json
  packages/s2-react/playground/index.tsx
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/examples/theme/custom/demo/custom-generate-palette.tsx
  s2-site/examples/theme/custom/demo/custom-manual-palette.tsx
  s2-site/examples/theme/custom/demo/meta.json
  s2-site/gatsby-browser.js
  s2-site/package.json
  s2-site/yarn.lock
  yarn.lock
Labels: pr(feature)

#1217 feat(switcher): add disabled property
  packages/s2-react/src/components/header/index.less
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/components/switcher/index.tsx
  s2-site/docs/api/components/switcher.zh.md
Labels: pr(feature), 🙏 need test cases or docs

#1270 fix: 修复switcher组件布局问题
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-react/__tests__/unit/components/switcher/headerUtil-spec.ts
  packages/s2-react/__tests__/unit/components/switcher/util-spec.ts
  packages/s2-react/src/components/switcher/constant.ts
  packages/s2-react/src/components/switcher/content/index.less
  packages/s2-react/src/components/switcher/content/index.tsx
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/components/switcher/headerUtil.ts
  packages/s2-react/src/components/switcher/util.ts
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/examples/react-component/switcher/demo/table.tsx
Labels: pr(fix)

#1271 feat: 去除自定义树无用的 transformCustomTreeItems 方法
  packages/s2-core/__tests__/unit/cell/custom-tree-corner-cell-spec.ts
  packages/s2-core/__tests__/unit/data-set/custom-tree-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/transform-custom-tree-spec.ts
  packages/s2-core/src/utils/layout/index.ts
  packages/s2-core/src/utils/layout/transform-custom-tree-items.ts
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/custom/custom-tree/demo/custom-tree.ts
Labels: pr(feature)

#1272 chore: 增加文档单词大小写检测
  CONTRIBUTING.en-US.md
  CONTRIBUTING.md
  package.json
  s2-site/docs/api/graphic.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/contribution.zh.md
  yarn.lock
Labels: pr(chore)

#1273 chore: 更新 project action 需要 token
  .github/workflows/auto-add-to-project.yml
Labels: pr(chore)

#1275 fix(interaction): 修复全选后无法清除选中状态
  packages/s2-core/src/interaction/root.ts
Labels: pr(fix)

#1276 fix: 行头/单元格icon颜色应默认与字体色一致
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#1274 fix(facet): 修复 scrollY 越界问题
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/utils/facet.ts
Labels: pr(fix)

#1284 chore: 修复自动添加到project action 触发类型
  .github/workflows/auto-add-to-project.yml
Labels: pr(chore)

#1285 fix: 树状结构第一个子层级无法排序的问题
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
Labels: pr(fix)

#1279 docs: 修复官网demo分群下钻表颜色丢失问题
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
Labels: pr(documentation)

#1281 feat: 新增 hoverFocusTime 配置项
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#1278 docs: 新增趋势分析表相关文档demo
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/manual/basic/analysis/strategy.en.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/examples/react-component/sheet/demo/meta.json
  s2-site/examples/react-component/sheet/demo/strategy.tsx
Labels: pr(documentation)

#1286 chore: alpha 合并到 master
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/bugs/issue-368-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/theme/palette/colorful.ts
  packages/s2-core/src/theme/palette/default.ts
  packages/s2-core/src/theme/palette/gray.ts
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(chore)

#1288 docs: 完善主题章节
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#1287 fix(corner-cell): 微调角头icon位置保持和行头对齐
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#1291 chore: 🤖 更新 version 以及 lock 文件
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1299 fix(strategySheet): 隐藏列兼容趋势分析表衍生指标场景
  package.json
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(fix)

#1300 chore: 合并 latest 分支代码
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#1301 chore: 修复 yarn workspace 把本地的 s2-core 隐射到 esm 目录的问题
  package.json
  packages/s2-react/package.json
  packages/s2-react/vite.config.ts
  packages/s2-vue/package.json
  packages/s2-vue/vite.config.ts
  yarn.lock
Labels: pr(chore)

#1293 fix: 修正auto reset 的 canvas 外判断逻辑
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#1302 feat: 树状层级样式优化
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/utils/g-renders.ts
  s2-site/docs/common/style.zh.md
Labels: pr(feature)

#1292 fix(interaction): 连续 Hover 失效问题修复
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/utils/interaction/state-controller.ts
Labels: pr(fix)

#1295 fix(interaction): 设置 stateShape 的 visible 默认为 false 来减少绘制调用
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/utils/g-renders.ts
Labels: pr(fix)
