Repository antvis/S2, pull requests merged in 2022-05, with the labels that each got.

#1307 fix(interaction): 树状模式列头非叶子节点选中无法高亮当前列
  packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/root.ts
Labels: pr(fix)

#1309 feat: 允许条件设置数据单元格为空的占位符
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(feature)

#1310 refactor: 树状层级结构构造取消分割符分割节点
  package.json
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(refactor)

#1311 fix: 修复容器设置transform样式后框选背景框错位问题
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/src/interaction/brush-selection.ts
Labels: pr(fix)

#1312 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
  yarn.lock
Labels: pr(chore)

#1319 fix: 在复制或者表格数据时，可对行列头进行格式化导出
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/index.ts
  s2-site/docs/common/export.zh.md
  s2-site/docs/manual/advanced/adaptive.zh.md
Labels: pr(fix)

#1321 fix(copy): 修复同步复制时会触发页面滚动的问题 close #1317
  packages/s2-core/__tests__/unit/utils/export/index-spec.ts
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#1318 docs: 增加如何在 Vue 中自定义 Tooltip 的文档
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/examples/react-component/tooltip/demo/custom-tooltip.tsx
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#1323 chore: 延时同步 s2 lock
  .github/workflows/prerelease-notify.yml
  .github/workflows/release-notify.yml
  .github/workflows/sync-site-lock-changelog-with-pr.yml
Labels: pr(chore)

#1322 fix(interaction): 角头单元格增加对自定义tooltip的适配
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/index.ts
  packages/s2-core/src/interaction/base-interaction/click/merged-cell-click.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/base-tooltip.zh.md
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(fix)

#1327 docs: 更新 Vue3 自定义 Tooltip 文档
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(documentation)

#1325 feat: 当子维度不足2个时可隐藏小计节点
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.zh.md
Labels: pr(feature)

#1332 fix: 带总/小计的交叉表复制报错
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1333 docs: 更新导航[使用文档/API文档]下的文字链接跳转问题
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/components/advanced-sort.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/common/custom/layoutArrange.zh.md
  s2-site/docs/common/custom/layoutCoordinate.zh.md
  s2-site/docs/common/custom/layoutDataPosition.zh.md
  s2-site/docs/common/custom/layoutHierarchy.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/common/view-meta.zh.md
  s2-site/docs/manual/advanced/get-instance.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(documentation)

#1338 fix: 仅配置列头总计时却渲染了行/列头所有总计
  packages/s2-core/__tests__/bugs/issue-1337-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(fix)

#1334 feat(interaction): 增加单元格的右键事件 close #1326
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/event-controller.ts
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#1339 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1340 chore(ci): 增加 sync changelog 成功&失败的通知
  .github/workflows/auto-release.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/compressed-size.yml
  .github/workflows/lint.yml
  .github/workflows/preview-build.yml
  .github/workflows/sync-notify.yml
  .github/workflows/sync-site-lock-changelog-with-pr.yml
  .github/workflows/test.yml
Labels: pr(chore)

#1341 chore: 增加 pengding 标签 action
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#1331 fix: 不应以mutable的方式修改headerActionIcons
  packages/s2-react/__tests__/unit/hooks/usePivotSheetUpdate-spec.ts
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/hooks/index.ts
  packages/s2-react/src/hooks/usePivotSheetUpdate.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-react/src/utils/drill-down.ts
Labels: pr(fix)

#1343 chore(ci): 修复 action 格式错误
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#1297 fix(facet): DataCell 边框改为统一绘制的 Grid
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/grid-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/frozen.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/group/frozen-group.ts
  packages/s2-core/src/group/grid-group.ts
  packages/s2-core/src/group/panel-scroll-group.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/grid.ts
  packages/s2-core/src/utils/interaction/scroll.ts
Labels: pr(fix)

#1350 feat: 支持回调函数调整 Tooltip 位置
  packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/common/tooltip.zh.md
Labels: pr(feature)

#1351 fix(interaction): 修复默认隐藏列的配置更新为空数组时, 未触发表格更新
  .github/ISSUE_TEMPLATE/ask-for-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/hooks/useSpreadSheet.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
Labels: pr(fix)

#1353 fix: 下钻数据没有按照用户数据展示
  packages/s2-core/__tests__/unit/facet/layout/build-row-tree-hierarchy-spec.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-react/__tests__/data/mock-drill-down-dataset.json
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/examples/custom/custom-cell/demo/col-cell.ts
  s2-site/examples/custom/custom-cell/demo/row-cell.ts
Labels: pr(fix)

#1352 feat: 丰富tooltip关闭的验证逻辑
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.tsx
Labels: pr(feature), 🙏 need test cases or docs

#1364 feat(theme): 新增度量值的主题配置, 修复小计总计主题配置不生效 close #1357
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(feature)

#1366 docs: 增加自定义小计/总计单元格的例子
  s2-site/examples/custom/custom-cell/demo/col-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/meta.json
  s2-site/examples/custom/custom-cell/demo/row-cell.ts
  s2-site/examples/custom/custom-cell/demo/totals-cell.ts
Labels: pr(documentation)

#1365 fix(interaction): 修复自定义单元格有自定义图片时无法触发点击 close #1360
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1372 fix: fieldValue精度过高时intervalShape未绘制
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix)

#1371 fix(strategysheet): 修复趋势分析表多列头时叶子节点未和数值单元格对齐
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix)

#1368 fix: 明细表下range-selection报错
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/src/interaction/range-selection.ts
Labels: pr(fix)

#1373 docs: 增加 vue 自适应文档
  s2-site/docs/manual/advanced/adaptive.zh.md
Labels: pr(documentation)

#1369 docs: 修改 S2DataConfig 文案
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(documentation)

#1375 docs: readme中添加 s2-vue badges
  README.md
Labels: pr(documentation)

#1374 feat: sortFunc 支持使用手动排序兜底
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/utils/sort-action.ts
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/examples/analysis/sort/demo/custom-sort-func.ts
Labels: pr(feature)

#1376 chore: 并发构建
  package.json
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
Labels: pr(chore)

#1377 chore: 文案修正
  README.en-US.md
  README.md
  packages/s2-core/README.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(chore)

#1378 chore(ci): ci 构建提速
  .github/workflows/compressed-size.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .husky/pre-push
  package.json
  packages/s2-core/package.json
  packages/s2-react/package.json
  packages/s2-vue/package.json
Labels: pr(chore)

#1379 fix: 增加文本条件格式默认值
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix)

#1382 docs: 新增马赛克图
  s2-site/examples/case/art/demo/meta.json
  s2-site/examples/case/art/demo/mosaic.tsx
  s2-site/examples/case/art/index.en.md
  s2-site/examples/case/art/index.zh.md
Labels: pr(documentation)

#1380 docs: 文档增加 s2-vue 的说明
  .github/workflows/compressed-size.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.en-US.md
  README.md
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/package.json
  packages/s2-react/package.json
  packages/s2-vue/package.json
  s2-site/docs/common/browser.en.md
  s2-site/docs/common/browser.zh.md
  s2-site/docs/common/packages.en.md
  s2-site/docs/common/packages.zh.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(documentation)

#1383 feat: 新增 "如何用 S2 买房" demo
  packages/s2-react/src/components/advanced-sort/index.tsx
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/examples/case/data-preview/demo/house.tsx
  s2-site/examples/case/data-preview/demo/meta.json
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/gatsby-browser.js
Labels: pr(feature)

#1385 docs: 新增demo「想如何度过一天（抽象版）」
  s2-site/examples/case/art/demo/meta.json
  s2-site/examples/case/art/demo/mosaic.tsx
  s2-site/examples/case/art/demo/time-spend-abstract.tsx
  s2-site/examples/case/comparison/demo/time-spend.tsx
Labels: pr(documentation)

#1387 docs: 新增 facet 相关 API 和 循环滚动 demo
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/common/browser.zh.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/scroll-loop.ts
  s2-site/examples/interaction/advanced/demo/scroll-to-cell.ts
Labels: pr(documentation)

#1388 chore: 🔧 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore)

#1390 fix: style 引入失败
  package.json
  packages/s2-react/src/components/tooltip/index.tsx
Labels: pr(fix)

#1391 docs(vue): 添加 vue 3.0 组件demo
  README.en-US.md
  README.md
  s2-site/docs/manual/basic/analysis/vue.en.md
  s2-site/docs/manual/basic/analysis/vue.zh.md
  s2-site/docs/manual/getting-started.zh.md
Labels: pr(documentation)

#1389 fix(vue): 统一表组件变量名保持和 react 版本一致 Sheet => SheetComponent
  packages/s2-vue/README.md
  packages/s2-vue/playground/App.vue
  packages/s2-vue/src/components/index.ts
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/get-instance.zh.md
  s2-site/docs/manual/getting-started.zh.md
Labels: pr(fix)

#1393 fix(copy): 修复rowdata可能为null的情况
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1395 docs: 优化快速上手文档
  packages/s2-react/README.md
  packages/s2-react/playground/index.tsx
  packages/s2-vue/README.md
  s2-site/docs/manual/getting-started.zh.md
Labels: pr(documentation)
