Repository antvis/S2, pull requests merged in 2022-09, with the labels that each got.

#1722 fix: 修复 pagination 组件属性透传问题, 简化 usePagination 逻辑
  packages/s2-react/__tests__/unit/hooks/usePagination-spec.ts
  packages/s2-react/playground/index.less
  packages/s2-react/src/components/pagination/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/hooks/usePagination.ts
Labels: pr(fix)

#1723 fix(types): 修复严格模式下 S2Options 类型报错
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-react/__tests__/data/grid-analysis-data.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/playground/resize.tsx
  packages/s2-react/src/components/header/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-react/src/utils/options.ts
  packages/s2-shared/src/interface.ts
  packages/s2-shared/src/utils/drill-down.ts
  packages/s2-shared/src/utils/options.ts
  packages/s2-vue/src/interface.ts
Labels: pr(fix)

#1726 feat: 导出组件层CustomTooltip类
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-react/src/components/index.ts
  packages/s2-vue/src/components/index.ts
Labels: pr(feature)

#1729 fix: 修复tooltip 点击空白无法消失的问题
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-react/__tests__/data/grid-analysis-data.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/resize.tsx
Labels: pr(fix)

#1732 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1733 fix: 修复表格 onDestroy 卸载事件无法触发
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(fix)

#1684 feat: 趋势分析表支持配置图标条件
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
Labels: pr(feature)

#1739 fix: 修复闭包导致的pagination被错误重置的问题
  packages/s2-react/src/hooks/usePagination.ts
Labels: pr(fix)

#1740 docs: 修复组件 options 类型文档错误
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(documentation)

#1745 feat: readme文件增加QQ交流群二维码
  README.en-US.md
  README.md
Labels: pr(feature)

#1743 fix: 修复趋势分析表多列头情况下，单元格数据为空引起的复制数据偏移问题
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
Labels: pr(fix)

#1747 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1759 fix: 子弹图左侧文字未对齐
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/g-mini-charts.ts
Labels: pr(fix)

#1753 fix: 修复合并单元格条件格式不生效问题 close #1751
  packages/s2-core/src/cell/merged-cell.ts
Labels: pr(fix)

#1742 feat: 圈选复制行列头功能
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/utils/export/copy.ts
  s2-site/docs/manual/basic/analysis/export.zh.md
  s2-site/examples/interaction/basic/demo/brush-header.ts
  s2-site/examples/interaction/basic/demo/meta.json
Labels: pr(feature)

#1757 docs: 增加成都疫情数据场景案例
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/examples/case/kpi-strategy/demo/covid-trend.tsx
  s2-site/examples/case/kpi-strategy/demo/meta.json
Labels: pr(documentation)

#1762 feat(strategysheet): 支持自定义衍生指标
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  s2-site/docs/manual/basic/analysis/strategy.zh.md
Labels: pr(feature)

#1761 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#1746 fix(sort): 修复 tooltip 中排序菜单未记住上一次选中状态 close #1716
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/src/components/tooltip/components/operator.tsx
  packages/s2-react/src/components/tooltip/custom-tooltip.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-shared/src/styles/tooltip/operator.less
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/common/custom-tooltip.zh.md
Labels: pr(fix)

#1773 chore: 更新官网s2版本
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1772 docs: 使用文档补充下钻组件
  s2-site/docs/manual/basic/analysis/drill-down.en.md
  s2-site/docs/manual/basic/analysis/drill-down.zh.md
Labels: pr(documentation)

#1776 chore: 只在pr时运行 lint 和 test，减少时间开销
  .github/workflows/lint.yml
  .github/workflows/release-success.yml
  .github/workflows/test.yml
Labels: pr(chore)

#1777 docs: 抽离内置 icon 文档，并分别注入条件格式和自定义 icon 章节
  s2-site/docs/common/icon.en.md
  s2-site/docs/common/icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
Labels: pr(documentation)

#1779 chore: 统一 playground 代码风格
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/resize.tsx
  packages/s2-react/src/components/drill-down/index.less
  packages/s2-react/tsconfig.declaration.json
  packages/s2-react/tsconfig.json
  packages/s2-shared/src/utils/drill-down.ts
Labels: pr(chore)

#1717 feat(data-set)!: 删除 standardTransform，简化 pivotDataSet 逻辑
  packages/s2-core/__tests__/bugs/issue-725-spec.ts
  packages/s2-core/__tests__/bugs/issue-860-spec.ts
  packages/s2-core/__tests__/data/data-custom-trees.ts
  packages/s2-core/__tests__/data/data-issue-860.json
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-set/custom-tree-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/util.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/number-calculate-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/total.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/cell-data.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/number-calculate.ts
  packages/s2-core/src/utils/sort-action.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
  packages/s2-shared/src/interface.ts
Labels: pr(feature)

#1786 fix: table formatter with header selected
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1629 feat: 初版编辑表
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.less
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/index.tsx
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/utils/SpreadSheetContext.tsx
  packages/s2-react/src/utils/invokeComponent.tsx
  packages/s2-shared/src/interface.ts
Labels: pr(feature)

#1785 fix(scroll): 修复点击滚动条滑道区域表格渲染空白 close #1764 #1780
  packages/s2-core/__tests__/bugs/issue-1764-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/ui/scrollbar/index.ts
Labels: pr(fix)

#1791 fix: clipbardItem不存在时不报错
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#1792 fix: 将依赖检查移动到外层
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#1795 fix: 明细表奇数行背景色不生效修复
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix)

#1771 refactor: 将条件格式迷你柱形图绘制及主题配置统一归并到mini图中
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/playground/config.ts
Labels: pr(refactor)

#1687 feat： 明细表支持多级表头
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/sort-action.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/src/components/advanced-sort/index.tsx
  packages/s2-react/src/components/switcher/headerUtil.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/basic/table/demo/table-column-group.ts
Labels: 🙏 need test cases or docs

#1797 feat: 树状结构下, 行小计数据显示配置规则
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(feature)

#1802 refactor: 优化树状行小记隐藏单元格绘制逻辑
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(refactor)
