Repository antvis/S2, pull requests merged in 2022-03, with the labels that each got.

#1146 feat: :sparkles: 多指标单元格支持切换文本水对齐方式
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/src/components/sheets/strategy-sheet/strategy-theme.ts
Labels: pr(feature)

#1145 feat: 透出s2自带翻页器change事件
  packages/s2-react/src/components/pagination/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(feature)

#1148 fix: :bug: 趋势分析表主题调优
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/strategy-theme.ts
Labels: pr(fix)

#1149 fix: :bug: 修复s2-react组件污染全局样式问题 close#1144
  packages/s2-react/src/components/sheets/base-sheet/index.less
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
Labels: pr(fix)

#1147 feat(interaction): 框选下拉支持自动滚动
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/interaction/index.ts
  packages/s2-core/src/utils/interaction/scroll.ts
  packages/s2-core/src/utils/layout/index.ts
Labels: pr(feature)

#1154 fix: 明细表排序 API 和透视表对齐
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/sort-action.ts
  s2-site/docs/common/sort-params.zh.md
  s2-site/docs/manual/basic/sort/custom.zh.md
  s2-site/examples/analysis/sort/demo/meta.json
  s2-site/examples/analysis/sort/demo/table-sort.ts
  s2-site/examples/analysis/sort/demo/table-sort.tsx
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/data/basic-table-mode.json
Labels: pr(fix)

#1160 docs: 文档校正，主要涉及属性：collapsedRows、calcTotals、calcSubTotals 和 width、height
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-react/src/hooks/useResize.ts
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/basic/pivot/demo/tree.ts
Labels: pr(documentation)

#1163 chore: 增加 rejected label action
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#1157 feat(totals): 增加前端totals计算方式
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/__tests__/unit/utils/number-calculate-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/utils/number-calculate.ts
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  yarn.lock
Labels: pr(feature)

#1152 feat: 列头滚动场景下非维度文字支持左/右对齐
  packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/utils/cell/cell.ts
  s2-site/docs/manual/advanced/custom/cell-align.zh.md
Labels: pr(feature)

#1161 fix: 开启 adaptive 时，options 更改后, 宽高不跟随 wrapperRef 的宽高改变
  packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
  packages/s2-react/src/hooks/useResize.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  s2-site/docs/manual/advanced/adaptive.zh.md
Labels: pr(fix)

#1168 chore(release): @antv/s2@1.12.0 @antv/s2-react@1.12.0
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1170 docs: update table data docs
  s2-site/examples/analysis/conditions/demo/table-text.ts
  s2-site/examples/basic/table/demo/table.ts
  s2-site/examples/interaction/advanced/demo/table-hide-columns.ts
  s2-site/examples/interaction/advanced/demo/table-link-jump.ts
  s2-site/examples/interaction/basic/demo/auto-reset-sheet-style.ts
  s2-site/examples/interaction/basic/demo/frozen.ts
  s2-site/examples/react-component/sheet/demo/table.tsx
Labels: pr(documentation)

#1173 fix: 修复draggable事件失效问题 close#1172
  packages/s2-core/src/interaction/brush-selection.ts
Labels: pr(fix)

#1175 fix: 修复趋势分析表多指标丢失问题
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
Labels: pr(fix)

#1176 test(interaction): 新增重复事件注册的测试
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
Labels: pr(test)

#1180 fix: 修复趋势分析表空数据不渲染问题
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
Labels: pr(fix)

#1183 docs: 修复Safari 15 无法访问官网的问题
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#1184 fix: 支持 Ctrl 键触发多选 Cell
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#1171 feat(derection): 方向键加快捷键操作
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-core/src/utils/interaction/state-controller.ts
Labels: pr(feature)

#1186 chore: 修复自动同步changelog action 无法触发 ci 的问题
  .github/workflows/sync-site-lock-changelog-with-pr.yml
Labels: pr(chore)

#1185 feat: 趋势分析表支持列展示不同数量的指标
  package.json
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(feature)

#1192 fix: 修复linkTextFill不生效的问题, close #1191
  packages/s2-core/__tests__/bugs/issue-1191-spec.ts
  packages/s2-core/src/cell/base-cell.ts
Labels: pr(fix)

#1196 fix: 有自定义行高，但表格高度为 0 时卡死的问题
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/src/utils/facet.ts
Labels: pr(fix)

#1140 fix: 修复一些包之间的依赖问题
  .eslintrc
  package.json
  packages/s2-core/__tests__/unit/utils/get-all-child-cells-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/package.json
  packages/s2-core/rollup.config.js
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/index.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/get-all-child-cells.ts
  packages/s2-react/__tests__/bugs/issue-594-spec.tsx
  packages/s2-react/__tests__/spreadsheet/custom/custom-interaction.tsx
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/__tests__/unit/utils/__snapshots__/build-table-hierarchy-spec.tsx.snap
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/package.json
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/switcher/content/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/utils/drill-down.ts
  packages/s2-react/vite.config.ts
  yarn.lock
Labels: pr(fix)

#1194 fix(react): 修复宽高改变后未重新渲染表格的问题 close #1193
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useResize.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(fix)

#1195 fix(adaptive): 修复开启自适应后 组件在 Safari 上无法渲染的问题 close #1164
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useResize.ts
Labels: pr(fix)

#1198 chore(release): @antv/s2@1.12.3 @antv/s2-react@1.12.3
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1199 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1200 fix: 未开启自适应, 改变浏览器窗口大小, 会导致表格重新渲染 close #1197
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1203 chore: 增加一些 eslint 规则
  .eslintrc
  .github/workflows/issue-labeled.yml
  package.json
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/__tests__/unit/utils/number-calculate-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/rollup.config.js
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/layout/build-header-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-react/package.json
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/switcher/headerUtil.ts
  packages/s2-react/src/utils/drill-down.ts
  packages/s2-react/vite.config.ts
  yarn.lock
Labels: pr(chore)

#1205 fix: 修复趋势分析表label文字对齐问题
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#1207 fix: 行列头多选支持 Ctrl 键
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/select-event-spec.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/interaction/select-event.ts
Labels: pr(fix)

#1208 fix(table-facet): 修复row高度大于canvas高度后导致的index计算错误
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#1210 fix: 单元格内换行存在"字符
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1167 fix: 修复以行列总计依赖度量汇总排序失败问题。
  packages/s2-core/__tests__/data/sort-advanced.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/utils/sort-action.ts
  s2-site/docs/manual/basic/sort/custom.zh.md
Labels: pr(fix)

#1213 docs: 修复自定义角头单元格 demo
  s2-site/examples/custom/custom-cell/demo/corner-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
Labels: pr(documentation)

#1211 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1218 fix(facet): 修复getIndexRangeWithOffsets在minHeight和maxHeight相等的情况下返回错误的情况
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/src/utils/facet.ts
Labels: pr(fix)

#1219 feat: 添加行头和列头的格式化功能
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(feature)

#1222 fix: headerActionIcons更新覆盖了下钻icon展示
  packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
Labels: pr(fix)
