Repository antvis/S2, pull requests merged in 2022-11, with the labels that each got.

#1863 docs: 更新README.md添加洞察分析
  README.md
Labels: pr(documentation)

#1854 fix: 重构绘制盒模型，修复边框偏移问题
  packages/s2-core/__tests__/bugs/issue-1539-spec.ts
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/facet/bbox/panelBBox-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/row-node-width-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/cell/table-corner-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/frame.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/group/grid-group.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-core/src/utils/layout/frozen.ts
  packages/s2-core/src/utils/text.ts
  s2-site/examples/custom/custom-cell/demo/col-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-cell.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/row-cell.ts
  s2-site/examples/custom/custom-cell/demo/totals-cell.ts
Labels: pr(fix)

#1874 fix: 修复 mergedCell 缺失theme 导致的报错
  .github/workflows/auto-release.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#1865 chore: 更新README
  README.md
Labels: pr(chore)

#1876 fix: ts problem
  .github/workflows/auto-release.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  package.json
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-react/playground/components/CustomGrid.tsx
  packages/s2-react/playground/components/CustomTree.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/pagination/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/components/sheets/mobile-sheet/index.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/components/switcher/item/single-item.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-react/src/utils/options.ts
Labels: pr(fix), 🚨 test failed, 🚨 lint failed

#1880 feat: 新增 measureTextHeight 用于测量文字高度
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: pr(feature)

#1882 docs: 更新master分支表格性能对比数据
  s2-site/examples/data/compare.json
Labels: pr(documentation)

#1871 docs: 更新性能对比文档中的dataSet说明，和性能对比数据
  s2-site/api-extractor.json
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/manual/advanced/performance.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/data/compare.json
Labels: pr(documentation)

#1887 docs: 新增自定义特定单元格示例
  s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/meta.json
Labels: pr(documentation)

#1886 docs(theme): 新增透明背景色主题配置示例
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/examples/theme/custom/demo/custom-schema.ts
  s2-site/examples/theme/custom/demo/custom-transparent-background.ts
  s2-site/examples/theme/custom/demo/meta.json
Labels: pr(documentation)

#1877 docs: 更新README，增加数据洞察
  README.en-US.md
  README.md
Labels: pr(documentation)

#1889 feat(interaction): 角头有省略号时 hover 后显示 tooltip
  .github/workflows/compressed-size.yml
  packages/s2-core/__tests__/unit/cell/corner-cell-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/index.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/playground/index.tsx
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
Labels: pr(feature)

#1888 fix: 修复行头链接跳转时，获取行数据的问题
  packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
Labels: pr(fix)

#1901 chore(release): bump version
  packages/s2-core/package.json
Labels: pr(chore)

#1903 docs: 优化 Issues/PR 模板
  .github/ISSUE_TEMPLATE/ask-for-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-release.yml
  .github/workflows/issue-labeled.yml
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/theme/custom/demo/custom-generate-palette.tsx
Labels: pr(documentation)

#1908 fix: 修复sortedDimensionValues过滤不正确而导致的排序错乱的问题
  packages/s2-core/__tests__/spreadsheet/sort-by-order-spec.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
Labels: pr(fix)

#1910 fix: 修复官网样例数据路径问题
  s2-site/.dumirc.ts
  s2-site/examples/analysis/sort/demo/custom-list.ts
  s2-site/examples/analysis/sort/demo/custom-measure.ts
  s2-site/examples/analysis/sort/demo/custom-method.ts
  s2-site/examples/analysis/sort/demo/custom-sort-func.ts
  s2-site/examples/analysis/sort/demo/table-sort.tsx
  s2-site/examples/analysis/totals/demo/calculate.ts
  s2-site/examples/analysis/totals/demo/custom.ts
  s2-site/examples/basic/table/demo/table.ts
  s2-site/examples/case/art/demo/time-spend-abstract.tsx
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
  s2-site/examples/case/comparison/demo/multiple-people-comparison.tsx
  s2-site/examples/case/comparison/demo/time-spend.tsx
  s2-site/examples/case/data-preview/demo/excel.tsx
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/case/kpi-strategy/demo/basic.tsx
  s2-site/examples/case/performance-compare/demo/basic.tsx
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/interaction/advanced/demo/scroll-speed-ratio.ts
  s2-site/examples/interaction/advanced/demo/table-hide-columns.ts
  s2-site/examples/interaction/advanced/demo/table-link-jump.ts
  s2-site/examples/interaction/basic/demo/auto-reset-sheet-style.ts
  s2-site/examples/layout/custom/demo/custom-table-size.ts
  s2-site/examples/layout/custom/demo/hide-columns.ts
  s2-site/examples/react-component/pagination/demo/table.tsx
  s2-site/examples/react-component/sheet/demo/table.tsx
  s2-site/examples/react-component/tooltip/demo/custom-description.tsx
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(fix)

#1885 feat: 官网新增在线体验功能
  s2-site/.dumi/pages/playground.en.tsx
  s2-site/.dumi/pages/playground.zh.tsx
  s2-site/.dumirc.ts
  s2-site/docs/manual/faq.zh.md
  s2-site/playground/config-panel/attribute-tree.tsx
  s2-site/playground/config-panel/config-component/base/index.less
  s2-site/playground/config-panel/config-component/base/index.tsx
  s2-site/playground/config-panel/config-component/collapse-panel/index.tsx
  s2-site/playground/config-panel/config-component/collapse/index.less
  s2-site/playground/config-panel/config-component/collapse/index.tsx
  s2-site/playground/config-panel/config-component/color-picker/index.less
  s2-site/playground/config-panel/config-component/color-picker/index.tsx
  s2-site/playground/config-panel/config-component/index.tsx
  s2-site/playground/config-panel/config-component/input-number/index.less
  s2-site/playground/config-panel/config-component/input-number/index.tsx
  s2-site/playground/config-panel/config-component/radio/index.tsx
  s2-site/playground/config-panel/config-component/select/index.less
  s2-site/playground/config-panel/config-component/select/index.tsx
  s2-site/playground/config-panel/config-component/switcher/index.tsx
  s2-site/playground/config-panel/config-component/tab-pane/index.tsx
  s2-site/playground/config-panel/config-component/tab/index.less
  s2-site/playground/config-panel/config-component/tab/index.tsx
  s2-site/playground/config-panel/config-token/index.ts
  s2-site/playground/config-panel/index.tsx
  s2-site/playground/config-panel/types.ts
  s2-site/playground/dataset/mock-dataset.json
  s2-site/playground/layouts/index.less
  s2-site/playground/layouts/index.tsx
  s2-site/playground/sheet-component/config.ts
  s2-site/playground/sheet-component/index.less
  s2-site/playground/sheet-component/index.tsx
  s2-site/yarn.lock
Labels: pr(feature)

#1913 docs: 修复英语文档启动错误的问题
  s2-site/docs/api/basic-class/base-cell.en.md
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-facet.en.md
  s2-site/docs/api/basic-class/base-tooltip.en.md
  s2-site/docs/api/basic-class/interaction.en.md
  s2-site/docs/api/basic-class/node.en.md
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/store.en.md
  s2-site/docs/manual/basic/base-concept.en.md
  s2-site/docs/manual/basic/sheet-type/table-mode.en.md
  s2-site/docs/manual/basic/theme.en.md
  s2-site/docs/manual/getting-started.en.md
  s2-site/package.json
  s2-site/script/translationHtml.mjs
  s2-site/yarn.lock
Labels: pr(documentation)

#1883 fix: 修复圈选偏移问题
  packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
Labels: pr(fix)

#1905 fix(interaction): 修复多列头多指标场景下隐藏列头错误 close #1721
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/layout-hooks.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  s2-site/docs/api/basic-class/base-facet.zh.md
Labels: pr(fix)

#1915 fix: 官网问题走查
  s2-site/.dumi/global.ts
  s2-site/docs/api/basic-class/base-tooltip.en.md
  s2-site/docs/api/basic-class/interaction.en.md
  s2-site/docs/api/components/export.en.md
  s2-site/docs/api/components/header.en.md
  s2-site/docs/api/components/header.zh.md
  s2-site/docs/api/general/S2DataConfig.en.md
  s2-site/docs/api/general/S2Options.en.md
  s2-site/docs/common/custom/dataCellCallback.en.md
  s2-site/docs/common/packages.en.md
  s2-site/docs/common/packages.zh.md
  s2-site/docs/manual/advanced/custom/category-tree.en.md
  s2-site/docs/manual/advanced/custom/category-tree.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.en.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.en.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/advanced/interaction/custom.en.md
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.en.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/docs/manual/advanced/interaction/link-jump.en.md
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.en.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/docs/manual/basic/analysis/copy-export.en.md
  s2-site/docs/manual/basic/analysis/copy-export.zh.md
  s2-site/docs/manual/basic/analysis/drill-down.en.md
  s2-site/docs/manual/basic/analysis/drill-down.zh.md
  s2-site/docs/manual/basic/analysis/pagination.en.md
  s2-site/docs/manual/basic/analysis/pagination.zh.md
  s2-site/docs/manual/basic/analysis/strategy.en.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/docs/manual/basic/analysis/switcher.en.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/conditions.en.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.en.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/docs/manual/basic/theme.en.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/docs/manual/basic/tooltip.en.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/faq.en.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.en.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.en.md
  s2-site/package.json
  s2-site/site.css
  s2-site/yarn.lock
Labels: pr(fix)

#1916 chore: 合并master
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/layout-hooks.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/script/translation.mjs
  s2-site/yarn.lock
Labels: pr(chore)

#1921 feat: 明细表支持多级表头
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-dataset-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/sort-action.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/src/components/advanced-sort/index.tsx
  packages/s2-react/src/components/switcher/headerUtil.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/examples/basic/table/demo/meta.json
  s2-site/examples/basic/table/demo/table-column-group.ts
  s2-site/examples/data/basic-table-mode.json
  s2-site/examples/data/basic-totals.json
  s2-site/examples/data/basic.json
  s2-site/examples/data/compare.json
  s2-site/examples/data/index-comparison.json
  s2-site/examples/data/kpi-strategy.json
  s2-site/examples/data/multiple-people-comparison.json
  s2-site/examples/data/multiple-values-totals.json
  s2-site/examples/data/single-population-proportion.json
  s2-site/examples/data/time-spend.json
Labels: pr(feature)

#1923 chore: 修复明细表多列头下无数据展示
  packages/s2-react/__tests__/data/mock-dataset.json
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
Labels: pr(chore)

#1925 docs: 修复官网部分展示问题
  s2-site/docs/manual/advanced/interaction/merge-cell.en.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/docs/manual/basic/analysis/copy-export.en.md
  s2-site/docs/manual/basic/analysis/strategy.en.md
  s2-site/docs/manual/basic/sort/custom.en.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/script/translation.mjs
Labels: pr(documentation)

#1858 feat: 编辑表格新增拖拽填充功能
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.less
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-point.less
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/index.tsx
Labels: pr(feature), 🙏 need test cases or docs

#1928 chore(release): bump version
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1927 docs: 添加 mini 图相关文档
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/theme.ts
  s2-site/docs/api/general/S2DataConfig.en.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/common/custom/customTreeItem.en.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/common/mini-chart.en.md
  s2-site/docs/common/mini-chart.zh.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
Labels: pr(documentation)

#1930 feat: 补充英文文档
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/common/mini-chart.en.md
  s2-site/docs/manual/basic/analysis/strategy.en.md
Labels: pr(feature)

#1932 docs: 更新过期包厢二维码
  .github/workflows/mirror.yml
  README.en-US.md
  README.md
Labels: pr(documentation)

#1934 fix: playground not work
  s2-site/.dumirc.ts
Labels: pr(fix)

#1936 fix: 修复编辑表格数据获取问题
  s2-site/.gitignore
  s2-site/examples/react-component/sheet/demo/editable.tsx
Labels: pr(fix)

#1942 chore: 优化自动发布 CI
  .github/workflows/issues-similarity-analysis.yml
  .github/workflows/release-notify.yml
  .github/workflows/release-success.yml
  .github/workflows/site-build-notify.yml
  .github/workflows/sync-notify.yml
  .releaserc.base.js
  package.json
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/package.json
  packages/s2-react/README.md
  packages/s2-react/package.json
  packages/s2-react/playground/index.tsx
  packages/s2-vue/README.md
  packages/s2-vue/package.json
  s2-site/examples/interaction/advanced/demo/scroll-loop.ts
  s2-site/examples/layout/custom/demo/custom-pivot-size.ts
  s2-site/examples/layout/custom/demo/custom-row-col-cell-width.ts
  s2-site/examples/layout/custom/demo/custom-table-size.ts
  s2-site/examples/layout/custom/demo/custom-tree-row-width.ts
  s2-site/examples/theme/custom/demo/custom-transparent-background.ts
  s2-site/package.json
Labels: pr(chore)

#1950 fix: 角头序号单元格meta无spreadsheet实例
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/src/facet/header/corner.ts
Labels: pr(fix)

#1952 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore)

#1954 fix(dataset): 修复数据undefined情况
  packages/s2-core/src/data-set/table-data-set.ts
Labels: pr(fix)

#1956 feat: shift+按键支持横向滚动
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(feature)

#1953 fix(facet): 调整 layoutCoordinate 执行顺序
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), 🙏 need test cases or docs
