Repository antvis/S2, pull requests merged in 2022-10, with the labels that each got.

#1804 chore(release): bump version
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1805 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1800 chore: 官网版本升级
  packages/s2-react/playground/index.tsx
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1799 feat(total): 全量移除所有 totalData 配置
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/__tests__/unit/cell/custom-tree-corner-cell-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-set/custom-tree-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/facet/util.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/__tests__/unit/utils/split-total-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/__tests__/util/index.ts
  packages/s2-core/src/common/constant/dataConfig.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/index.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-react/playground/index.tsx
Labels: pr(feature)

#1801 fix: 明细表多级表头固定多行和多列后数据和界面渲染不正确
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
Labels: pr(fix)

#1812 fix: 带行头复制报错修复
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1813 fix: 修复KPI趋势表demo
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/case/kpi-strategy/demo/basic.tsx
  s2-site/examples/data/kpi-strategy.json
  s2-site/yarn.lock
Labels: pr(fix)

#1809 feat: ✨ 表头单元格支持字段标记
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-react/playground/config.ts
Labels: pr(feature)

#1819 chore: 自动发布 commit 触发条件 增加 refactor 和 style
  .releaserc.base.js
Labels: pr(chore)

#1816 fix(tooltip): tooltip 显示时不应该强制清空 dom
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/src/components/tooltip/custom-tooltip.tsx
  s2-site/docs/common/custom-tooltip.zh.md
Labels: pr(fix)

#1822 fix: data-cell文字无法交互
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix)

#1828 feat: 在生成 id 时，对 undefined, null 做区分
  packages/s2-core/__tests__/unit/utils/layout/generate-id.spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/utils/layout/generate-id.ts
  packages/s2-core/src/utils/layout/index.ts
Labels: pr(feature)

#1831 fix: 修复open属性冲突的问题 close #1736
  packages/s2-react/__tests__/bugs/issue-1736-spec.tsx
  packages/s2-react/src/components/export/index.tsx
  s2-site/docs/api/components/export.zh.md
Labels: pr(fix)

#1825 fix(interaction): 修复滚动刷选 onDataCellBrushSelection 未透出正确的单元格 close #1817
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/tooltip/components/detail.tsx
  packages/s2-react/src/components/tooltip/components/head-info.tsx
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-shared/src/interface.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(fix)

#1834 fix: 紧凑模式下节点宽度计算错误
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#1837 fix: 修复文档 SplitLine 参数错误 close #1836
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(fix)

#1839 fix: 自适应模式节点宽度计算错误
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#1843 fix: 修复 SheetComponent 未使用 getSpreadSheet 也会报 warning 的问题
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/index.tsx
Labels: pr(fix)

#1841 fix: bold字体对应数字字重不正确
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-tree-mode-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/src/theme/index.ts
Labels: pr(fix)

#1814 fix: customFilter执行时不再执行defaultFilter
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
Labels: pr(fix)

#1844 chore(release): 🔖@antv/s2@1.32.0 @antv/s2-react@1.29.0 @antv/s2-vue@1…
  packages/s2-core/package.json
  packages/s2-react/package.json
  packages/s2-vue/package.json
Labels: pr(chore)

#1847 fix(theme): 获取标准色时增加容错和兜底
  packages/s2-core/__tests__/unit/utils/color-spec.ts
  packages/s2-core/src/utils/color.ts
Labels: pr(fix)

#1842 feat: 在背景字段标记中添加 文本智能反色
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/constant/condition.ts
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/utils/color.ts
  s2-site/docs/common/conditions.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/examples/analysis/conditions/demo/intelligent-background.ts
  s2-site/examples/analysis/conditions/demo/meta.json
Labels: pr(feature)

#1849 docs: 补充表头单元格条件格式文档demo
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/examples/analysis/conditions/demo/background.ts
  s2-site/examples/analysis/conditions/demo/icon.ts
  s2-site/examples/analysis/conditions/demo/meta.json
  s2-site/examples/analysis/conditions/demo/text.ts
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(documentation)

#1852 fix: 修复新版g5.0clipPath计算规则改变导致的裁剪错位问题
  packages/s2-core/package.json
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/table-facet.ts
  yarn.lock
Labels: pr(fix), 🚨 lint failed

#1840 refactor: 将 layer groups 全部收敛到 facet 中
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/__tests__/bugs/issue-1668-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-resize-spec.ts
  packages/s2-core/__tests__/unit/facet/bbox/panelBBox-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/resize-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/common/constant/frozen.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-core/src/utils/interaction/resize.ts
Labels: pr(refactor)

#1833 [WIP] feat: 移动端组件适配
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/utils/is-mobile.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/mobile-tooltip-spec.tsx
  packages/s2-react/__tests__/unit/components/tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/common/constant/options.ts
  packages/s2-react/src/components/advanced-sort/index.less
  packages/s2-react/src/components/header/index.less
  packages/s2-react/src/components/header/index.tsx
  packages/s2-react/src/components/icons/index.less
  packages/s2-react/src/components/sheets/base-sheet/index.less
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.less
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/mobile-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
  packages/s2-react/src/components/switcher/content/index.less
  packages/s2-react/src/components/switcher/dimension/index.less
  packages/s2-react/src/components/switcher/index.less
  packages/s2-react/src/components/switcher/item/index.less
  packages/s2-react/src/components/tooltip/components/head-info.tsx
  packages/s2-react/src/components/tooltip/components/summary.tsx
  packages/s2-react/src/components/tooltip/context.ts
  packages/s2-react/src/components/tooltip/custom-tooltip.tsx
  packages/s2-react/src/components/tooltip/style.less
  packages/s2-react/src/context/SpreadSheetContext.tsx
  packages/s2-react/src/utils/invokeComponent.tsx
  packages/s2-shared/__tests__/utils/options-spec.ts
  packages/s2-shared/src/constant/classnames.ts
  packages/s2-shared/src/styles/drill-down.less
  packages/s2-shared/src/styles/tooltip/index.less
  packages/s2-shared/src/styles/tooltip/operator.less
  packages/s2-shared/src/styles/variables.less
  packages/s2-shared/src/utils/options.ts
  packages/s2-vue/src/styles/variable.less
  s2-site/docs/manual/basic/analysis/mobile-component.en.md
  s2-site/docs/manual/basic/analysis/mobile-component.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/examples/case/comparison/demo/philosophers.tsx
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/examples/react-component/sheet/demo/meta.json
  s2-site/examples/react-component/sheet/demo/mobile-pivot.tsx
Labels: 🚨 test failed, 🚨 lint failed

#1860 test: 修复单测错误
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-shared/__tests__/utils/options-spec.ts
  packages/s2-vue/src/components/sheets/base-sheet.vue
Labels: pr(test)
