Repository antvis/S2, pull requests merged in 2022-08, with the labels that each got.

#1640 docs: 优化文档说法和校正有误的内容
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/merged-cell.en.md
  s2-site/docs/common/merged-cell.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/docs/manual/basic/sort/basic.zh.md
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
  s2-site/examples/data/index-comparison.json
Labels: pr(documentation)

#1644 fix: 修复存在 0 时，数值为 number 时，排序错误的问题
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/utils/sort-action.ts
Labels: pr(fix)

#1633 fix(pagination): 分页配置未传 current 参数时表格渲染空白
  packages/s2-core/__tests__/bugs/issue-1587-spec.ts
  packages/s2-core/src/common/constant/index.ts
  packages/s2-core/src/common/constant/pagination.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-react/playground/index.tsx
  packages/s2-shared/src/utils/resize.ts
  s2-site/docs/common/pagination.zh.md
  s2-site/docs/manual/basic/analysis/pagination.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/examples/theme/custom/demo/custom-schema.ts
Labels: pr(fix)

#1647 feat: 复制支持html格式
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/index.ts
Labels: pr(feature)

#1638 feat(interaction): 宽高调整事件透出 resizedWidth/resizedHeight, 修复错误类型定义
  .github/workflows/pr-auto-assign-reviewer.yml
  packages/s2-core/__tests__/spreadsheet/spread-sheet-resize-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/common/interaction.zh.md
Labels: pr(feature)

#1623 fix: 修复pivot模式 cell点击事件无法触发BUG
  packages/s2-vue/playground/App.vue
  packages/s2-vue/src/components/sheets/pivot-sheet.vue
  packages/s2-vue/src/utils/initPropAndEmits.ts
Labels: pr(fix)

#1649 chore: 发布成功后自动部署官网
  .github/workflows/release-success.yml
Labels: pr(chore)

#1646 fix(layout): 修复 treeRowsWidth 配置不生效 close #1622
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-react/playground/config.ts
  s2-site/docs/common/style.zh.md
Labels: pr(fix)

#1650 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
  yarn.lock
Labels: pr(chore)

#1654 fix: 修复选中态的描边宽度样式问题
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/src/cell/base-cell.ts
Labels: pr(fix)

#1652 fix: 链接字段高亮下划线过长
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#1655 feat: 明细表行头单元格支持拖拽
  packages/s2-core/__tests__/spreadsheet/table-resize-spec.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(feature)

#1653 fix(interaction): 优化resetSheetStyle性能
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/state-controller.ts
Labels: pr(fix)

#1661 docs: 官网文档优化
  s2-site/docs/api/components/header.en.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.en.md
  s2-site/docs/manual/contribution.zh.md
Labels: pr(documentation)

#1664 fix(scroll): 修复滚动边界判断错误导致无法滚动
  packages/s2-core/src/common/interface/scroll.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-react/playground/config.ts
  s2-site/docs/api/basic-class/base-facet.zh.md
Labels: pr(fix)

#1673 chore: update the reviewers
  .github/workflows/pr-auto-assign-reviewer.yml
Labels: pr(chore)

#1675 fix(resize): 修复总计列存在子节点时无法调整宽度
  packages/s2-core/__tests__/bugs/issue-1668-spec.ts
  packages/s2-core/__tests__/data/data-issue-1668.json
  packages/s2-core/src/cell/col-cell.ts
Labels: pr(fix)

#1678 fix: 修复明细表 onRaneSort 失效问题
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1679 fix: 修复趋势分析表对于不同个数同环比列头复制时，数据不对齐的问题
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/strategy-sheet-spec.tsx
Labels: pr(fix)

#1671 fix(scroll): 修复滚动条显示越界 & 优化滚动性能
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/common/interface/scroll.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  packages/s2-react/playground/config.ts
  s2-site/docs/api/basic-class/base-facet.zh.md
Labels: pr(fix)

#1680 feat: 刷选时支持高亮所有对应的行列头cell
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#1682 fix: 双击时不取消datacell 选中态
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
Labels: pr(fix)

#1685 chore: 增加 eslint 规则 & 同步国内镜像同步通知
  .eslintrc.js
  .github/workflows/mirror.yml
  .github/workflows/sync-notify.yml
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/layout/build-header-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/export-worker.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-react/__tests__/spreadsheet/custom/custom-interaction.tsx
  packages/s2-react/src/components/drill-down/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-vue/playground/App.vue
  packages/s2-vue/src/components/drill-down/index.vue
  packages/s2-vue/src/components/tooltip/components/summary.vue
Labels: pr(chore)

#1693 chore: 优化lint, test action，取消上一次的action运行，减少pending时间
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: pr(chore)

#1692 chore: 优化 CI/模板 的一些文案和提示
  .github/ISSUE_TEMPLATE/ask-for-question.md
  .github/workflows/auto-release.yml
  .github/workflows/release-success.yml
  .github/workflows/site-build-notify.yml
Labels: pr(chore)

#1689 feat: actionIcons支持细粒度展示控制
  packages/s2-core/__tests__/unit/utils/cell/header-cell-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/cell/header-cell.ts
  packages/s2-core/src/utils/cell/table-col-cell.ts
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/common/custom/headerActionIcons.zh.md
  s2-site/docs/common/header-action-icon.zh.md
Labels: pr(feature)

#1691 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1698 fix(pagination): 透传组件分页参数 & 修复国际化不生效 close #1697
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-react/__tests__/spreadsheet/__snapshots__/pagination-spec.tsx.snap
  packages/s2-react/__tests__/spreadsheet/pagination-spec.tsx
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/pagination/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/utils/options.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/interface.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  s2-site/docs/manual/basic/analysis/pagination.zh.md
  s2-site/examples/react-component/pagination/demo/pivot.tsx
Labels: pr(fix)

#1701 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1703 feat: 在树状模式下，增加默认展开层级的配置
  packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/style.zh.md
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/row-expand-depth.ts
Labels: pr(feature)

#1704 fix: tablefacet销毁时off事件
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), 🙏 need test cases or docs

#1694 chore: facet.startsScroll添加被动参数
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(chore)

#1706 fix: text居中居右时link绘制错位
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
Labels: pr(fix)

#1699 feat: 实现行头和列头的圈选功能
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/index.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-shared/__tests__/utils/options-spec.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#1709 chore: 增加 alpha/beta 版本发布 devDeps 校验
  .husky/common.sh
  .husky/pre-commit
  .husky/pre-push
  package.json
  scripts/validate-deps.js
Labels: pr(chore)

#1712 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1710 chore: 新增命令自动向 react 和 Vue 同步原生事件脚本
  package.json
  packages/s2-core/package.json
  packages/s2-core/scripts/sync-event.mjs
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/hooks/useEvents.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/common/interaction.zh.md
Labels: pr(chore)

#1720 chore: 修复官网构建不压缩问题
  s2-site/package.json
Labels: pr(chore)
