Repository antvis/S2, pull requests merged in 2022-06, with the labels that each got.

#1398 docs: 补充表组件部分文档
  s2-site/docs/api/components/advanced-sort.zh.md
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/api/components/header.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/components/switcher.zh.md
Labels: pr(documentation)

#1397 fix(locale): 修复国际化配置不生效 close #1394
  packages/s2-core/__tests__/unit/common/i18n/index-spec.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/i18n/index.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/common/constant/index.ts
  packages/s2-react/src/components/advanced-sort/custom-sort.tsx
  packages/s2-react/src/components/advanced-sort/index.tsx
  packages/s2-react/src/components/export/index.tsx
  packages/s2-react/src/components/header/index.tsx
  packages/s2-react/src/components/switcher/constant.ts
  packages/s2-react/src/components/switcher/content/index.less
  packages/s2-react/src/components/switcher/content/index.tsx
  packages/s2-react/src/components/switcher/dimension/index.tsx
  packages/s2-shared/src/constant/i18n/en_US.ts
  packages/s2-shared/src/constant/i18n/zh_CN.ts
  packages/s2-shared/src/constant/index.ts
  packages/s2-shared/src/constant/sort.ts
  packages/s2-shared/src/index.ts
  packages/s2-vue/src/common/constant/index.ts
  packages/s2-vue/src/common/constant/sort.ts
  s2-site/docs/manual/basic/i18n.en.md
  s2-site/docs/manual/basic/i18n.zh.md
Labels: pr(fix)

#1402 refactor: 删除无用的 debounceRenderCell 方法
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(refactor)

#1401 docs: 添加自适应布局demo
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/basic/analysis/vue.zh.md
  s2-site/examples/case/data-preview/demo/house.tsx
  s2-site/examples/layout/adaptive/API.en.md
  s2-site/examples/layout/adaptive/API.zh.md
  s2-site/examples/layout/adaptive/demo/container-adaptation.ts
  s2-site/examples/layout/adaptive/demo/meta.json
  s2-site/examples/layout/adaptive/demo/react-adaptive.tsx
  s2-site/examples/layout/adaptive/demo/window-adaptation.ts
  s2-site/examples/layout/adaptive/index.en.md
  s2-site/examples/layout/adaptive/index.zh.md
Labels: pr(documentation)

#1405 chore(release): 🔖@antv/s2@1.18.1 @antv/s2-vue@1.0.1
  packages/s2-vue/package.json
Labels: pr(chore)

#1408 fix: 修复打包core层源码中样式文件错误问题
  packages/s2-react/src/components/tooltip/index.less
  packages/s2-react/src/components/tooltip/index.tsx
  packages/s2-vue/src/components/tooltip/index.vue
Labels: pr(fix)

#1407 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
  s2-site/.yarnrc
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1413 docs: 更新vue组件demo
  s2-site/docs/manual/basic/analysis/vue.zh.md
Labels: pr(documentation)

#1409 feat(scroll): 增加边界滚动配置, 解决横屏滚动会触发 mac 回退的问题
  packages/s2-core/__tests__/bugs/issue-372-spec.ts
  packages/s2-core/__tests__/bugs/issue-836-spec.ts
  packages/s2-core/__tests__/bugs/issue-860-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/frozen-util-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/index.tsx
  packages/s2-shared/__tests__/utils/options-spec.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/docs/manual/basic/i18n.zh.md
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/overscroll-behavior.ts
  s2-site/examples/react-component/sheet/demo/strategy.tsx
Labels: pr(feature)

#1418 fix(tooltip): 减少 tooltip 框重绘
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/ui/tooltip/index.less
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.less
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(fix)

#1424 fix(sort): 透视表/明细表 排序菜单文案显示错误
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-remove-inactive.yml
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
Labels: pr(fix)

#1426 docs: 修正一些错误文档
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/hooks/useSpreadSheet.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/style.zh.md
  s2-site/docs/common/totals.zh.md
Labels: pr(documentation)

#1415 feat: canvas 未聚焦时不触发选中格子的键盘 move 行为
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
Labels: pr(feature)

#1431 fix: 修复序号对齐问题， close #1412
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/theme/index.ts
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(fix), 🙏 need test cases or docs

#1433 fix(copy): 修复字段名带有-导致复制失败的问题
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#1432 docs: [滚动] 提取成独立章节
  .github/workflows/compressed-size.yml
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/custom/customTreeItem.zh.md
  s2-site/docs/common/sort-params.zh.md
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/docs/manual/advanced/hd-adapter.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/scroll.en.md
  s2-site/docs/manual/advanced/interaction/scroll.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/examples/interaction/advanced/demo/scroll-loop.ts
Labels: pr(documentation)

#1435 fix: 树状结构下，子节点全部折叠，导出内容错误
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#1438 fix: 出现 tooltip 后点击画布外面的空白区域可能抛出错误
  packages/s2-core/src/utils/tooltip.ts
Labels: pr(fix)

#1444 chore: 移除官网部署预览的工作流
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/preview-start.yml
Labels: pr(chore)

#1443 fix(tooltip): 修复行/列层级超过2级时选中数据统计错误
  .github/PULL_REQUEST_TEMPLATE.md
  packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/tooltip/components/summary.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(fix)

#1440 docs: 新增自定义单元格宽高文档和示例
  packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/select-event-spec.ts
  packages/s2-core/src/cell/index.ts
  packages/s2-core/src/cell/table-series-cell.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/get-all-child-cells.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/custom/cell-align.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.en.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/examples/layout/custom/demo/custom-pivot-size.ts
  s2-site/examples/layout/custom/demo/custom-table-size.ts
  s2-site/examples/layout/custom/demo/custom-tree-row-width.ts
  s2-site/examples/layout/custom/demo/hide-columns.ts
  s2-site/examples/layout/custom/demo/meta.json
  s2-site/examples/layout/custom/index.zh.md
Labels: pr(documentation)

#1425 fix: 解决父元素缩放时,自适应无法充满父元素bug
  packages/s2-shared/src/utils/resize.ts
Labels: pr(fix), 🙏 need test cases or docs

#1445 docs: 新增分页组件demo
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/pagination.en.md
  s2-site/docs/common/pagination.zh.md
  s2-site/docs/manual/basic/analysis/pagination.en.md
  s2-site/docs/manual/basic/analysis/pagination.zh.md
  s2-site/docs/manual/basic/analysis/vue.en.md
  s2-site/docs/manual/basic/analysis/vue.zh.md
  s2-site/docs/manual/introduction.en.md
  s2-site/examples/react-component/pagination/API.en.md
  s2-site/examples/react-component/pagination/API.zh.md
  s2-site/examples/react-component/pagination/demo/meta.json
  s2-site/examples/react-component/pagination/demo/pivot.tsx
  s2-site/examples/react-component/pagination/demo/table.tsx
  s2-site/examples/react-component/pagination/index.en.md
  s2-site/examples/react-component/pagination/index.zh.md
Labels: pr(documentation)

#1456 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1459 refactor: S2Options.hierarchyCollapse => S2Options.style.hierarchyCollapse
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-react/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-vue/playground/App.vue
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/style.zh.md
Labels: pr(refactor)

#1450 feat(strategy-sheet): 子弹图支持显示 Tooltip
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.module.less
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/kpi-columns/custom-bullet-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/utils/index.ts
  packages/s2-shared/src/constant/i18n/en_US.ts
  packages/s2-shared/src/constant/i18n/zh_CN.ts
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(feature)

#1460 fix: 修复相同配置字段导致程序出错, close #1427
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/utils/merge.ts
Labels: pr(fix)

#1461 fix(interaction): 修复禁用多选后, 未对行/列头生效
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/config.ts
  s2-site/docs/common/interaction.zh.md
Labels: pr(fix)

#1463 fix: 自定义 flatten 函数未考虑空值情况
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/src/utils/data-set-operate.ts
Labels: pr(fix)

#1464 chore: 更新国内镜像同步账号信息
  .github/workflows/mirror.yml
Labels: pr(chore)

#1466 chore: 🤖 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  s2-site/package.json
  s2-site/yarn.lock
Labels: pr(chore)

#1455 test: 补充自适应在父容器有缩放的情况下宽高获取错误的测试
  .github/PULL_REQUEST_TEMPLATE.md
  packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
  packages/s2-react/__tests__/unit/hooks/useResize-spec.ts
  packages/s2-shared/src/utils/resize.ts
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
Labels: pr(test)

#1472 fix: 构造含总计的 tree 行头布局时报错
  packages/s2-core/__tests__/unit/facet/layout/build-row-tree-hierarchy-spec.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
Labels: pr(fix)

#1465 fix: 修复柱状图区间及零点问题
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/condition/conditions-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/utils/condition/condition.ts
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/examples/analysis/conditions/demo/bidirectional-interval.ts
  s2-site/examples/analysis/conditions/demo/meta.json
Labels: pr(fix)

#1468 feat(interaction): 添加 onDataCellSelectMove 事件
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-shared/__tests__/utils/options-spec.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/hooks/useEvents.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(feature)

#1475 feat: 添加编辑场景文档
  s2-site/examples/case/data-preview/demo/excel.tsx
  s2-site/examples/case/data-preview/demo/meta.json
Labels: pr(feature)

#1470 fix(strategysheet): 修复趋势分析表多列头切换为单列头后, 隐藏列头功能失效
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/common/store/index.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-vue/src/hooks/useSheetUpdate.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: pr(fix)

#1476 chore: 将 s2-shared 的单测检测添加到 CI 运行中
  packages/s2-shared/package.json
Labels: pr(chore)

#1477 fix: 增加tooltip允许复制的样式防止被外部覆盖
  packages/s2-core/src/ui/tooltip/index.less
Labels: pr(fix)

#1478 feat(tooltip): 支持额外的样式和类名 & 修复内容过长 tooltip 展示不全的问题
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/common/constant/tooltip.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/ui/tooltip/index.less
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/tooltip.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(feature)

#1471 feat: s2-vue 添加下钻组件
  jest.config.base.js
  packages/s2-react/__tests__/__mocks__/svg.ts
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-react/package.json
  packages/s2-react/src/components/drill-down/index.tsx
  packages/s2-react/src/components/icons/index.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/utils/index.ts
  packages/s2-react/tsconfig.declaration.json
  packages/s2-react/tsconfig.json
  packages/s2-react/typings.d.ts
  packages/s2-react/vite.config.ts
  packages/s2-shared/src/constant/classnames.ts
  packages/s2-shared/src/constant/index.ts
  packages/s2-shared/src/icons/calendar-icon.svg
  packages/s2-shared/src/icons/col-icon.svg
  packages/s2-shared/src/icons/dot-icon.svg
  packages/s2-shared/src/icons/location-icon.svg
  packages/s2-shared/src/icons/row-icon.svg
  packages/s2-shared/src/icons/search-icon.svg
  packages/s2-shared/src/icons/sort-icon.svg
  packages/s2-shared/src/icons/switcher-icon.svg
  packages/s2-shared/src/icons/text-icon.svg
  packages/s2-shared/src/icons/value-icon.svg
  packages/s2-shared/src/index.ts
  packages/s2-shared/src/interface.ts
  packages/s2-shared/src/styles/drilldown.less
  packages/s2-shared/src/utils/drill-down.ts
  packages/s2-vue/package.json
  packages/s2-vue/playground/App.vue
  packages/s2-vue/src/components/drill-down/index.vue
  packages/s2-vue/src/components/sheets/pivot-sheet.vue
  packages/s2-vue/src/components/tooltip/custom-tooltip.ts
  packages/s2-vue/src/components/tooltip/index.vue
  packages/s2-vue/src/interface.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  packages/s2-vue/tsconfig.declaration.json
  packages/s2-vue/tsconfig.json
  packages/s2-vue/typings.d.ts
  packages/s2-vue/vite.config.ts
  yarn.lock
Labels: pr(feature)

#1479 fix: 趋势表自定义列头数值误用数据单元格样式
  packages/s2-core/src/utils/text.ts
  packages/s2-react/package.json
Labels: pr(fix)

#1482 feat: 明细表的 getCellData 可获取单行数据
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-react/playground/index.tsx
Labels: pr(feature)

#1483 feat(interaction): 增加行头单元格和全局单元格滚动事件及文档
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/events.ts
  packages/s2-core/src/common/interface/scroll.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/interaction/brush-selection.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/hooks/useEvents.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/scroll.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/case/data-preview/demo/excel.tsx
Labels: pr(feature)

#1484 feat: 支持绘制 mini 折线图
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/kpi-columns/custom-bullet-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(feature)

#1485 feat: 明细表趋势图透出点击透出整行数据
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-react/playground/config.ts
Labels: pr(feature)

#1486 fix: node 可能为null
  packages/s2-core/src/interaction/root.ts
Labels: pr(fix)

#1487 chore(release): 🔖@antv/s2@1.22.0 @antv/s2-react@1.19.1 @antv/s2-vue@1.1.0
  packages/s2-core/package.json
  packages/s2-react/package.json
  packages/s2-vue/package.json
Labels: pr(chore)

#1491 refactor: 将cell中所有的private改为protected，便于继承定制
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
Labels: pr(refactor)

#1494 docs: totalData 类型文案修正
  s2-site/docs/api/general/S2DataConfig.zh.md
Labels: pr(documentation)

#1492 chore(ci): 合并 changelog 时加上 --squash 将 commit 合并成一个
  .github/workflows/sync-site-lock-changelog-with-pr.yml
Labels: pr(chore)

#1495 docs: 修改透视表文档
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
Labels: pr(documentation)

#1490 docs: 更新浏览器引入 demo 链接
  s2-site/docs/common/browser.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/getting-started.zh.md
Labels: pr(documentation)

#1493 chore: 更新 lock 和 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore)

#1496 fix(interaction): 修复按下快捷选中按钮之后通过触摸板切换页面，快捷键状态没有reset的问题
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/interaction/base-event.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/root.ts
Labels: pr(fix)

#1497 chore(ci): 每次 push 代码时取消上一次未执行完的 CI, 避免排队
  .github/workflows/lint.yml
  .github/workflows/test.yml
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
Labels: pr(chore)

#1498 fix(interaction): 修复链接跳转会触发单选和 Tooltip 显示的问题
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-text-click-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/interaction/base-event.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/interaction/formatter.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1504 fix: 修复 pivot 无法获取整行数据，而报错的问题
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
Labels: pr(fix)

#1508 docs: 编辑场景 超出容器 编辑框消失
  s2-site/examples/case/data-preview/demo/excel.tsx
Labels: pr(documentation)
