Repository antvis/S2, pull requests merged in 2022-01, with the labels that each got.

#964 fix: 自定义目录树切换优化
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(fix), 🚨 test failed

#959 refactor: 合并单元格在绘制时使用增量更新。
  packages/s2-core/__tests__/unit/utils/merge-cell.spec.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
Labels: pr(refactor)

#966 fix: 修改 s2-react 错误的 peerDependencies close #963
  packages/s2-react/package.json
Labels: pr(fix), 🚨 test failed

#967 feat(interaction): 支持通过键盘方向键移动选中的单元格
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#961 修复下钻行总计单元格数据错误
  packages/s2-core/__tests__/data/mock-drill-down-dataset.json
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
Labels: 🚨 test failed

#970 fix: 修复自定义树取值路径错误问题
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#968 fix: 优化复制功能，解决大数据量复制导致的页面崩溃问题
  packages/s2-core/src/utils/export/index.ts
Labels: pr(fix)

#971 chore(react): fix lint
  packages/s2-react/src/components/export/index.tsx
Labels: pr(chore)

#974 fix: 修复点击非表格区域报错
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#975 fix(facet): frozenRowHeader=false滚动时列头展示不全
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
Labels: pr(fix)

#973 feat: 字段标记(filed)可使用正则进行匹配
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/interface/condition.ts
  s2-site/docs/common/conditions.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
  s2-site/examples/analysis/conditions/demo/table-text.ts
Labels: pr(feature)

#976 fix(export): 优化复制数据到剪贴板的逻辑
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/src/components/export/index.tsx
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/common/conditions.en.md
  s2-site/docs/common/export.en.md
  s2-site/docs/common/export.zh.md
  s2-site/docs/manual/basic/analysis/export.zh.md
Labels: pr(fix)

#978 docs: ✨ 增加布局相关demo
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/style.en.md
  s2-site/docs/common/style.zh.md
  s2-site/examples/layout/basic/API.en.md
  s2-site/examples/layout/basic/API.zh.md
  s2-site/examples/layout/basic/demo/colAdaptive.ts
  s2-site/examples/layout/basic/demo/compact.ts
  s2-site/examples/layout/basic/demo/meta.json
  s2-site/examples/layout/basic/index.en.md
  s2-site/examples/layout/basic/index.zh.md
  s2-site/examples/layout/custom/API.en.md
  s2-site/examples/layout/custom/API.zh.md
  s2-site/examples/layout/custom/demo/custom-height.ts
  s2-site/examples/layout/custom/demo/custom-width.ts
  s2-site/examples/layout/custom/demo/meta.json
  s2-site/examples/layout/custom/index.en.md
  s2-site/examples/layout/custom/index.zh.md
  s2-site/gatsby-config.js
Labels: pr(documentation)

#982 docs: correct brush event
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(documentation)

#979 refactor(facet): 在锁行时使用列头内部的clip实现列头滚动
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/col.ts
Labels: pr(refactor)

#983 fix(react): 修复 s2-react 无法安装到 alpha 版本 s2 的问题
  packages/s2-react/package.json
Labels: pr(fix)

#981 fix(interaction): shift区间多选在明细表序列号上失效
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/interaction/shift-multi-selection.ts
Labels: pr(fix)

#984 fix(s2-react): 修复 hierarchyType 切换导致的渲染问题
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(fix)

#986 fix: 修复多指标情况下自定义树展示不全的问题
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-react/src/hooks/useEvents.ts
Labels: pr(fix), 🚨 test failed

#989 fix(facet): 数据量较少时，维持 panelBBox 宽高
  packages/s2-core/__tests__/unit/facet/bbox/panelBBox-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/baseBBox.ts
  packages/s2-core/src/facet/bbox/panelBBox.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#990 feat: 增加supportCSSTransform设置
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(feature)

#992 docs: 优化部分文档, 增加部分 faq
  .github/workflows/issue-labeled.yml
  .github/workflows/release-notify.yml
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/docs/manual/faq.zh.md
Labels: pr(documentation)

#993 chore: 增加组内不排序icon
  packages/s2-core/src/common/icons/svg/index.ts
  packages/s2-core/src/common/icons/svg/svgs.ts
Labels: pr(chore)

#995 fix: :bug: 修复多指标渲染空值问题
  packages/s2-core/src/utils/text.ts
Labels: pr(fix), 🚨 test failed

#996 fix: 列宽计算适配多指标情况
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/grid-analysis-data.ts
Labels: pr(fix), 🚨 test failed

#997 feat(facet): add scrollBarPosition option
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  s2-site/docs/common/interaction.zh.md
Labels: pr(feature)

#972 fix(facet): 交叉表 compact 模式下行/列头宽度计算错误
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix), 🚨 test failed

#1001 fix(facet): 移动 ScrollbarPositionType 枚举位置
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), 🚨 test failed

#1002 test(scroll): 修复 layout变化后导致的断言错误
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
Labels: pr(test)

#1003 chore(release): @antv/s2@1.6.0 @antv/s2-react@1.6.0
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1007 fix: 修复高度自适应死循环问题
  packages/s2-react/src/hooks/useResize.ts
Labels: pr(fix)

#1010 fix: 加载下钻数据引起render死循环
  packages/s2-react/package.json
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  yarn.lock
Labels: pr(fix), 🚨 test failed

#1019 feat: node增加节点信息参数便于透传额外业务信息
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/node.ts
Labels: pr(feature), 🚨 test failed

#1015 fix: 下钻参数变更后未正确重置
  packages/s2-react/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/utils/drill-down.ts
Labels: pr(fix), 🚨 test failed

#1023 fix(drilldown): 修复clearDrillDown下钻清除错误及重渲逻辑
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  s2-site/docs/api/components/drill-down.zh.md
Labels: pr(fix)

#1025 docs: 修复文档404链接和报错demo
  s2-site/docs/manual/advanced/custom/hook.zh.md
  s2-site/examples/react-component/drill-dwon/demo/basic-panel.tsx
  s2-site/examples/react-component/drill-dwon/demo/for-pivot.tsx
  s2-site/examples/react-component/drill-dwon/demo/meta.json
Labels: pr(documentation)

#1024 fix(strategy-sheet): 修复衍生指标颜色,图标显示不正确 & tooltip 不显示指标名
  package.json
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.json
  packages/s2-react/__tests__/unit/utils/__snapshots__/build-table-hierarchy-spec.tsx.snap
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.module.less
Labels: pr(fix), 🚨 test failed

#1027 chore(ci): 新增 prerelease 推送 & CI 细节调整
  .github/workflows/lint.yml
  .github/workflows/pr-notify.yml
  .github/workflows/prerelease-notify.yml
  .github/workflows/release-notify.yml
  .github/workflows/sync-site-lock-changelog-with-pr.yml
  .github/workflows/test.yml
Labels: pr(chore)

#1030 fix: 自定义目录树增加layoutHierarchy的hook修复层级问题
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#1031 fix(facet): scroll speed options & pagination totals
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
Labels: pr(fix)

#1033 fix(s2-core): 修复延迟销毁表格时没有移除canvas节点的问题 close #1011
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(fix)

#1035 docs: 增加小册子demo《哲学家的观点》
  s2-site/examples/case/comparison/demo/meta.json
  s2-site/examples/case/comparison/demo/philosophers.tsx
Labels: pr(documentation)

#1034 fix(tooltip): 修复单元格文字过长时 tooltip 显示被截断 close #1028
  packages/s2-core/src/ui/tooltip/index.less
  packages/s2-react/src/components/tooltip/components/simple-tips.tsx
  packages/s2-react/src/components/tooltip/components/summary.tsx
  packages/s2-react/src/components/tooltip/index.less
Labels: pr(fix)

#921 feat: 支持配置前端计算小计/总计
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-total-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/__tests__/unit/utils/number-calculate-spec.ts
  packages/s2-core/__tests__/util/index.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/number-calculate.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/analysis/totals/demo/calculate.ts
  s2-site/examples/analysis/totals/demo/custom.ts
  s2-site/examples/analysis/totals/demo/meta.json
Labels: pr(feature)

#1036 fix(tooltip): 修复明细表列头的 tooltip 内容被错误的格式化 close #998
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#1013 fix(interactive): table move problem
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
Labels: pr(fix)

#1038 docs: 优化demo《哲学家的观点》
  s2-site/examples/case/comparison/demo/philosophers.tsx
Labels: pr(documentation)

#1037 feat: 完善交叉表分页功能
  package.json
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/facet.ts
  packages/s2-react/package.json
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  yarn.lock
Labels: pr(feature)

#1040 fix(facet): 序号列应早于列头添加到group
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#1039 chore(release): @antv/s2@1.7.0 @antv/s2-react@1.7.0
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1041 chore: Revert release commit @antv/s2@1.7.0 @antv/s2-react@1.7.0 (#1039)
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1046 chore(release): @antv/s2@1.7.0 @antv/s2-react@1.6.1
  packages/s2-core/package.json
  packages/s2-react/package.json
Labels: pr(chore)

#1048 fix(interaction): table 模式下的序列号兼容
  packages/s2-core/src/interaction/selected-cell-move.ts
Labels: pr(fix)

#1049 feat: 趋势分析表列头支持多文本展示
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.json
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-col-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(feature), 🚨 test failed

#1052 fix(strategy-sheet): 修复自定义树布局模式下, 获取不到字段描述
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-col-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/interface.ts
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix)

#1054 feat: 支持自定义设备像素比
  packages/s2-core/__tests__/setup.js
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/__tests__/unit/utils/merge.spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-react/__tests__/unit/utils/options-spec.ts
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/advanced/hd-adapter.zh.md
Labels: pr(feature)

#1053 fix: 透视表无序未按原顺序展示问题
  packages/s2-core/__tests__/unit/dataset/pivot-dataset-spec.ts
  packages/s2-core/src/utils/sort-action.ts
Labels: pr(fix)
