Repository antvis/S2, pull requests merged in 2023-11, with the labels that each got.

#2399 fix: 修复趋势分析表自定义列头 tooltip 后错误的使用行头的 tooltip
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
Labels: pr(fix)

#2401 feat: 支持透视表明细表单元格虚线&分割线虚线(#2400)
  CONTRIBUTING.md
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/group/grid-group.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/cell/cell.ts
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(feature)

#2407 docs: 补充缺失的 fontStyle 和 fontVariant 文档
  packages/s2-core/src/common/interface/theme.ts
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/api/graphic.zh.md
  s2-site/examples/custom/custom-cell/demo/data-cell-placeholder.ts
  s2-site/examples/custom/custom-cell/demo/meta.json
Labels: pr(documentation), 🚨 test failed

#2408 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore), 🚨 test failed

#2411 fix(interaction): 修复行列头圈选后滑出可视范围后, 错误的选择了数值单元格 close #2340
  packages/s2-core/__tests__/bugs/issue-2340-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/root.ts
Labels: pr(fix)

#2410 fix(copy): 修复刷选复制行列头时, 数值单元格未格式化 & 存在省略号时未复制原始值
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-react/playground/config.ts
  s2-site/docs/common/export.zh.md
  s2-site/docs/manual/basic/analysis/copy-export.zh.md
Labels: pr(fix)

#2412 fix: 修复交叉模式下 行序号位置不正确&总计行未添加行序号
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/layout/node.ts
Labels: pr(fix), 👀 need more info

#2415 refactor: 抽取明细表冻结行列逻辑，交叉表冻结首行逻辑复用
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/header/col.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(refactor)

#2417 fix: 修复隐藏列总计时行总计也被隐藏问题
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/src/facet/layout/layout-hooks.ts
Labels: pr(fix)

#2422 chore: update dumi-theme-antv 0.4.0
  s2-site/.dumirc.ts
  s2-site/package.json
Labels: pr(chore)

#2425 docs: buttons unify and image position
  s2-site/.dumirc.ts
Labels: pr(documentation)

#2426 docs: image position change
  s2-site/.dumirc.ts
Labels: pr(documentation), 🚨 test failed

#2427 docs: 更新官网主题
  .github/workflows/pr-auto-assign-reviewer.yml
  s2-site/package.json
Labels: pr(documentation), 🚨 test failed

#2428 docs: 更新官网新闻公告
  LICENSE
  s2-site/.dumirc.ts
  s2-site/package.json
Labels: pr(documentation)

#2423 feat: 支持自定义 G 5.0 插件和配置
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/spreadsheet/custom-cell-style-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-react/CHANGELOG.md
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
  packages/s2-react/package.json
  packages/s2-react/playground/components/Plugins.tsx
  packages/s2-react/playground/config.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-shared/__tests__/utils/options-spec.ts
  pnpm-lock.yaml
  s2-site/docs/api/general/S2Options.en.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/advanced/hd-adapter.zh.md
  s2-site/docs/manual/faq.en.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/custom/custom-plugins/API.en.md
  s2-site/examples/custom/custom-plugins/API.zh.md
  s2-site/examples/custom/custom-plugins/demo/custom-plugins.ts
  s2-site/examples/custom/custom-plugins/demo/meta.json
  s2-site/examples/custom/custom-plugins/index.en.md
  s2-site/examples/custom/custom-plugins/index.zh.md
  s2-site/package.json
Labels: pr(feature), next

#2432 fix: 修复 React 18 StrictMode 同时挂载两个表格的问题
  package.json
  packages/s2-react/__tests__/spreadsheet/spread-sheet-spec.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useSpreadSheet.ts
Labels: pr(fix), next

#2436 fix: 修复维度缺失部分维值时, 行维值以及对应的数值展示错误
  packages/s2-core/__tests__/spreadsheet/miss-dimension-values-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)
