Repository antvis/S2, pull requests merged in 2023-09, with the labels that each got.

#2338 feat: 小计/总计功能，支持按维度分组汇总 #2337
  packages/s2-core/__tests__/bugs/issue-1715-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/spreadsheet/sort-by-order-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/data-set/__snapshots__/pivot-data-set-total-spec.ts.snap
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/README-adjustTotalNodesCoordinate.md
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/interface.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/layout/total-class.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/facet.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/layout/get-dims-condition-by-node.ts
  packages/s2-core/src/utils/layout/whether-leaf-by-level.ts
  s2-site/docs/api/basic-class/node.en.md
  s2-site/docs/api/basic-class/node.zh.md
  s2-site/docs/common/totals.en.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/analysis/totals/demo/dimension-group-col.ts
  s2-site/examples/analysis/totals/demo/dimension-group-row.ts
  s2-site/examples/analysis/totals/demo/meta.json
Labels: pr(feature)

#2339 feat: 趋势分析表无波动的字体不用红绿色显示
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
Labels: pr(feature)

#2325 fix: 优化 handleDimensionValueFilter 复杂度
  packages/s2-core/src/data-set/table-data-set.ts
Labels: pr(fix)

#2332 feat: 交叉表行头叶子节点支持斑马纹风格
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
Labels: pr(feature)

#2343 test: 更新 React 包单测快照
  packages/s2-react/__tests__/unit/utils/__snapshots__/build-table-hierarchy-spec.tsx.snap
Labels: pr(test)

#2323 fix(table-facet): 修复过滤多列时，删除一列过滤将同时清空后续过滤列
  packages/s2-core/__tests__/bugs/issue-2322-spec.ts
  packages/s2-core/__tests__/data/data-issue-2322.json
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#2344 docs: 完善交互主题配置
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/interaction/basic/demo/hover.ts
  s2-site/examples/interaction/basic/demo/meta.json
  s2-site/examples/interaction/basic/demo/state-theme.ts
Labels: pr(documentation)

#2345 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2351 feat: 对比值无波动时也显示灰色
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
Labels: pr(feature)

#2353 fix: 修复树状模式下总计节点的指标节点没有被格式化数据
  packages/s2-core/src/cell/header-cell.ts
Labels: pr(fix)

#2346 feat: 小计/总计功能，支持按维度分组汇总
  packages/s2-core/__tests__/bugs/issue-1715-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/spreadsheet/sort-by-order-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/data-set/__snapshots__/pivot-data-set-total-spec.ts.snap
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/unit/utils/facet-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/README-adjustTotalNodesCoordinate.md
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/interface.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/layout/total-class.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/facet.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/layout/get-dims-condition-by-node.ts
  packages/s2-core/src/utils/layout/whether-leaf-by-level.ts
  packages/s2-react/__tests__/unit/utils/__snapshots__/build-table-hierarchy-spec.tsx.snap
  s2-site/docs/api/basic-class/node.en.md
  s2-site/docs/api/basic-class/node.zh.md
  s2-site/docs/common/totals.en.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/analysis/totals/demo/dimension-group-col.ts
  s2-site/examples/analysis/totals/demo/dimension-group-row.ts
  s2-site/examples/analysis/totals/demo/meta.json
Labels: pr(feature)

#2356 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)
