Repository antvis/S2, pull requests merged in 2023-06, with the labels that each got.

#2224 fix(interaction): 修复列头隐藏后展开 icon 显示异常 close #2194
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
  packages/s2-core/__tests__/spreadsheet/sort-by-order-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-tree-mode-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/resize-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: pr(fix)

#2130 feat: 增加暗黑主题
  .stylelintrc
  jest.config.base.js
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/rollup.config.js
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/styles/theme/dark.less
  packages/s2-core/src/styles/variables.less
  packages/s2-core/src/theme/palette/dark.ts
  packages/s2-core/src/ui/tooltip/index.less
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/inject-css-text.ts
  packages/s2-core/src/utils/theme.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/advanced-sort/index.less
  packages/s2-react/src/components/header/index.less
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.less
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
  packages/s2-react/src/components/switcher/dimension/index.less
  packages/s2-react/src/components/switcher/index.less
  packages/s2-react/src/components/switcher/index.tsx
  packages/s2-react/src/components/switcher/item/index.less
  packages/s2-react/src/components/tooltip/style.less
  packages/s2-react/vite.config.ts
  packages/s2-shared/src/constant/theme.ts
  packages/s2-shared/src/index.ts
  packages/s2-shared/src/styles/drill-down.less
  packages/s2-shared/src/styles/theme/dark.less
  packages/s2-shared/src/styles/tooltip/index.less
  packages/s2-shared/src/styles/tooltip/operator.less
  packages/s2-shared/src/styles/variables.less
  packages/s2-shared/src/utils/drill-down.ts
  packages/s2-shared/src/utils/theme.ts
  pnpm-lock.yaml
  s2-site/examples/react-component/sheet/demo/strategy.tsx
Labels: pr(feature), next

#2235 feat: trigger hover after scroll
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/interaction.en.md
  s2-site/docs/common/interaction.zh.md
  s2-site/examples/interaction/basic/demo/hover-after-scroll.ts
  s2-site/examples/interaction/basic/demo/meta.json
Labels: pr(feature)

#2238 fix(react): correct showPagination type
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/interface.ts
  packages/s2-shared/src/interface.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/basic/analysis/pagination.en.md
  s2-site/docs/manual/basic/analysis/pagination.zh.md
  s2-site/examples/react-component/pagination/demo/table.tsx
Labels: pr(fix)

#2226 feat: support separate config of `hoverHighlight`
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/interaction.en.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/examples/interaction/basic/demo/hover.ts
Labels: pr(feature)

#2241 fix: 修复导出数据分隔符有误的问题
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
Labels: pr(fix), next

#2245 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2248 docs: update DATA_CELL_SELECT_MOVE event
  s2-site/docs/api/general/S2Event.en.md
  s2-site/docs/api/general/S2Event.zh.md
Labels: pr(documentation)

#2254 fix: use actualText replace value label in copy
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)
