Repository antvis/S2, pull requests merged in 2023-01, with the labels that each got.

#2024 fix: 修复单元格宽高为0时的无意义渲染
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#2029 docs: 替换antgroup主站
  s2-site/.dumirc.ts
Labels: pr(documentation)

#2028 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2032 refactor: rowCells 重命名为 currentRow，避免与行头 rowCell 定义冲突
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-react/playground/index.tsx
Labels: pr(refactor)

#2027 chore: 使用 pnpm 作为包管理器
  .github/workflows/auto-release.yml
  .github/workflows/compressed-size.yml
  .github/workflows/lint.yml
  .github/workflows/release-success.yml
  .github/workflows/test.yml
  .husky/pre-push
  .npmrc
  .yarnrc
  README.en-US.md
  README.md
  lerna.json
  package.json
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/package.json
  packages/s2-react/__tests__/spreadsheet/__snapshots__/pagination-spec.tsx.snap
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-react/__tests__/unit/components/pagination/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
  packages/s2-react/package.json
  packages/s2-shared/package.json
  packages/s2-vue/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  s2-site/docs/common/development.en.md
  s2-site/docs/common/development.zh.md
  s2-site/docs/manual/contribution.en.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/package.json
  scripts/bump-version.js
  scripts/validate-deps.js
  yarn.lock
Labels: pr(chore), next

#2048 chore: 增加 issue 格式检测 & 讨论区通知 action
  .github/workflows/disscustion.yml
  .github/workflows/issue-opend.yml
  .github/workflows/pr-auto-assign-reviewer.yml
  .github/workflows/pr-auto-set-next-label.yml
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(chore)

#2044 feat: tooltip summaries 返回原始数据
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/src/components/tooltip/components/summary.tsx
Labels: pr(feature)

#2033 feat: playground 支持导入 JSON 数据
  s2-site/.dumi/pages/playground.zh.tsx
  s2-site/playground/config-panel/config-component/dragger-upload/index.less
  s2-site/playground/config-panel/config-component/dragger-upload/index.tsx
  s2-site/playground/config-panel/config-component/radio/index.tsx
  s2-site/playground/config-panel/config-component/select/index.tsx
  s2-site/playground/config-panel/config-token/index.ts
  s2-site/playground/layouts/index.less
  s2-site/playground/sheet-component/index.less
  s2-site/playground/sheet-component/index.tsx
Labels: pr(feature)

#2041 fix(layout): 修复树状模式下无列头时行头对应的角头不显示
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/src/facet/header/corner.ts
Labels: pr(fix)

#2051 fix(layout): 修复存在多列头多数值且数值置于行头时,列总计单元格高度不对 close #1715 #2049
  packages/s2-core/__tests__/bugs/issue-1715-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-react/playground/config.ts
Labels: pr(fix)

#2038 fix(interaction): 修复自定义列头时无法调整第一列的叶子节点高度 close #1979
  packages/s2-core/__tests__/data/custom-grid-fields.ts
  packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-react/__tests__/bugs/issue-652-spec.tsx
  packages/s2-react/__tests__/setup.js
  packages/s2-react/__tests__/spreadsheet/tooltip-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
  packages/s2-react/playground/components/CustomGrid.tsx
  packages/s2-react/playground/components/ResizeConfig.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/playground/utils.ts
Labels: pr(fix), next

#2052 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2045 chore: 移除所有 @deprecated 标记 api
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/corner-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/style.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
  packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
  packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-react/__tests__/spreadsheet/pressure-test-spec.tsx
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/index-spec.tsx
  packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/header/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-shared/__tests__/utils/options-spec.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/hooks/useEvents.ts
  packages/s2-vue/src/hooks/useSpreadSheet.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  pnpm-lock.yaml
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.en.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/common/custom/headerActionIcons.en.md
  s2-site/docs/common/custom/headerActionIcons.zh.md
  s2-site/docs/common/header-action-icon.en.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-order.en.md
  s2-site/docs/manual/advanced/custom/custom-order.zh.md
  s2-site/docs/manual/advanced/get-instance.en.md
  s2-site/docs/manual/advanced/get-instance.zh.md
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
  s2-site/examples/custom/custom-order/demo/custom-order.tsx
Labels: pr(chore), next

#2055 chore: 开启 noPropertyAccessFromIndexSignature 配置
  .eslintrc.js
  packages/s2-core/__tests__/bugs/issue-1668-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-tree-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-totals-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/layout-hooks-spec.tsx
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-vue/src/components/sheets/index.vue
  packages/s2-vue/src/components/sheets/pivot-sheet.vue
  tsconfig.base.json
Labels: pr(chore)
