Repository antvis/S2, pull requests merged in 2023-10, with the labels that each got.

#2360 fix(layout): 修复隐藏结点时对父节点的布局计算错误 close #2355
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
Labels: pr(fix)

#2363 docs: 修复 headerActionIcons 错误文档 close #2362
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/common/icon.zh.md
Labels: pr(documentation)

#2357 fix(table-sheet): 明细表数据为空时错误的展示一行空数据 close #2255
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  s2-site/docs/api/basic-class/base-data-set.zh.md
Labels: pr(fix)

#2364 fix: 列头绘制多列文本时错误的使用了数值单元格的样式 close #2359
  packages/s2-core/__tests__/bugs/issue-2359-spec.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(fix)

#2369 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2370 fix: 修复分组汇总时，按汇总排序获取排序数据为空
  packages/s2-core/__tests__/unit/utils/__snapshots__/sort-action-spec.tsx.snap
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/utils/sort-action.ts
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
Labels: pr(fix)

#2378 chore: 同步 master 到 alpha
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/bugs/issue-2359-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/sort-action-spec.tsx.snap
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/package.json
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/layout/build-gird-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/interface.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/layout/total-class.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/sort-action.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-shared/package.json
  packages/s2-vue/package.json
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/common/icon.zh.md
  s2-site/docs/common/totals.en.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/analysis/totals/demo/dimension-group-col.ts
  s2-site/examples/analysis/totals/demo/dimension-group-row.ts
Labels: pr(chore)

#2390 fix: 修复树状角头，当有存在icon时，内容与box宽度恰好相等，出现换行 close #2389
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/spread-sheet-tree-mode-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#2392 fix(layout): 修复在紧凑模式列头宽度未按文本自适应 close #2385
  packages/s2-core/__tests__/bugs/issue-2385-spec.ts
  packages/s2-core/__tests__/data/data-issue-2385.json
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-react/__tests__/data/mock-dataset.json
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/style.zh.md
Labels: pr(fix)

#2393 chore: 不按 issue 模版提交自动关闭
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-opend.yml
Labels: pr(chore)

#2394 docs: 新增自定义明细表单元格 & 自定义 mini 图文档
  s2-site/docs/manual/advanced/custom/hook.zh.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/examples/case/art/demo/lost-text.tsx
  s2-site/examples/case/art/demo/meta.json
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
  s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
  s2-site/examples/custom/custom-cell/demo/custom-table-cell.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/meta.json
  s2-site/examples/custom/custom-cell/demo/mini-chart.ts
  s2-site/examples/custom/custom-cell/demo/totals-cell.ts
  s2-site/examples/custom/custom-layout/demo/custom-coordinate.ts
  s2-site/examples/custom/custom-layout/demo/custom-data-position.ts
  s2-site/examples/custom/custom-layout/demo/custom-layout-arrange.ts
  s2-site/examples/custom/custom-layout/demo/custom-layout-hierarchy.ts
  s2-site/examples/custom/custom-layout/demo/custom-value-order.ts
  s2-site/examples/react-component/sheet/demo/strategy-mini-chart.tsx
Labels: pr(documentation)

#2395 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2375 refactor: 小计/总计配置重构
  packages/s2-core/__tests__/bugs/issue-1668-spec.ts
  packages/s2-core/__tests__/bugs/issue-1715-spec.ts
  packages/s2-core/__tests__/bugs/issue-2164-spec.ts
  packages/s2-core/__tests__/bugs/issue-368-spec.ts
  packages/s2-core/__tests__/bugs/issue-372-spec.ts
  packages/s2-core/__tests__/bugs/issue-836-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-facet-layout-api-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.tsx
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/layout/add-totals.ts
  packages/s2-react/__tests__/bugs/issue-522-spec.tsx
  packages/s2-react/__tests__/spreadsheet/data-accuracy-one-measure-spec.tsx
  packages/s2-react/__tests__/spreadsheet/data-accuracy-two-measures-spec.tsx
  packages/s2-react/__tests__/spreadsheet/pressure-test-spec.tsx
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/totals.en.md
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/analysis/sort/demo/custom-totals.ts
  s2-site/examples/analysis/totals/demo/basic.ts
  s2-site/examples/analysis/totals/demo/calculate.ts
  s2-site/examples/analysis/totals/demo/custom.ts
  s2-site/examples/analysis/totals/demo/multiple-values.ts
  s2-site/examples/analysis/totals/demo/tree.ts
  s2-site/playground/sheet-component/index.tsx
Labels: pr(refactor), next
