Repository antvis/S2, pull requests merged in 2023-05, with the labels that each got.

#2186 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2180 fix: 修复 meta name 同名时，hoverFocus 出错的问题
  packages/s2-core/__tests__/bugs/issue-1781-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix), next

#2191 fix: 系统拦截快捷键后多选交互异常
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/utils/interaction/select-event.ts
Labels: pr(fix)

#2187 fix: 修复 meta name 同名时，hoverFocus 出错的问题
  packages/s2-core/__tests__/bugs/issue-1781-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix)

#2201 feat: 同步复制支持自定义transformer
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/export/copy/index.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/export/interface.ts
  packages/s2-react/src/components/export/index.tsx
  packages/s2-react/src/components/export/strategy-copy.ts
  s2-site/docs/common/export.zh.md
  s2-site/docs/common/interaction.zh.md
Labels: pr(feature), next

#2208 docs: 更新自定义datacell示例
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
Labels: pr(documentation)

#2207 feat: 行列头和数值为空时，不渲染表格框架
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/utils.ts
Labels: pr(feature)

#2209 fix: 修复总计小计被意外 format 的问题
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/src/cell/header-cell.ts
Labels: pr(fix)

#2206 fix(core): only do compatibility of shift + scroll on Windows
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#2213 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2212 fix(core): can not set field height or width when the field name is surrounded by square brackets
  packages/s2-core/__tests__/bugs/issue-2195-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
  s2-site/docs/common/style.en.md
  s2-site/docs/common/style.zh.md
Labels: pr(fix)

#2200 fix: 明细表存在横向滚动条时多列头文本不居中 close #2199
  packages/s2-core/__tests__/bugs/issue-2199-spec.ts
  packages/s2-core/__tests__/data/data-issue-2199.json
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
Labels: pr(fix)

#2216 feat: 在行列头配置为空时，趋势分析表和customTree 模式不渲染框架
  packages/s2-core/__tests__/unit/data-set/custom-tree-data-set-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
Labels: pr(feature)

#2210 fix(core): can reset tooltip.renderTooltip in setOptions
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#2219 fix: 修复树状模式下，总计小计格式化问题
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
Labels: pr(fix)

#2227 fix: 修复 dataCell linkField 不能点击的问题
  packages/s2-core/__tests__/spreadsheet/data-link-spec.ts
  packages/s2-core/src/cell/data-cell.ts
Labels: pr(fix)

#2221 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2228 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2211 fix(core): highlight the column header cell and row header when data cell clicked
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.en.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(fix)

#2161 feat: 行列头兼容 condition icon 和 action icons
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/interaction/selected-cell-move-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/table-col-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/text-scrolling-spec.ts
  packages/s2-core/__tests__/unit/utils/condition/conditions-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/common/interface/util.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/cell/header-cell.ts
  packages/s2-core/src/utils/cell/table-col-cell.ts
  packages/s2-core/src/utils/cell/text-scrolling.ts
  packages/s2-core/src/utils/condition/condition.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
  packages/s2-react/__tests__/spreadsheet/multiple-values-cell-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-shared/src/utils/drill-down.ts
  pnpm-lock.yaml
  s2-site/docs/common/custom/headerActionIcons.zh.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.en.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-order.en.md
  s2-site/docs/manual/advanced/custom/custom-order.zh.md
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
  s2-site/examples/custom/custom-icon/demo/custom-svg-icon.ts
  s2-site/examples/custom/custom-order/demo/custom-order.tsx
Labels: pr(feature), next

#2234 docs: type InteractionStateTheme
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(documentation)
