Repository antvis/S2, pull requests merged in 2023-02, with the labels that each got.

#2053 refactor: 移除 g5.0 todo 项
  packages/s2-core/__tests__/spreadsheet/row-link-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/engine/CustomText.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/base.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/interaction/common.ts
Labels: pr(refactor), next

#2065 fix: 自定义 svg 支持无后缀的在线链接
  packages/s2-core/__tests__/unit/common/icons/__snapshots__/gui-icon-spec.ts.snap
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/src/common/icons/gui-icon.ts
Labels: pr(fix)

#2057 refactor: 重构复制代码，删除重复功能代码片段，修复bug
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/common/constant/copy.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/export/copy/index.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/pivot-header-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/export-worker.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/export/interface.ts
  packages/s2-core/src/utils/export/method.ts
Labels: pr(refactor), next

#2074 fix: 修复 2k 显示器切换到 MacBook 后表格渲染模糊 close #2072
  packages/s2-core/__tests__/bugs/issue-1191-spec.ts
  packages/s2-core/__tests__/bugs/issue-1624-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
Labels: pr(fix)

#2076 docs: update FAQ link error
  s2-site/docs/manual/faq.zh.md
Labels: pr(documentation)

#2069 feat: 增加自定义行头最大固定宽度的功能
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/facet/bbox/cornerBBox-spec.ts
  packages/s2-core/__tests__/unit/facet/bbox/panelBBox-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/bbox/cornerBBox.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/common/frozen.en.md
  s2-site/docs/common/frozen.zh.md
  s2-site/examples/case/comparison/demo/time-spend.tsx
Labels: pr(feature), next

#2082 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2084 docs: 修复行列冻结demo
  s2-site/examples/interaction/basic/demo/frozen.ts
Labels: pr(documentation)

#2085 docs: 更新主题章节文档
  s2-site/docs/manual/basic/theme.zh.md
Labels: pr(documentation)

#2086 chore: 合并master变更
  .github/workflows/disscustion.yml
  .github/workflows/issue-opend.yml
  .github/workflows/pr-auto-assign-reviewer.yml
  .github/workflows/pr-auto-set-next-label.yml
  packages/s2-core/CHANGELOG.md
  packages/s2-core/__tests__/bugs/issue-1191-spec.ts
  packages/s2-core/__tests__/bugs/issue-1715-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/__tests__/unit/facet/bbox/cornerBBox-spec.ts
  packages/s2-core/__tests__/unit/facet/header/corner-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/ui/hd-adapter/index-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/CHANGELOG.md
  packages/s2-react/__tests__/unit/components/tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/src/components/tooltip/components/summary.tsx
  packages/s2-vue/CHANGELOG.md
  s2-site/.dumi/pages/playground.zh.tsx
  s2-site/.dumirc.ts
  s2-site/docs/api/basic-class/node.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/interaction/advanced/demo/pivot-hide-columns.ts
  s2-site/playground/config-panel/config-component/dragger-upload/index.less
  s2-site/playground/config-panel/config-component/dragger-upload/index.tsx
  s2-site/playground/config-panel/config-component/radio/index.tsx
  s2-site/playground/config-panel/config-component/select/index.tsx
  s2-site/playground/config-panel/config-token/index.ts
  s2-site/playground/layouts/index.less
  s2-site/playground/sheet-component/index.less
  s2-site/playground/sheet-component/index.tsx
Labels: pr(chore)

#2090 feat: 复制支持自定义transformer
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(feature)

#2097 docs: 复制文档优化，添加自定义transformer描述
  s2-site/docs/common/export.zh.md
Labels: pr(documentation)

#2081 feat(interaction): 点击角头后支持选中所对应那一列的行头 close #2073
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/common/custom-tooltip.zh.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
Labels: pr(feature)

#2087 feat(interaction): 行头支持滚动刷选
  .github/workflows/pr-auto-assign-reviewer.yml
  packages/s2-core/__tests__/bugs/issue-720-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/scroll.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/base.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/facet.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/base-facet.en.md
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.en.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/examples/interaction/advanced/demo/scroll-to-cell.ts
Labels: pr(feature)

#2098 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)
