Repository antvis/S2, pull requests merged in 2023-08, with the labels that each got.

#2278 fix: 修复复制整行时错位
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#2301 feat: headerActionIcons 支持细粒度配置 & 修复异步渲染导致无法获取实例的问题
  packages/s2-core/__tests__/spreadsheet/header-action-icons-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/utils/cell/header-cell.ts
  packages/s2-react/__tests__/unit/components/drill-down/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/mobile-tooltip-spec.tsx
  packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/drill-down/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  packages/s2-react/src/components/sheets/chart-sheet/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-react/src/components/sheets/mobile-sheet/index.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  packages/s2-react/src/components/sheets/table-sheet/index.tsx
  packages/s2-react/src/context/SpreadSheetContext.tsx
  packages/s2-shared/src/interface.ts
  packages/s2-shared/src/styles/drill-down.less
  packages/s2-shared/src/utils/drill-down.ts
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.tsx
Labels: pr(feature), next

#2320 fix: condition.mapping 返回值与文档不符合，允许返回undefined与null
  packages/s2-core/src/common/interface/condition.ts
Labels: pr(fix)

#2306 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2302 fix(scroll): 修复移动端快速滚动时控制台报错 close #2266
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/playground/index.html
Labels: pr(fix)

#2317 fix(scroll): 修复调用 scrollWithAnimation 后 unmount 表格导致频繁报错
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)
