Repository antvis/S2, pull requests merged in 2023-04, with the labels that each got.

#2134 [WIP] feat: 统一导出和复制逻辑，优化导出和复制性能
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/export/copy/index.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/export/interface.ts
  packages/s2-core/src/utils/export/method.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/src/components/export/strategy-copy.ts
Labels: 🚨 test failed, next

#2138 feat: icon支持更新name与fill
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/src/common/icons/gui-icon.ts
Labels: pr(feature)

#2165 fix: 多指标行头总计节点宽度计算错误
  packages/s2-core/__tests__/bugs/issue-2164-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#2152 feat: 统一导出和复制逻辑，优化导出和复制性能
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/export/copy/index.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/export/interface.ts
  packages/s2-core/src/utils/export/method.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/src/components/export/strategy-copy.ts
  pnpm-lock.yaml
Labels: pr(feature), next

#2167 fix: 修复 cornerText 配置对树状模式的适配
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/custom-tree-pivot-data-set.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
  s2-site/docs/api/general/S2Options.zh.md
Labels: pr(fix)

#2163 fix: isMouseOnTheCanvasContainer judge Event is not Native #2162
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#2171 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2173 fix: 行头过宽且不冻结时滚动条渲染错误
  packages/s2-core/__tests__/bugs/issue-2140-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#2183 docs: fix doc text typo bug close #2182
  s2-site/docs/api/basic-class/interaction.zh.md
Labels: pr(documentation)

#2181 fix: canvas mouseout 判断错误
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix), next

#2175 fix(layout): 修复自定义列头采样错误导致行角头不显示 close #2117
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-grid-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-react/playground/components/CustomGrid.tsx
Labels: pr(fix), next

#2172 fix(tooltip): 修复特定配置下点击 tooltip 内容后 tooltip 关闭 close #2170
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#2179 refactor(interaction): 刷选 API 命名调整
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/ui/tooltip/index-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/common/interface/style.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-shared/__tests__/utils/options-spec.ts
  s2-site/docs/api/basic-class/interaction.en.md
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/common/interaction.en.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/basic.en.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/basic/analysis/copy-export.en.md
  s2-site/docs/manual/basic/analysis/copy-export.zh.md
  s2-site/docs/manual/basic/analysis/mobile-component.en.md
  s2-site/docs/manual/basic/analysis/mobile-component.zh.md
  s2-site/examples/interaction/basic/demo/brush-header.ts
Labels: pr(refactor), next
