Repository antvis/S2, pull requests merged in 2023-07, with the labels that each got.

#2273 fix(core): 使用客户端的位置来计算调整大小的偏移量
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/interaction/row-column-resize.ts
Labels: pr(fix)

#2263 fix(core): 删除范围选择中的错误拦截器
  packages/s2-core/src/interaction/range-selection.ts
Labels: pr(fix)

#2261 fix(core): 悬停角头单元格后显示图标
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-react/playground/config.ts
Labels: pr(fix)

#2276 docs: 更新 FAQ 和 文档示例
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/interaction/basic/demo/hover.ts
  s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-content.tsx
Labels: pr(documentation)

#2247 feat: 为 react 编辑组件添加 onDataCellEditEnd 事件
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-shared/src/interface.ts
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/examples/react-component/sheet/demo/editable.tsx
Labels: pr(feature)

#2265 fix(core): 文本区域高度不应超过视口高度
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-react/__tests__/spreadsheet/pagination-spec.tsx
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#2257 fix(core): 调用 `setOptions` 设置 `brushSelection`
  packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#2242 feat: 条件格式 mapping 增加第三个参数获取单元格实例
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/condition.ts
  s2-site/docs/common/conditions.en.md
  s2-site/docs/common/conditions.zh.md
Labels: pr(feature), next

#2275 perf(react): 防止不必要的重新渲染
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/index.tsx
Labels: next

#2272 feat: 使用 requestIdleCallback 处理数据大量导出的情况
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/src/common/constant/copy.ts
  packages/s2-core/src/common/interface/events.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/export-worker.ts
  packages/s2-core/src/utils/export/index.ts
  packages/s2-core/src/utils/export/interface.ts
  packages/s2-react/src/components/export/index.tsx
  s2-site/docs/common/export.zh.md
Labels: pr(feature), next

#2281 docs: 完善 tooltip 文档
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx
Labels: pr(documentation)

#2267 feat: 文本和图标的条件格式支持主题配置
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/interface/condition.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/playground/components/StrategySheet.tsx
  packages/s2-react/playground/config.ts
  packages/s2-react/src/components/index.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-cell/col-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-cell/data-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-cell/index.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-data-set.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/col-cell-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/data-cell-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/row-cell-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/basic/theme.zh.md
  s2-site/examples/react-component/sheet/demo/strategy.tsx
Labels: pr(feature), next

#2282 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2290 fix(table): 修复明细表获取到错误的实际渲染内容高度
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
Labels: pr(fix)

#2288 fix: 点击列头后hover拦截消失
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/src/interaction/range-selection.ts
Labels: pr(fix)

#2293 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2286 chore: `setDataCfg` 函数类型优化
  packages/s2-core/src/common/interface/store.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: pr(chore)
