Repository antvis/S2, pull requests merged in 2023-12, with the labels that each got.

#2444 fix: 修复缺失维度所生成的 query 多了 empty extra value 字段
  packages/s2-core/__tests__/spreadsheet/miss-dimension-values-spec.ts
  packages/s2-core/src/utils/layout/get-dims-condition-by-node.ts
Labels: pr(fix)

#2442 fix: 修复中英文标点符号
  packages/s2-core/__tests__/unit/common/i18n/index-spec.ts
  packages/s2-core/src/common/i18n/en_US.ts
  packages/s2-core/src/common/i18n/zh_CN.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/tooltip/components/description.tsx
  packages/s2-react/src/components/tooltip/components/head-info.tsx
  packages/s2-react/src/components/tooltip/components/summary.tsx
  packages/s2-shared/src/constant/i18n/en_US.ts
  packages/s2-shared/src/constant/i18n/zh_CN.ts
Labels: pr(fix)

#2445 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2416 feat: 交叉表支持冻结首行能力
  packages/s2-core/__tests__/bugs/issue-1191-spec.ts
  packages/s2-core/__tests__/bugs/issue-1201-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/facet/header/frozen-row-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-frozen-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/cell/frozen-row-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/index.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/constant/frozen.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/header/base-frozen-row.ts
  packages/s2-core/src/facet/header/index.ts
  packages/s2-core/src/facet/header/pivot-row.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/indexes.ts
  packages/s2-react/__tests__/spreadsheet/drill-down-spec.tsx
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.en.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/examples/interaction/advanced/demo/frozen-pivot-grid.ts
  s2-site/examples/interaction/advanced/demo/frozen-pivot-tree.ts
  s2-site/examples/interaction/advanced/demo/meta.json
Labels: pr(feature)

#2448 docs: 润色文档细节 & 修复一些错误的文档示例地址
  packages/s2-core/README.md
  packages/s2-core/__tests__/unit/facet/header/frozen-row-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-frozen-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-react/README.md
  packages/s2-react/playground/config.ts
  s2-site/docs/api/components/drill-down.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/basic/analysis/drill-down.zh.md
  s2-site/docs/manual/basic/analysis/editable-mode.zh.md
  s2-site/docs/manual/basic/analysis/strategy.zh.md
  s2-site/docs/manual/basic/analysis/switcher.zh.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.en.md
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/docs/manual/basic/sort/advanced.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/examples/basic/table/demo/table.ts
  s2-site/examples/interaction/advanced/demo/frozen-pivot-grid.ts
  s2-site/examples/interaction/advanced/demo/frozen-pivot-tree.ts
  s2-site/examples/react-component/drill-down/API.en.md
  s2-site/examples/react-component/drill-down/API.zh.md
  s2-site/examples/react-component/drill-down/demo/basic-panel.tsx
  s2-site/examples/react-component/drill-down/demo/for-pivot.tsx
  s2-site/examples/react-component/drill-down/demo/meta.json
  s2-site/examples/react-component/drill-down/index.en.md
  s2-site/examples/react-component/drill-down/index.zh.md
Labels: pr(documentation)

#2449 fix(interaction): 修复数值单元格取消选中 & 点击空白处取消选中时没触发 GLOBAL_SELECTED 事件
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/facet/header/pivot-row.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix)

#2450 refactor: frozenRowCell 重命名为 rowCell
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/facet/header/frozen-row-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-frozen-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/state-controller-spec.ts
  packages/s2-core/src/cell/base-row-cell.ts
  packages/s2-core/src/cell/frozen-row-cell.ts
  packages/s2-core/src/cell/index.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/facet/header/base-frozen-row.ts
  packages/s2-core/src/facet/header/pivot-row.ts
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/manual/basic/sheet-type/pivot-mode.zh.md
  s2-site/examples/basic/pivot/demo/grid.ts
  s2-site/examples/basic/pivot/demo/tree.ts
  s2-site/examples/interaction/basic/demo/frozen-row-header.ts
  s2-site/examples/interaction/basic/demo/meta.json
Labels: pr(refactor)

#2452 fix: 修复透视表数据为空时，行列交叉单元格缺失的问题
  packages/s2-core/__tests__/spreadsheet/empty-dataset-spec.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/facet/frozen-facet.ts
Labels: pr(fix)

#2451 fix: 区分 GuiIcon 报错类型 close #2345
  packages/s2-core/src/common/icons/gui-icon.ts
Labels: pr(fix)

#2453 fix(table-sheet): 修复明细表排序后开启行列冻结, 冻结行展示错误 close #2388
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/dataset/__snapshots__/table-dataset-spec.ts.snap
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/util/index.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-react/__tests__/spreadsheet/filter-sheet-spec.tsx
  packages/s2-react/playground/config.ts
  s2-site/examples/interaction/basic/demo/state-theme.ts
Labels: pr(fix)

#2459 fix: seriesNumberHeader 不应该使用 custom row cell
  packages/s2-core/src/facet/header/row.ts
  packages/s2-core/src/facet/header/series-number.ts
Labels: pr(fix)

#2457 fix(table-sheet): 修复明细表 tooltip 展示了错误的汇总数据的问题
  packages/s2-core/__tests__/unit/data-set/__snapshots__/table-data-set-spec.ts.snap
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/table-data-set.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/playground/config.ts
Labels: pr(fix)

#2461 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2466 fix(tooltip): 修复字段描述为英文时展示不全
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/custom-tooltip/index-spec.tsx
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-data-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/custom-row-tooltip.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/custom-tooltip/index.less
Labels: pr(fix)

#2472 fix: 修复多列文本单元格 hover 时报错
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
Labels: pr(fix)

#2474 fix: 去除 data cell hover 的 ellipsisTooltip 展示逻辑
  packages/s2-core/src/interaction/base-interaction/hover.ts
Labels: pr(fix)

#2477 feat: 在自动发布前, 自动注入新版本到打包代码中
  .github/workflows/auto-release.yml
  .releaserc.base.js
  package.json
  scripts/add-version.js
  yarn.lock
Labels: pr(feature)

#2479 fix: 修复初始化渲染未完成时headNode NPE问题
  packages/s2-core/src/facet/utils.ts
Labels: pr(fix)

#2482 fix: 修复行头字段为空字符串时, getDimensionValues 获取数据错误的问题
  packages/s2-core/__tests__/spreadsheet/empty-string-values-spec.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(fix)

#2481 chore: 🤖 更新 changelog 文件
  .github/workflows/auto-release.yml
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore), 🚨 test failed

#2478 perf: 优化多行文本渲染性能
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/interface.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/data/custom-tree-fields.ts
  packages/s2-react/playground/components/ResizeConfig.tsx
  packages/s2-react/playground/config.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/chart-sheet/custom-cell/data-cell.ts
  packages/s2-react/src/components/sheets/grid-analysis-sheet/custom-cell/data-cell.ts
  packages/s2-react/src/components/sheets/strategy-sheet/custom-cell/data-cell.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: next

#2485 fix: 处理 getMultiData 在找不到数据时的报错信息
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-row-value-spec.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(fix)

#2488 fix: 修复维度字段中包含 [&] 分隔符导致的获取数据不正确的问题
  packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(fix)

#2491 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore), 🚨 test failed

#2494 feat(dumi): add dumi plugin close antd alias
  s2-site/.dumi/theme/plugin.ts
  s2-site/.dumirc.ts
Labels: pr(feature), next
