Repository antvis/S2, pull requests merged in 2023-03, with the labels that each got.

#2094 refactor: 统一行列在文字实时滚动逻辑
  .eslintrc.js
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/text-scrolling-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/interface/scroll.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/cell/text-scrolling.ts
  packages/s2-core/src/utils/normalize.ts
  packages/s2-core/src/utils/text-absorption.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(refactor), next

#2099 docs: 修复官网图表示例无法运行
  .github/workflows/site-build-notify.yml
  .gitignore
  .npmrc
  .yarnrc
  s2-site/.gitignore
  s2-site/.npmrc
  s2-site/.yarnrc
  s2-site/README.md
  s2-site/package.json
  s2-site/public/site.css
Labels: pr(documentation)

#2105 chore: 更新 project action 配置
  .github/workflows/auto-add-to-project.yml
Labels: pr(chore)

#2104 fix: 修复 vue playground 启动失败
  packages/s2-vue/playground/App.vue
Labels: pr(fix), next

#2107 chore: 修复 typo action 错误
  .github/workflows/auto-add-to-project.yml
Labels: pr(chore)

#2108 fix: 重命名supportCSSTransform为supportsCSSTransform
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(fix), next

#2109 feat: 在 shape 中添加文本的原始值
  packages/s2-core/src/utils/g-renders.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(feature)

#2112 chore: 修复 disscustion action 执行失败
  .github/workflows/disscustion.yml
Labels: pr(chore)

#2114 feat: 增加自定义合并单元格能力
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/advanced/interaction/merge-cell.en.md
  s2-site/docs/manual/advanced/interaction/merge-cell.zh.md
  s2-site/examples/custom/custom-cell/demo/custom-merged-cell.ts
  s2-site/examples/custom/custom-cell/demo/meta.json
Labels: pr(feature)

#2113 chore: 修复镜像源问题导致自动发布失败
  .github/workflows/auto-release.yml
  .github/workflows/prerelease-notify.yml
  .github/workflows/release-notify.yml
  .github/workflows/release-success.yml
  .github/workflows/site-build-notify.yml
  .github/workflows/sync-notify.yml
  .npmrc
Labels: pr(chore)

#2116 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2120 docs: 优化文档
  s2-site/docs/api/components/header.en.md
  s2-site/docs/api/components/header.zh.md
  s2-site/docs/api/components/switcher.zh.md
  s2-site/docs/common/header.zh.md
  s2-site/docs/common/interaction.zh.md
Labels: pr(documentation)

#2121 chore: 修改 reject label 为 won't support
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#2122 docs: update CONTRIBUTING
  CONTRIBUTING.en-US.md
  CONTRIBUTING.md
Labels: pr(documentation)

#2123 chore: label ci type fix
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#2124 chore: update issue-labeled.yml
  .github/workflows/issue-labeled.yml
Labels: pr(chore)

#2102 feat: implement data cell link
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-react/playground/index.html
  packages/s2-react/playground/index.tsx
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/examples/interaction/advanced/demo/pivot-link-jump.ts
Labels: pr(feature), 🙏 need test cases or docs

#2119 fix(interaction): 修复从下往上滚动刷选速度缓慢 & 优化滚动刷选蒙层显示
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
Labels: pr(fix)

#2133 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2139 feat: 移除switcher按钮important样式
  packages/s2-react/src/components/switcher/index.less
Labels: pr(feature)

#2145 chore: 🤖 更新 changelog 文件
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2144 docs: 增加角头和明细表数据获取文档 close #2141
  s2-site/docs/manual/advanced/get-cell-data.zh.md
Labels: pr(documentation)
