Repository antvis/S2, pull requests merged in 2024-07, with the labels that each got.

#2790 chore: 更新 react-componnents 依赖配置和说明文档
  packages/s2-react-components/README.md
  packages/s2-react-components/package.json
  packages/s2-react-components/playground/config.tsx
  packages/s2-react-components/playground/index.tsx
  packages/s2-react-components/src/components/config/theme-panel/interface.ts
  packages/s2-react-components/tsconfig.json
Labels: pr(chore), next

#2805 fix: 自定义计算汇总 calcFunc 回调函数增加 s2 实例, 修复无法获取汇总数据的问题 close #2795
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/utils/data-set-operate.ts
  pnpm-lock.yaml
  s2-site/.dumirc.ts
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/examples/analysis/totals/demo/custom.ts
  s2-site/package.json
Labels: pr(fix)

#2796 feat: 统一链接跳转字段绘制逻辑, 支持标记列头 close #2430
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/header-cell-link-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/header-cell-link-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/formatter-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/header-cell-link-click.ts
  packages/s2-core/src/interaction/base-interaction/click/index.ts
  packages/s2-core/src/interaction/base-interaction/click/row-text-click.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/interaction/formatter.ts
  packages/s2-core/src/utils/interaction/link-field.ts
  packages/s2-react-components/__tests__/unit/components/config/theme-panel/__snapshots__/utils-spec.ts.snap
  packages/s2-react/playground/config.tsx
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/link-jump.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/interaction/advanced/demo/custom-link-jump.ts
  s2-site/examples/interaction/advanced/demo/custom-tree-link-jump.ts
  s2-site/examples/interaction/advanced/demo/meta.json
  s2-site/examples/interaction/advanced/demo/pivot-link-jump.ts
Labels: pr(feature), next

#2799 feat: meta 支持配置数值和正则, 便于批量配置 close #2647
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/data-set/base-data-set.ts
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/manual/basic/formatter.zh.md
  s2-site/examples/basic/pivot/demo/grid.ts
Labels: pr(feature), next

#2800 fix: 取消双击表格时浏览器默认的选中文本行为 close #2798
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
  packages/s2-react/playground/index.tsx
Labels: pr(fix), next

#2802 feat: 支持同时在 React 16/17/18 下运行
  packages/s2-react/__tests__/unit/utils/react-render-16-spec.tsx
  packages/s2-react/__tests__/unit/utils/react-render-18-spec.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/custom-cell/edit-cell/index.tsx
  packages/s2-react/src/components/tooltip/custom-tooltip.tsx
  packages/s2-react/src/utils/invokeComponent.tsx
  packages/s2-react/src/utils/reactRender.ts
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(feature), next

#2806 fix: 修复树状模式当一组数据只有一条数据时, 叶子节点判断错误, 也渲染了展开/收起图标 close #2804
  packages/s2-core/__tests__/bugs/issue-2804-spec.ts
  packages/s2-core/__tests__/data/data-issue-2804.json
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
Labels: pr(fix), 🚨 test failed, 🚨 lint failed

#2811 chore: 🤖 更新 changelog 文件
  .github/workflows/auto-release.yml
  .github/workflows/compressed-size.yml
  .github/workflows/lint.yml
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore), 🚨 test failed

#2812 chore(ci): 升级 CI 运行的 pnpm 版本, 解决 ERR_INVALID_THIS 问题
  .github/workflows/test.yml
Labels: pr(chore)

#2823 fix(typo): Change target attribute from _black to _blank
  s2-site/playground/config-panel/config-component/dragger-upload/index.tsx
Labels: pr(fix)

#2826 fix: 处理自定义mini图显示柱状图时，全为正值&全为零值 展示异常问题
  packages/s2-core/src/utils/g-mini-charts.ts
Labels: pr(fix), next

#2829 fix: 修复在维值缺失场景下导出数据占位符未解析的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/miss-dimension-values-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/miss-dimension-values-spec.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/facet/utils.ts
  packages/s2-core/src/utils/export/copy.ts
  packages/s2-core/src/utils/export/export-worker.ts
Labels: pr(fix)

#2835 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2836 docs: 文档错位修正
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(documentation)

#2842 docs: 修复 v1 官网部分页面白屏
  s2-site/.dumirc.ts
  s2-site/docs/api/basic-class/base-cell.en.md
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/interaction.en.md
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Options.en.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/custom/dataCellCallback.en.md
  s2-site/docs/common/custom/dataCellCallback.zh.md
  s2-site/docs/common/custom/layoutDataPosition.en.md
  s2-site/docs/common/custom/layoutDataPosition.zh.md
Labels: pr(documentation), 🚨 test failed
