Repository antvis/S2, pull requests merged in 2024-04, with the labels that each got.

#2642 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2645 feat: canvas 支持挂载 s2 实例
  global.d.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/rollup.config.js
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/tsconfig.declaration.json
  packages/s2-core/tsconfig.json
  packages/s2-react/tsconfig.json
  packages/s2-vue/tsconfig.json
Labels: pr(feature)

#2651 docs: 移除答疑群二维码, 任何问题请提交 issue
  README.md
  packages/s2-core/README.md
  s2-site/docs/manual/introduction.zh.md
Labels: pr(documentation)

#2650 test(cell): 增加基础单元格和滚动条-单测覆盖
  jest.config.base.js
  package.json
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/merged-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/series-number-cell-spec.ts
  packages/s2-core/__tests__/unit/common/icons/factory-spec.ts
  packages/s2-core/__tests__/unit/ui/scrollbar/__snapshots__/index-spec.ts.snap
  packages/s2-core/__tests__/unit/ui/scrollbar/index-spec.ts
  packages/s2-core/src/cell/base-row-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
Labels: pr(test)

#2652 test: 增加基础工具函数-单测覆盖
  packages/s2-core/__tests__/unit/utils/__snapshots__/g-mini-charts-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/__snapshots__/sort-action-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/canvas-spec.ts
  packages/s2-core/__tests__/unit/utils/condition/condition-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.ts
  packages/s2-core/__tests__/unit/utils/formatter-spec.ts
  packages/s2-core/__tests__/unit/utils/g-mini-charts-spec.ts
  packages/s2-core/__tests__/unit/utils/get-classnames-spec.ts
  packages/s2-core/__tests__/unit/utils/indexes-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/__snapshots__/formatter-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/interaction/formatter-spec.ts
  packages/s2-core/__tests__/unit/utils/is-mobile-spec.ts
  packages/s2-core/__tests__/unit/utils/layout/__snapshots__/frozen-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/layout/frozen-spec.ts
  packages/s2-core/__tests__/unit/utils/layout/generate-id-spec.ts
  packages/s2-core/__tests__/unit/utils/layout/get-dims-condition-by-node-spec.ts
  packages/s2-core/__tests__/unit/utils/layout/whether-leaf-by-level-spec.ts
  packages/s2-core/__tests__/unit/utils/sort-action-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/__tests__/unit/utils/theme-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/index.ts
  packages/s2-core/src/utils/layout/generate-id.ts
  packages/s2-core/src/utils/layout/get-right-field-in-query.ts
  packages/s2-core/src/utils/text-absorption-center.ts
  s2-site/docs/manual/faq.zh.md
Labels: pr(test)

#2653 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore)

#2657 test(shared): 完善公用包单测
  jest.config.base.js
  packages/s2-shared/__tests__/unit/utils/classnames-spec.ts
  packages/s2-shared/__tests__/unit/utils/drill-down-spec.ts
  packages/s2-shared/__tests__/unit/utils/options-spec.ts
  packages/s2-shared/__tests__/unit/utils/resize-spec.ts
  packages/s2-shared/__tests__/util/helpers.ts
  packages/s2-shared/src/utils/drill-down.ts
Labels: pr(test)

#2656 docs: 修复小计总计错误文档
  s2-site/docs/common/totals.zh.md
  s2-site/docs/manual/basic/totals.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/analysis/totals/demo/basic.ts
Labels: pr(documentation), next

#2668 fix: 修复紧凑模式下数值单元格maxWidth计算错误的问题
  packages/s2-core/__tests__/bugs/issue-2385-spec.ts
  packages/s2-core/__tests__/data/data-issue-2385.json
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/utils/cell/cell.ts
Labels: pr(fix)

#2666 fix: 修复分页配置无法透传
  packages/s2-vue/src/components/pagination/index.vue
  packages/s2-vue/src/components/sheets/base-sheet.vue
  packages/s2-vue/src/hooks/usePagination.ts
Labels: pr(fix)

#2672 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore)

#2673 fix: 修复紧凑模式下单元格宽度计算忽略了icon宽度的问题
  packages/s2-core/__tests__/bugs/issue-2385-spec.ts
  packages/s2-core/__tests__/data/data-issue-2385.json
  packages/s2-core/__tests__/unit/utils/condition/condition-spec.ts
  packages/s2-core/__tests__/unit/utils/layout/icon-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/condition/condition.ts
  packages/s2-core/src/utils/layout/icon.ts
  packages/s2-core/src/utils/layout/index.ts
Labels: pr(fix)

#2674 fix: 修复明细表自定义多级列头导出格式错误 close #2664
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-react/playground/components/CustomGrid.tsx
Labels: pr(fix), next

#2682 fix: 修复只有一行数据时异步导出数据为空 close #2681
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
Labels: pr(fix), next

#2685 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2689 fix: 修复计算列宽时计算的文字宽度和判断文本是否溢出隐藏的文字宽度不一致的问题
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#2686 fix: 修复透视表开启多行文本后自定义行高不生效 close #2678
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), next

#2690 fix: 修复表格右键事件无法触发 close #2687
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/src/common/constant/events/g.ts
  packages/s2-core/src/common/constant/events/index.ts
  packages/s2-core/src/common/constant/events/origin.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/manual/advanced/interaction/custom.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/interaction/custom/demo/disable-context-menu.ts
  s2-site/examples/interaction/custom/demo/double-click-hide-columns.ts
  s2-site/examples/interaction/custom/demo/meta.json
Labels: pr(fix), next

#2692 fix: 修复非滚动引起的渲染也会触发滚动事件的问题
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#2691 fix: 修复维值带有 '-' 时刷选复制无法复制表头 close #2684
  packages/s2-core/__tests__/bugs/__snapshots__/issue-2684-spec.ts.snap
  packages/s2-core/__tests__/bugs/issue-2684-spec.ts
  packages/s2-core/__tests__/data/data-issue-2684.json
  packages/s2-core/__tests__/spreadsheet/total-group-spec.ts
  packages/s2-core/__tests__/unit/cell/header-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/series-number-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/data-cell-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/utils/cell/data-cell.ts
  packages/s2-core/src/utils/export/copy.ts
Labels: pr(fix)

#2695 chore: 移除过时的 workflow
  .github/workflows/issue-opend.yml
  .github/workflows/release-success.yml
  .github/workflows/site-build-notify.yml
  .github/workflows/sync-notify.yml
Labels: pr(chore)

#2696 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)
