Repository antvis/S2, pull requests merged in 2024-05, with the labels that each got.

#2631 feat: 更新 g 到最新版
  packages/s2-core/__tests__/benchmark/pivot-sheet-spec.ts
  packages/s2-core/__tests__/benchmark/table-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/package.json
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/series-number.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-react/__tests__/unit/components/advanced-sort/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/drill-down/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/export/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/header/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/pagination/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/switcher/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/tooltip/__snapshots__/index-spec.tsx.snap
  packages/s2-react/package.json
  packages/s2-react/playground/index.tsx
  pnpm-lock.yaml
  s2-site/package.json
Labels: pr(feature), next

#2700 feat(options): customSVGIcons API 变更
  packages/s2-core/__tests__/benchmark/pivot-sheet-spec.ts
  packages/s2-core/__tests__/benchmark/table-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/header-action-icons-spec.ts
  packages/s2-core/__tests__/spreadsheet/theme-spec.ts
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/common/icons/factory.ts
  packages/s2-core/src/common/icons/svg/index.ts
  packages/s2-core/src/common/icons/svg/svgs.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/package.json
  packages/s2-react/playground/components/ChartSheet.tsx
  packages/s2-react/playground/index.tsx
  pnpm-lock.yaml
  s2-site/docs/common/custom/customSvgIcons.zh.md
  s2-site/docs/common/header-action-icon.zh.md
  s2-site/docs/common/icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.en.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/advanced/custom/custom-order.en.md
  s2-site/docs/manual/advanced/custom/custom-order.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/custom/custom-icon/demo/custom-data-cell-icon.ts
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.ts
  s2-site/examples/custom/custom-icon/demo/custom-svg-icon.ts
  s2-site/examples/custom/custom-icon/demo/custom-tree-icon.ts
  s2-site/examples/custom/custom-order/demo/custom-order.tsx
  s2-site/package.json
Labels: pr(feature), next

#2703 fix: 修复导出 CSV 时分隔符错误导致的展示格式错误 close #2701
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/bugs/issue-565-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/__tests__/unit/utils/export/utils-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/constant/copy.ts
  packages/s2-core/src/common/interface/export.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/utils.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/playground/config.tsx
  packages/s2-react/src/components/export/index.tsx
  packages/s2-react/src/components/export/strategy-copy.ts
  s2-site/docs/api/components/export.en.md
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/common/copy-export.en.md
  s2-site/docs/common/copy-export.zh.md
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(fix), next

#2708 fix: 修复明细表含有空数据占位符时排序错误 close #2707
  packages/s2-core/__tests__/bugs/__snapshots__/issue-2707-spec.ts.snap
  packages/s2-core/__tests__/bugs/issue-2707-spec.ts
  packages/s2-core/__tests__/data/data-issue-2707.json
  packages/s2-core/src/data-set/table-data-set.ts
Labels: pr(fix)

#2705 fix: 修复配置了多行文本但实际渲染的文本未换行时, 单元格高度也会自适应调整的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-facet-spec.ts
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/package.json
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-react/package.json
  packages/s2-react/playground/index.tsx
  pnpm-lock.yaml
Labels: pr(fix), next

#2711 fix: 修复无汇总数据时前端计算汇总值缺少聚合方式导致排序失效的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/sort-by-order-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/sort-by-order-spec.ts
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
Labels: pr(fix), 🚨 test failed

#2713 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2721 fix: 修复滚动边界问题 close #2720
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), next

#2725 docs: 修复升级 G 6.0 引起的文档错误
  packages/s2-react/CHANGELOG.md
  packages/s2-react/playground/index.tsx
  pnpm-lock.yaml
  s2-site/docs/common/packages.zh.md
  s2-site/docs/manual/advanced/chart-in-cell.zh.md
  s2-site/docs/manual/advanced/custom/custom-order.zh.md
  s2-site/docs/manual/basic/multi-line-text.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/case/art/demo/time-spend-abstract.tsx
  s2-site/examples/custom/custom-cell/demo/col-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/row-cell.ts
  s2-site/examples/custom/custom-order/demo/custom-order.tsx
  s2-site/examples/custom/custom-plugins/demo/a11y.ts
  s2-site/examples/custom/custom-plugins/demo/meta.json
  s2-site/examples/custom/custom-plugins/demo/rough.ts
  s2-site/examples/custom/custom-plugins/index.en.md
  s2-site/examples/custom/custom-plugins/index.zh.md
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
  s2-site/package.json
Labels: pr(documentation), next

#2719 fix: 修复下载数据重复 close #2718
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/__tests__/util/index.ts
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
Labels: pr(fix), next

#2733 docs: 增加使用 @antv/s2 实现排序功能的示例
  packages/s2-core/src/common/interface/basic.ts
  s2-site/docs/manual/basic/sort/group.zh.md
  s2-site/examples/analysis/sort/demo/group-sort-base.ts
  s2-site/examples/analysis/sort/demo/group-sort.tsx
  s2-site/examples/analysis/sort/demo/meta.json
Labels: pr(documentation), next

#2728 perf: 优化未开启多行文本时的布局性能 close #2693
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: next

#2732 fix: 修复列等宽布局模式下角头出现省略号 close #2726
  packages/s2-core/__tests__/bugs/issue-2726-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix), next

#2729 feat: 明细表新增空数据占位符能力
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/table-sheet-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/miss-dimension-values-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/common/icons/factory-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/merge-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/i18n/en_US.ts
  packages/s2-core/src/common/i18n/zh_CN.ts
  packages/s2-core/src/common/icons/svg/index.ts
  packages/s2-core/src/common/icons/svg/svgs.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/data/strategy-data.ts
  packages/s2-react/__tests__/spreadsheet/table-sheet-spec.tsx
  packages/s2-react/playground/config.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/export/strategy-copy.ts
  packages/s2-shared/__tests__/unit/utils/__snapshots__/options-spec.ts.snap
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/basic/table/demo/table.ts
  s2-site/examples/case/kpi-strategy/demo/covid-trend.tsx
  s2-site/examples/custom/custom-cell/demo/data-cell-placeholder.ts
  s2-site/examples/custom/custom-cell/demo/empty-placeholder.ts
  s2-site/examples/custom/custom-cell/demo/meta.json
  s2-site/examples/theme/custom/demo/custom-schema.ts
Labels: pr(feature), next

#2739 fix: 在 resize 时加上 preventDefault 事件，兼容 chrome 125 事件更新的处理
  packages/s2-core/src/interaction/row-column-resize.ts
Labels: pr(fix)

#2740 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore), 🚨 test failed

#2738 fix: 修复自定义 tooltip 时, 刷选时无法获取到单元格信息
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/tooltip.ts
Labels: pr(fix), next

#2734 perf: 优化开启多行文本时的布局性能
  packages/s2-core/__tests__/benchmark/pivot-sheet-spec.ts
  packages/s2-core/__tests__/benchmark/table-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/package.json
  packages/s2-core/scripts/test-live.mjs
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/header/table-col.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-react/package.json
  packages/s2-react/scripts/test-live.mjs
  packages/s2-shared/package.json
  packages/s2-vue/package.json
  pnpm-lock.yaml
Labels: 🚨 test failed, next

#2741 docs: 完善自定义单元格的优先级说明和自定义绘制图标的示例 close #2736
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
  s2-site/examples/custom/custom-shape-and-chart/demo/meta.json
  s2-site/examples/layout/custom/demo/custom-pivot-size.ts
  s2-site/examples/layout/custom/demo/custom-table-size.ts
Labels: pr(documentation), next

#2744 fix: 修复字段标记背景色透明度优先级低于主题背景色透明度的问题
  packages/s2-core/__tests__/unit/utils/color-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/utils/color.ts
  s2-site/docs/manual/basic/conditions.en.md
  s2-site/docs/manual/basic/conditions.zh.md
Labels: pr(fix)

#2743 docs: 增加如何避免表格滚动时图片重复加载的文档和示例 #2737
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-react/playground/config.tsx
  s2-site/docs/manual/advanced/chart-in-cell.zh.md
  s2-site/docs/manual/faq.zh.md
  s2-site/examples/case/art/demo/lost-text.tsx
  s2-site/examples/case/art/demo/time-spend-abstract.tsx
  s2-site/examples/custom/custom-cell/demo/col-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-cell.ts
  s2-site/examples/custom/custom-cell/demo/corner-header.ts
  s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/row-cell.ts
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
Labels: pr(documentation), next

#2746 test(utils): 完善工具函数的单测
  packages/s2-core/__tests__/unit/facet/layout/layout-hooks-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/node-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/select-event-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
  packages/s2-core/src/utils/text.ts
Labels: pr(test)

#2758 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2643 fix: wheel scroll error!
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/playground/components/BigDataSheet.tsx
  packages/s2-react/playground/index.tsx
Labels: pr(fix), next

#2757 fix: 修复明细表导出时自定义序号文本不生效 close #2755
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/data-set/table-data-set-spec.ts
  packages/s2-core/__tests__/unit/facet/header/corner-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/layout/build-header-hierarchy.ts
  packages/s2-core/src/facet/layout/build-table-hierarchy.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/method.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: pr(fix), next

#2760 docs: 2.0 升级指南增加 antd 多版本共存的教程
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/custom/custom-order/demo/custom-order.tsx
Labels: pr(documentation), next

#2748 fix: 修复自定义 dataCell 错误的传参写法
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/src/components/sheets/chart-sheet/index.tsx
  packages/s2-react/src/components/sheets/grid-analysis-sheet/index.tsx
  packages/s2-react/src/components/sheets/strategy-sheet/index.tsx
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/common/custom/dataCellCallback.zh.md
  s2-site/docs/manual/advanced/chart-in-cell.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/case/art/demo/time-spend-abstract.tsx
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
  s2-site/examples/case/comparison/demo/time-spend.tsx
  s2-site/examples/case/kpi-strategy/demo/basic.tsx
  s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
  s2-site/examples/custom/custom-cell/demo/custom-table-cell.ts
  s2-site/examples/custom/custom-cell/demo/data-cell.ts
  s2-site/examples/custom/custom-cell/demo/mini-chart.ts
  s2-site/examples/custom/custom-dataset/demo/custom-strategy-sheet-dataset.ts
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g2-chart.ts
Labels: pr(fix), next
