Repository antvis/S2, pull requests merged in 2024-09, with the labels that each got.

#2886 docs: 优化 contextmenu API 文档 close #2882
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
Labels: pr(documentation), next

#2890 docs: 修复文档 vue demo
  s2-site/docs/manual/basic/tooltip.en.md
  s2-site/docs/manual/basic/tooltip.zh.md
Labels: pr(documentation)

#2883 feat: 新增 s2.facet.getContentWidth() API
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(feature), next

#2895 fix: 修复 expandDepth 在自定义行头场景下不生效
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-collapse-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/style.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-react/playground/components/CustomTree.tsx
  s2-site/docs/manual/advanced/custom/custom-collapse-nodes.zh.md
Labels: pr(fix), next

#2891 fix: 移动端关闭 supportsPointerEvents, 避免禁用 touchAction close #2857
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(fix), next

#2897 fix: 修复浏览器窗口多次放大后表格渲染模糊 close #2884
  packages/s2-core/src/ui/hd-adapter/index.ts
Labels: pr(fix), next
