Repository antvis/S2, pull requests merged in 2024-01, with the labels that each got.

#2519 fix: 增加树状模式自定义宽度的容错
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-resize-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/spread-sheet-resize-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix)

#2521 fix(table-sheet): 修复明细表配置自定义行高后展示异常 close #2501
  packages/s2-core/__tests__/bugs/issue-2501-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix)

#2524 fix: 自定义 icon 支持跨域 close #2513
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  s2-site/docs/manual/basic/sheet-type/table-mode.zh.md
  s2-site/examples/basic/table/demo/table.ts
Labels: pr(fix)

#2527 fix(interaction): 修复隐藏列头配置更新时未覆盖上一次的配置 close #2495
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-vue/src/hooks/useSheetUpdate.ts
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/examples/analysis/sort/demo/table-sort.tsx
  s2-site/examples/interaction/advanced/demo/pivot-hide-columns.ts
  s2-site/examples/interaction/advanced/demo/table-hide-columns.ts
  s2-site/examples/react-component/switcher/demo/pure-switcher.tsx
  s2-site/examples/react-component/switcher/demo/table.tsx
Labels: pr(fix)

#2522 chore: 使用 pnpm 作为包管理器
  .eslintrc.js
  .github/workflows/auto-release.yml
  .github/workflows/compressed-size.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/lint.yml
  .github/workflows/release-success.yml
  .github/workflows/test.yml
  .husky/pre-push
  .npmrc
  .yarnrc
  CONTRIBUTING.en-US.md
  CONTRIBUTING.md
  README.en-US.md
  README.md
  jest.config.base.js
  lerna.json
  package.json
  packages/s2-core/README.en-US.md
  packages/s2-core/README.md
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/custom-tree-corner-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/common/icons/__snapshots__/gui-icon-spec.ts.snap
  packages/s2-core/package.json
  packages/s2-core/rollup.config.js
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/ui/scrollbar/index.ts
  packages/s2-react/README.md
  packages/s2-react/__tests__/spreadsheet/__snapshots__/pagination-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/drill-down/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/pagination/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
  packages/s2-react/package.json
  packages/s2-react/src/components/advanced-sort/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/switcher/content/index.tsx
  packages/s2-react/src/hooks/useLoading.ts
  packages/s2-shared/package.json
  packages/s2-vue/README.md
  packages/s2-vue/package.json
  packages/s2-vue/src/components/sheets/index.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
  s2-site/docs/common/development.en.md
  s2-site/docs/common/development.zh.md
  s2-site/docs/manual/contribution.en.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/package.json
  scripts/add-version.js
  scripts/bump-version.js
  scripts/validate-deps.js
  yarn.lock
Labels: pr(chore)

#2530 docs: 修复 https://s2.antv.vision 老官网自动部署失败
  .github/workflows/release-success.yml
  LEGAL.md
  pnpm-lock.yaml
  s2-site/LEGAL.md
  s2-site/package.json
Labels: pr(documentation), 🚨 test failed
