Repository antvis/S2, pull requests merged in 2024-12, with the labels that each got.

#3012 chore: 更新 next issue label ci 脚本
  .github/workflows/issue-labeled.yml
Labels: pr(chore), next

#3010 fix: 修复角头存在多行文本时未自动撑开列头高度的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/common/constant/basic.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/basic/multi-line-text.zh.md
Labels: pr(fix), next

#3013 fix: 修复点击单元格中的 icon 时无法获取到单元格 meta 信息的问题 close #2985
  packages/s2-core/src/utils/interaction/formatter.ts
  packages/s2-react/src/hooks/useEvents.ts
Labels: pr(fix), next

#3017 fix: 修复明细表自定义行高时多行文本未自适应调整
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/__snapshots__/formatter-spec.ts.snap
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), next

#3021 fix: 选中事件增加 event 信息
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  s2-site/docs/common/interaction.zh.md
Labels: pr(fix), next

#3019 fix: 修复手动排序在单行头且维值相似的场景不生效
  .github/workflows/test.yml
  packages/s2-core/__tests__/unit/utils/sort-action-spec.ts
  packages/s2-core/src/utils/sort-action.ts
Labels: pr(fix), next

#3026 fix: 构建产物编译到 es2015 close #3025
  package.json
  packages/s2-core/tsconfig.build.json
  packages/s2-core/tsconfig.json
  packages/s2-react-components/tsconfig.build.json
  packages/s2-react/tsconfig.build.json
  packages/s2-vue/tsconfig.build.json
Labels: pr(fix), next

#3027 fix: 修复在维值缺失场景下导出数据占位符未解析的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/miss-dimension-values-spec.ts.snap
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/utils/export/method.ts
Labels: pr(fix), next

#3029 fix: 修复行头圈选复制时部分场景下数据重复 close #2975
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/basic/pivot/demo/grid.ts
Labels: pr(fix), next

#3039 fix: 解决移动端下，树形结构展开、收起交互失效的问题
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/row-cell.ts
Labels: pr(fix), next

#3033 chore: 优化 CI Workflow
  .github/ISSUE_TEMPLATE/ask-for-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-opend.yml
  .github/workflows/pr-auto-assign-reviewer.yml
  .github/workflows/pr-labeled.yml
  .github/workflows/pr-notify.yml
  .github/workflows/pr-opend.yml
  .github/workflows/test-s2-react-components.yml
  .github/workflows/test-s2-react.yml
  .github/workflows/test-s2.yml
  README.md
  jest.config.base.js
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/package.json
  packages/s2-react-components/package.json
  packages/s2-react/__tests__/spreadsheet/__snapshots__/pagination-spec.tsx.snap
  packages/s2-react/__tests__/spreadsheet/pagination-spec.tsx
  packages/s2-react/package.json
  packages/s2-vue/package.json
  s2-site/docs/manual/contribution.zh.md
Labels: pr(chore), next

#3041 docs: 修复文档必选错位
  s2-site/docs/common/view-meta.zh.md
Labels: pr(documentation), next

#3042 fix: 修复明细表在 dataCfg 为空, 同时开启序号列时, 错误的渲染了占位符的问题
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/src/facet/table-facet.ts
  s2-site/docs/common/development.zh.md
Labels: pr(fix), next

#3046 fix: 修复明细表自定义列头时, 隐藏列头后出现空白区域 close #3044
  jest.config.base.js
  packages/s2-core/__tests__/data/custom-table-col-fields.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-table-col-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-table-col-spec.ts
  packages/s2-core/scripts/test-live.mjs
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-react/scripts/test-live.mjs
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
  s2-site/examples/interaction/advanced/demo/pivot-hide-columns.ts
  s2-site/examples/interaction/advanced/demo/table-hide-columns.ts
Labels: pr(fix), next

#3049 fix: 修复合并单元格滚动出可视范围后边框绘制错误 close #3048
  packages/s2-core/__tests__/bugs/issue-3048-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-cell-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/utils/interaction/merge-cell.ts
Labels: pr(fix), next

#3050 fix: 修复 Safari 浏览器复制/导出报错
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  s2-site/docs/common/copy-export.zh.md
Labels: pr(fix), next

#3051 fix: 修复切换到 4k 显示器时渲染模糊的问题
  packages/s2-core/src/ui/hd-adapter/index.ts
Labels: pr(fix), next

#3053 fix: 使用离屏 Canvas 测量文本, 提高宽度计算的准确性 close #3018
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/compare-layout-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/__tests__/unit/utils/canvas-spec.ts
  packages/s2-core/package.json
  packages/s2-core/scripts/test-live.mjs
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/canvas.ts
  packages/s2-react/playground/config.tsx
  packages/s2-react/scripts/test-live.mjs
  pnpm-lock.yaml
  s2-site/package.json
Labels: pr(fix), next
