Repository antvis/S2, pull requests merged in 2024-06, with the labels that each got.

#2763 fix: 修复 react 层对 frozen 的处理
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
Labels: pr(fix), next

#2765 docs: 修复通过 2.0 官网图表示例的 '在 CodeSandbox 中打开', 错误的安装了 1.x 版本的问题
  packages/s2-react/src/components/index.ts
  s2-site/.dumirc.ts
  s2-site/examples/analysis/sort/demo/advanced.tsx
  s2-site/examples/analysis/sort/demo/group-sort.tsx
  s2-site/examples/analysis/sort/demo/table-sort.tsx
  s2-site/examples/case/art/demo/lost-text.tsx
  s2-site/examples/case/art/demo/mosaic.tsx
  s2-site/examples/case/art/demo/time-spend-abstract.tsx
  s2-site/examples/case/comparison/demo/measure-comparison.tsx
  s2-site/examples/case/comparison/demo/multiple-people-comparison.tsx
  s2-site/examples/case/comparison/demo/philosophers.tsx
  s2-site/examples/case/comparison/demo/time-spend.tsx
  s2-site/examples/case/data-preview/demo/excel.tsx
  s2-site/examples/case/data-preview/demo/house.tsx
  s2-site/examples/case/data-preview/demo/index.tsx
  s2-site/examples/case/kpi-strategy/demo/basic.tsx
  s2-site/examples/case/kpi-strategy/demo/covid-trend.tsx
  s2-site/examples/case/performance-compare/demo/basic.tsx
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/case/proportion/demo/single-population-proportion.tsx
  s2-site/examples/custom/custom-order/demo/custom-order.tsx
  s2-site/examples/layout/adaptive/demo/react-adaptive.tsx
  s2-site/examples/react-component/drill-down/demo/basic-panel.tsx
  s2-site/examples/react-component/drill-down/demo/for-pivot.tsx
  s2-site/examples/react-component/export/demo/export.tsx
  s2-site/examples/react-component/header/demo/default.tsx
  s2-site/examples/react-component/pagination/demo/pivot.tsx
  s2-site/examples/react-component/pagination/demo/table.tsx
  s2-site/examples/react-component/sheet/demo/editable.tsx
  s2-site/examples/react-component/sheet/demo/pivot.tsx
  s2-site/examples/react-component/sheet/demo/strategy-mini-chart.tsx
  s2-site/examples/react-component/sheet/demo/strategy.tsx
  s2-site/examples/react-component/switcher/demo/pivot-header.tsx
  s2-site/examples/react-component/switcher/demo/pivot-with-children.tsx
  s2-site/examples/react-component/switcher/demo/pivot.tsx
  s2-site/examples/react-component/switcher/demo/pure-switcher.tsx
  s2-site/examples/react-component/switcher/demo/table.tsx
  s2-site/examples/react-component/tooltip/demo/basic.tsx
  s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-content-react.tsx
  s2-site/examples/react-component/tooltip/demo/custom-description.tsx
  s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-operation.tsx
  s2-site/examples/react-component/tooltip/demo/custom-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/operation.tsx
  s2-site/examples/theme/custom/demo/custom-generate-palette.tsx
  s2-site/examples/theme/custom/demo/custom-manual-palette.tsx
Labels: pr(documentation), next

#2762 feat(components): 组件层更新时增加 loading 效果 close #1790
  .prettierignore
  packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/facet/header/corner.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/sheet-type/table-sheet.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-react/__tests__/unit/hooks/usePivotSheetUpdate-spec.ts
  packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
  packages/s2-react/src/components/sheets/editable-sheet/custom-cell/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/sheets/pivot-sheet/index.tsx
  packages/s2-react/src/components/switcher/header.tsx
  packages/s2-react/src/hooks/usePagination.ts
  packages/s2-react/src/hooks/usePivotSheetUpdate.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  packages/s2-shared/src/interface.ts
  packages/s2-shared/src/utils/drill-down.ts
  packages/s2-shared/src/utils/resize.ts
  packages/s2-vue/src/hooks/usePagination.ts
  packages/s2-vue/src/hooks/useSheetUpdate.ts
  packages/s2-vue/src/hooks/useSpreadSheet.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/case/art/demo/lost-text.tsx
  s2-site/examples/react-component/sheet/demo/pivot.tsx
  s2-site/examples/react-component/sheet/demo/table.tsx
Labels: pr(feature), next

#2774 fix: 修复 headerActionIcons 下的 defaultHide 属性不生效 close #2772
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/icons/gui-icon.ts
  packages/s2-core/src/utils/interaction/state-controller.ts
Labels: pr(fix), next

#2777 refactor: 修复部分 circular deps
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/interface/export.ts
Labels: pr(refactor), next

#2779 feat(text-align-panel): 新增文字对齐配置组件
  packages/s2-react-components/__tests__/unit/components/common/tooltip-wrapper/__snapshots__/index-spec.tsx.snap
  packages/s2-react-components/__tests__/unit/components/common/tooltip-wrapper/index-spec.tsx
  packages/s2-react-components/__tests__/unit/components/config/text-align-panel/__snapshots__/index-spec.tsx.snap
  packages/s2-react-components/__tests__/unit/components/config/text-align-panel/index-spec.tsx
  packages/s2-react-components/__tests__/unit/components/config/theme-panel/__snapshots__/index-spec.tsx.snap
  packages/s2-react-components/playground/index.less
  packages/s2-react-components/playground/index.tsx
  packages/s2-react-components/playground/utils.ts
  packages/s2-react-components/src/common/index.ts
  packages/s2-react-components/src/common/interface/components.ts
  packages/s2-react-components/src/common/interface/icon.ts
  packages/s2-react-components/src/common/interface/index.ts
  packages/s2-react-components/src/components/common/index.ts
  packages/s2-react-components/src/components/common/tooltip-wrapper/index.tsx
  packages/s2-react-components/src/components/common/tooltip-wrapper/interface.ts
  packages/s2-react-components/src/components/config/index.ts
  packages/s2-react-components/src/components/config/text-align-panel/icons.tsx
  packages/s2-react-components/src/components/config/text-align-panel/index.less
  packages/s2-react-components/src/components/config/text-align-panel/index.tsx
  packages/s2-react-components/src/components/config/text-align-panel/interface.ts
  packages/s2-react-components/src/components/config/text-align-panel/utils.ts
  packages/s2-react-components/src/components/config/theme-panel/icons.tsx
  packages/s2-react-components/src/components/config/theme-panel/index.tsx
  packages/s2-react-components/src/components/config/theme-panel/interface.ts
  packages/s2-shared/src/constant/i18n/en_US.ts
  packages/s2-shared/src/constant/i18n/zh_CN.ts
Labels: pr(feature), next

#2783 feat(type): 使用 Template Literal Types 增强枚举类型的提示
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/events.ts
  packages/s2-core/src/common/interface/export.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/common/interface/resize.ts
  packages/s2-core/src/common/interface/s2DataConfig.ts
  packages/s2-core/src/common/interface/style.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/config.tsx
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/basic/theme.zh.md
Labels: pr(feature), next

#2782 feat(frozen-panel): 增加行列头冻结配置面板
  package.json
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-react-components/__tests__/unit/components/config/frozen-panel/__snapshots__/index-spec.tsx.snap
  packages/s2-react-components/__tests__/unit/components/config/frozen-panel/frozen-input-number/__snapshots__/index-spec.tsx.snap
  packages/s2-react-components/__tests__/unit/components/config/frozen-panel/frozen-input-number/index-spec.tsx
  packages/s2-react-components/__tests__/unit/components/config/frozen-panel/index-spec.tsx
  packages/s2-react-components/playground/config.tsx
  packages/s2-react-components/playground/index.tsx
  packages/s2-react-components/src/components/config/frozen-panel/frozen-input-number/index.tsx
  packages/s2-react-components/src/components/config/frozen-panel/frozen-input-number/interface.ts
  packages/s2-react-components/src/components/config/frozen-panel/index.less
  packages/s2-react-components/src/components/config/frozen-panel/index.tsx
  packages/s2-react-components/src/components/config/frozen-panel/interface.ts
  packages/s2-react-components/src/components/config/index.ts
  packages/s2-shared/src/constant/i18n/en_US.ts
  packages/s2-shared/src/constant/i18n/zh_CN.ts
Labels: pr(feature), next

#2787 docs: 修复关于默认字体的错误描述 close #2786
  packages/s2-core/src/common/icons/svg/svgs.ts
  packages/s2-core/src/ui/tooltip/index.less
  s2-site/docs/api/general/S2Theme.en.md
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(documentation), next
