Repository antvis/S2, pull requests merged in 2024-02, with the labels that each got.

#2540 docs: 修复官网导航栏样式异常
  s2-site/.dumi/global.less
  s2-site/.dumi/global.ts
Labels: pr(documentation)

#2544 fix: 修复表格排序后, 编辑单元格后数据更新错误 close #2573
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/drag-copy-mask.tsx
  packages/s2-react/src/components/sheets/editable-sheet/drag-copy/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
Labels: pr(fix)

#2546 fix: 回退生成 nodeId 时对 extra 字段的格式化
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-dataset-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-value-order-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-dataset-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-value-order-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/copy-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/util/fp.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  s2-site/examples/interaction/advanced/demo/pivot-hide-columns.ts
Labels: pr(fix), next

#2547 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
  packages/s2-vue/CHANGELOG.md
  packages/s2-vue/package.json
Labels: pr(chore)

#2556 fix(scroll): 修复移动端滚动至边缘时抖动
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix)

#2551 fix: 修复自定义目录树同名节点展示异常 & 导出缺失角头 close #2455
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-cell-style-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-tree-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-cell-style-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-grid-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-table-col-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-tree-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/tooltip-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/copy-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/pivot-header-copy.ts
  packages/s2-core/src/utils/export/method.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
  packages/s2-react/__tests__/data/custom-tree-fields.ts
  packages/s2-react/__tests__/unit/components/header/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/strategy-sheet/index-spec.tsx
  packages/s2-react/playground/components/CustomGrid.tsx
  packages/s2-react/playground/components/CustomTree.tsx
  packages/s2-react/playground/context/playground.context.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/export/index.tsx
  packages/s2-react/src/components/export/strategy-copy.ts
  packages/s2-react/src/components/header/index.tsx
  s2-site/docs/api/basic-class/node.zh.md
Labels: pr(fix), next

#2545 fix(interaction): 修复表格滚动后, 行列头部分单元格选中高亮效果丢失 close #2503
  packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/config.ts
Labels: pr(fix)

#2549 fix: 修复编辑表的输入框未回填格式化后的数据 close #2528
  packages/s2-core/__tests__/bugs/issue-2528-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/data-set/base-data-set.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/editable-sheet/index.tsx
  packages/s2-shared/src/interface.ts
  s2-site/docs/api/basic-class/base-cell.en.md
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/basic/analysis/editable-mode.zh.md
  s2-site/examples/react-component/sheet/demo/editable.tsx
Labels: pr(fix)

#2559 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore), 🚨 test failed

#2565 fix: 修复父容器存在 transform 缩放时单元格刷选偏移 close #2553
  packages/s2-core/__tests__/unit/interaction/brush-selection/base-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/col-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/data-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/brush-selection/row-brush-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/tooltip.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-react/playground/components/CustomTree.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
Labels: pr(fix), next

#2566 feat: 移除已废弃的方法和逻辑 & 优化文档
  packages/s2-core/__tests__/bugs/issue-2340-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/utils/text-spec.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/layout/build-row-tree-hierarchy.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/export/copy/core.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/utils.ts
  packages/s2-core/src/utils/g-mini-charts.ts
  packages/s2-core/src/utils/text.ts
  packages/s2-react/__tests__/unit/components/sheets/chart-sheet/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/__snapshots__/index-spec.tsx.snap
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/index-spec.tsx
  packages/s2-react/__tests__/unit/components/sheets/mobile-sheet/mobile-tooltip-spec.tsx
  packages/s2-react/__tests__/unit/components/tooltip/index-spec.tsx
  packages/s2-react/playground/components/Mobile.tsx
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/index.ts
  packages/s2-react/src/components/sheets/editable-sheet/custom-cell/edit-cell/index.tsx
  packages/s2-react/src/components/sheets/mobile-sheet/index.tsx
  packages/s2-shared/__tests__/utils/options-spec.ts
  packages/s2-shared/src/utils/options.ts
  packages/s2-vue/src/hooks/useSpreadSheet.ts
  packages/s2-vue/src/utils/initPropAndEmits.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/general/S2Options.zh.md
  s2-site/docs/manual/advanced/analysis/mobile-component.en.md
  s2-site/docs/manual/advanced/analysis/mobile-component.zh.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/docs/manual/getting-started.en.md
  s2-site/docs/manual/getting-started.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.ts
  s2-site/examples/custom/custom-icon/demo/meta.json
  s2-site/examples/custom/custom-layout/demo/custom-facet.ts
  s2-site/examples/react-component/sheet/demo/mobile-pivot.tsx
  s2-site/examples/react-component/tooltip/demo/custom-content-base.ts
  s2-site/examples/theme/custom/demo/custom-scrollbar.ts
Labels: pr(feature), next

#2568 feat: 明细表支持同名列渲染 closes #2502 #2510
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-cell-style-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-facet-layout-api-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/spread-sheet-facet-layout-api-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/copy-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
Labels: pr(feature), next

#2562 fix: 角头选中列兼容树状模式和自定义行头场景
  packages/s2-core/__tests__/spreadsheet/interaction-corner-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
Labels: pr(fix), 🚨 test failed, next
