Repository antvis/S2, pull requests merged in 2024-08, with the labels that each got.

#2853 feat(i18n): add support of the russian language
  packages/s2-core/__tests__/unit/common/i18n/index-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/common/i18n/index.ts
  packages/s2-core/src/common/i18n/ru.ts
  packages/s2-shared/src/constant/i18n/index.ts
  packages/s2-shared/src/constant/i18n/ru.ts
  s2-site/docs/manual/basic/i18n.en.md
Labels: pr(feature)

#2862 feat(i18n): add formatter support of the russian language
  packages/s2-core/__tests__/unit/common/i18n/index-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/common/i18n/index.ts
  packages/s2-core/src/common/i18n/ru_RU.ts
  packages/s2-core/src/utils/formatter.ts
  packages/s2-react/src/components/sheets/index.tsx
  packages/s2-shared/src/constant/i18n/index.ts
  packages/s2-shared/src/constant/i18n/ru_RU.ts
  s2-site/docs/manual/basic/i18n.en.md
  s2-site/docs/manual/basic/i18n.zh.md
Labels: pr(feature)

#2868 docs: 完善 ViewMeta 和 CellData 文档 close #2845
  packages/s2-core/src/data-set/cell-data.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  s2-site/docs/api/basic-class/base-data-set.zh.md
  s2-site/docs/api/basic-class/cell-data.en.md
  s2-site/docs/api/basic-class/cell-data.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/general/S2DataConfig.zh.md
  s2-site/docs/common/custom/layoutCellMeta.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/common/view-meta.zh.md
  s2-site/docs/manual/advanced/get-cell-data.zh.md
  s2-site/docs/manual/basic/sort/basic.zh.md
  s2-site/docs/manual/extended-reading/data-process/pivot.zh.md
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(documentation), next

#2864 fix: 修复在明细表中绘制 G2 图表, 点击单元格报错 close #2843
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/utils/tooltip.ts
  s2-site/docs/manual/advanced/chart-in-cell.zh.md
Labels: pr(fix), next

#2869 fix: 修复自定义列头导出数据时, 角头文本展示错误 close #2844
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
Labels: pr(fix), next

#2871 fix: 修复在局部复制和导出场景时, 格式化函数获取不到单元格信息 close #2866
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  s2-site/docs/api/basic-class/base-facet.zh.md
Labels: pr(fix), next

#2865 feat: 导出组件支持复制 HTML (text/html) 格式的数据 close #2828
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/export-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/interface/export.ts
  packages/s2-core/src/utils/export/utils.ts
  packages/s2-react/src/components/export/index.tsx
  s2-site/docs/api/components/export.zh.md
  s2-site/docs/common/copy-export.zh.md
  s2-site/docs/manual/advanced/analysis/export.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/interaction/basic/demo/copy-export.ts
Labels: pr(feature), next
