Repository antvis/S2, pull requests merged in 2024-03, with the labels that each got.

#2569 docs: 更新 G 链接
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.zh.md
  s2-site/docs/api/graphic.zh.md
  s2-site/docs/manual/advanced/custom/hook.zh.md
  s2-site/docs/manual/basic/conditions.zh.md
Labels: pr(documentation), next

#2570 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
Labels: pr(chore)

#2581 docs: 补充绘制自定义 G 图形文档
  s2-site/docs/manual/advanced/chart-in-cell.zh.md
  s2-site/examples/custom/custom-g2-chart/demo/meta.json
  s2-site/examples/custom/custom-g2-chart/index.en.md
  s2-site/examples/custom/custom-g2-chart/index.zh.md
  s2-site/examples/custom/custom-shape-and-chart/API.en.md
  s2-site/examples/custom/custom-shape-and-chart/API.zh.md
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g-shape.ts
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g2-chart.ts
  s2-site/examples/custom/custom-shape-and-chart/demo/meta.json
  s2-site/examples/custom/custom-shape-and-chart/index.en.md
  s2-site/examples/custom/custom-shape-and-chart/index.zh.md
Labels: pr(documentation), next

#2571 feat: 增加角头和序号列的交互能力
  packages/s2-core/__tests__/README.md
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-facet-layout-api-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-corner-click-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-facet-layout-api-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-tree-mode-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/hover-event-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/series-number-cell.ts
  packages/s2-core/src/cell/table-data-cell.ts
  packages/s2-core/src/facet/header/util.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/interaction/hover-event.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-react/__tests__/README.md
  packages/s2-react/__tests__/unit/components/pagination/index-spec.tsx
  packages/s2-react/playground/README.md
  packages/s2-react/playground/config.tsx
  packages/s2-react/playground/index.tsx
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/contribution.zh.md
  s2-site/examples/custom/custom-icon/demo/custom-tree-icon.ts
  s2-site/examples/custom/custom-icon/demo/meta.json
  s2-site/examples/interaction/basic/demo/corner-cell-click-selection.ts
  s2-site/examples/interaction/basic/demo/event.ts
  s2-site/examples/interaction/basic/demo/meta.json
Labels: pr(feature), next

#2580 feat(interaction): 支持批量调整行高列宽 close #2574
  packages/s2-core/__tests__/unit/interaction/__snapshots__/row-column-resize-spec.ts.snap
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/constant/resize.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-react/__tests__/unit/components/pagination/index-spec.tsx
  packages/s2-react/playground/config.tsx
  s2-site/docs/api/basic-class/base-facet.zh.md
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/resize.zh.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/interaction/basic/demo/meta.json
  s2-site/examples/interaction/basic/demo/resize-selected.ts
  s2-site/examples/interaction/basic/demo/resize.ts
Labels: pr(feature), next

#2590 fix: 修复树状模式下开启分页, 行头展开收起后表格渲染异常 close #2582
  .github/workflows/issue-labeled.yml
  .github/workflows/pr-labeled.yml
  packages/s2-core/__tests__/bugs/issue-2582-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-react/playground/config.ts
  packages/s2-react/playground/index.tsx
Labels: pr(fix)

#2598 fix: 修复文本行数不一致时自动换行高度自适应失效 close #2594
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/data-process/table-spec.tsx
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/layout/node.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-react/src/components/export/strategy-copy.ts
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/docs/manual/basic/multi-line-text.zh.md
  s2-site/examples/layout/custom/demo/custom-pivot-size.ts
  s2-site/examples/layout/custom/demo/custom-table-size.ts
  s2-site/examples/layout/custom/demo/custom-tree-row-width.ts
  s2-site/examples/layout/custom/demo/hide-pivot-columns.ts
  s2-site/examples/layout/custom/demo/hide-table-columns.ts
  s2-site/examples/layout/custom/demo/meta.json
  s2-site/examples/layout/multi-line-text/API.en.md
  s2-site/examples/layout/multi-line-text/API.zh.md
  s2-site/examples/layout/multi-line-text/demo/meta.json
  s2-site/examples/layout/multi-line-text/demo/pivot.ts
  s2-site/examples/layout/multi-line-text/demo/table.ts
  s2-site/examples/layout/multi-line-text/index.en.md
  s2-site/examples/layout/multi-line-text/index.zh.md
Labels: pr(fix), next

#2600 chore: 单测调试支持跨平台
  packages/s2-core/scripts/test-live.mjs
  packages/s2-react/scripts/test-live.mjs
Labels: pr(chore)

#2601 chore: 🤖 更新 changelog 文件
  packages/s2-core/CHANGELOG.md
  packages/s2-core/package.json
  packages/s2-react/CHANGELOG.md
  packages/s2-react/package.json
Labels: pr(chore)

#2606 fix(g): 修复表格初次渲染时部分 icon 不展示 close #2014
  packages/s2-core/package.json
  packages/s2-react/package.json
  pnpm-lock.yaml
Labels: pr(fix), next

#2616 fix: 修复组件层事件回调无法获取单元格信息 closes #2615 #2610
  packages/s2-core/__tests__/unit/utils/interaction/__snapshots__/formatter-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/interaction/formatter-spec.ts
  packages/s2-core/src/utils/interaction/formatter.ts
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/case/comparison/demo/philosophers.tsx
  s2-site/examples/case/proportion/demo/group-drill-down.tsx
  s2-site/examples/react-component/tooltip/demo/custom-click-show-tooltip.tsx
  s2-site/examples/react-component/tooltip/demo/custom-hover-show-tooltip.tsx
Labels: pr(fix), next

#2605 fix(interaction): 修复在未选中状态下调整宽高, 错误的修改了相邻单元格的样式
  packages/s2-core/__tests__/unit/interaction/__snapshots__/row-column-resize-spec.ts.snap
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  s2-site/docs/api/basic-class/base-cell.zh.md
  s2-site/docs/api/graphic.zh.md
  s2-site/docs/common/contact-us.zh.md
  s2-site/examples/custom/custom-cell/demo/custom-specified-cell.ts
Labels: pr(fix), next

#2620 fix: 修复角头和行头折叠展开 icon 的状态未同步以及展开异常的问题 close #2607
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-collapse-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/sheet-type/pivot-sheet.ts
  packages/s2-react/playground/components/CustomTree.tsx
  packages/s2-react/playground/config.tsx
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(fix), next

#2623 refactor: 去除多余的 TotalsStatus，只保留 TotalStatus
  packages/s2-core/__tests__/unit/data-set/pivot-data-set-total-spec.ts
  packages/s2-core/__tests__/unit/utils/data-set-operate-spec.tsx
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/data-set/interface.ts
  packages/s2-core/src/data-set/pivot-data-set.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/utils/data-set-operate.ts
  packages/s2-core/src/utils/dataset/pivot-data-set.ts
Labels: pr(refactor), next

#2626 docs: 修正 tooltip 和下钻demo 文档
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/react-component/drill-down/demo/for-pivot.tsx
Labels: pr(documentation), 🚨 test failed, next

#2628 refactor: 重构 on 和 emit 类型
  packages/s2-core/src/sheet-type/spread-sheet.ts
Labels: pr(refactor), next

#2629 更新至 G 最新版本
  packages/s2-core/__tests__/unit/common/icons/gui-icon-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/package.json
  packages/s2-react/__tests__/unit/components/sheets/chart-sheet/index-spec.tsx
  packages/s2-react/package.json
  packages/s2-react/playground/components/ChartSheet.tsx
  pnpm-lock.yaml
  s2-site/package.json
Labels: 🚨 test failed

#2637 docs: 补充宽高调整文档
  s2-site/docs/manual/advanced/interaction/resize.zh.md
  s2-site/examples/interaction/basic/demo/event.ts
  s2-site/examples/interaction/basic/demo/resize.ts
Labels: pr(documentation), next

#2633 fix: 调整 peerDependencies 命中规则
  packages/s2-react/package.json
  packages/s2-vue/package.json
Labels: pr(fix), next

#2630 fix: 调整换行高度自适应和自定义高度的优先级 close #2613
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  s2-site/docs/manual/advanced/custom/cell-size.zh.md
  s2-site/docs/manual/basic/multi-line-text.zh.md
  s2-site/examples/layout/custom/demo/custom-table-size.ts
Labels: pr(fix), next

#2632 fix: 修复紧凑模式下数值单元格错误的展示了省略号
  packages/s2-core/__tests__/bugs/issue-2385-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/merge-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/merge.ts
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(fix), next
