Repository antvis/S2, pull requests merged in 2024-11, with the labels that each got.

#2956 feat: 增加不同类型单元格的选中事件 & 支持识别事件来源
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-cell-selected-event-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/interaction/__snapshots__/root-spec.ts.snap
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/data-cell-multi-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/event-controller-spec.ts
  packages/s2-core/__tests__/unit/interaction/range-selection-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/utils/interaction/select-event-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/interaction.ts
  packages/s2-core/src/interaction/base-event.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/brush-selection/base-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/col-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/data-cell-brush-selection.ts
  packages/s2-core/src/interaction/brush-selection/row-brush-selection.ts
  packages/s2-core/src/interaction/data-cell-multi-selection.ts
  packages/s2-core/src/interaction/event-controller.ts
  packages/s2-core/src/interaction/range-selection.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/interaction/selected-cell-move.ts
  packages/s2-core/src/utils/interaction/select-event.ts
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
  packages/s2-shared/src/interface.ts
  packages/s2-vue/src/hooks/useEvents.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/api/general/S2Event.zh.md
  s2-site/docs/common/interaction.zh.md
  s2-site/examples/analysis/get-data/demo/get-cell-data.ts
  s2-site/examples/interaction/basic/demo/brush-header.ts
  s2-site/examples/interaction/basic/demo/corner-cell-click-selection.ts
  s2-site/examples/interaction/basic/demo/data-cell-click-selection.ts
  s2-site/examples/interaction/basic/demo/data-cell-range-selection.ts
  s2-site/examples/interaction/basic/demo/event.ts
  s2-site/examples/interaction/basic/demo/header-cell-click-selection.ts
  s2-site/examples/interaction/basic/demo/selected-cell-move.ts
Labels: pr(feature), next

#2953 feat: 优化紧凑模式下的单元格宽度计算方式
  packages/s2-core/__tests__/bugs/issue-2726-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-frozen-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/table-sheet-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/compare-layout-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/merge-spec.ts.snap
  packages/s2-core/src/common/constant/resize.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/utils/condition/condition.ts
  packages/s2-react/playground/config.tsx
  packages/s2-shared/__tests__/unit/utils/__snapshots__/options-spec.ts.snap
  s2-site/docs/common/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/resize.zh.md
  s2-site/examples/interaction/basic/demo/resize.ts
Labels: pr(feature), next

#2960 fix: 修复文本设为左对齐时, 角头文本没有垂直对齐的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/corner-spec.ts
  packages/s2-core/src/cell/corner-cell.ts
Labels: pr(fix), 🚨 test failed, next

#2961 fix: 修复分割线在深色背景下颜色渲染异常 & 内容宽高未包含分割线的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/__tests__/unit/sheet-type/table-sheet-spec.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/facet/bbox/panel-bbox.ts
  packages/s2-core/src/facet/header/frame.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-react-components/__tests__/unit/components/config/theme-panel/__snapshots__/utils-spec.ts.snap
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(fix), next

#2965 fix: 修复表格卸载后, 高清适配逻辑还会触发的问题
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/ui/hd-adapter/index.ts
Labels: pr(fix), next

#2969 docs: 优化 spreadsheet class api 文档
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/general/S2Theme.zh.md
  s2-site/examples/custom/custom-icon/demo/custom-header-action-icon.ts
Labels: pr(documentation), next

#2966 fix: 修复开启自定义指标层级后, 角头数值文本未对齐 close #2957
  packages/s2-core/__tests__/bugs/issue-2957-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/src/theme/index.ts
  packages/s2-react-components/__tests__/unit/components/config/theme-panel/__snapshots__/utils-spec.ts.snap
  packages/s2-react-components/package.json
  s2-site/docs/api/general/S2Theme.zh.md
Labels: pr(fix), next

#2968 fix: 修复明细表自定义列头时开启文本换行, 单元格高度错误的问题 close #2955
  packages/s2-core/__tests__/data/custom-table-col-fields.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), 🚨 test failed, next

#2973 fix: 修复表格卸载时 G 图形实例未销毁的问题
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), next

#2972 fix: 修复紧凑模式下, 文本带有 '\n' 换行符时 maxLines 配置未生效和文本溢出的问题 closes #2963 #2900
  packages/s2-core/__tests__/data/data-issue-2385.json
  packages/s2-core/__tests__/spreadsheet/compare-layout-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/merge-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/merge.ts
Labels: pr(fix), next

#2970 feat: 调整单元格默认 padding, 优化多行文本时的展示效果
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/theme-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/theme/index.ts
  packages/s2-react-components/__tests__/unit/components/config/theme-panel/__snapshots__/utils-spec.ts.snap
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(feature), next

#2971 fix: 减少开启 ReactDOM.unstable_batchedUpdates 后的重渲染次数
  packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts
  packages/s2-core/src/common/interface/s2Options.ts
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-react/__tests__/unit/hooks/useSpreadSheet-spec.ts
  packages/s2-react/src/hooks/useSpreadSheet.ts
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/manual/migration-v2.zh.md
Labels: pr(fix), next

#2978 fix: 修复文本存在换行符时, 未显示省略号的问题
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/package.json
  packages/s2-react/package.json
  pnpm-lock.yaml
  s2-site/package.json
Labels: pr(fix), next

#2903 feat: vue 支持编辑表模式
  packages/s2-vue/playground/App.vue
  packages/s2-vue/src/components/sheets/base-sheet.vue
  packages/s2-vue/src/components/sheets/editable-sheet.vue
  packages/s2-vue/src/components/sheets/index.vue
  packages/s2-vue/src/hooks/useSpreadSheet.ts
Labels: pr(feature), next

#2988 refactor: 调整暗黑主题样式的加载方式, 避免样式污染和构建错误
  .github/workflows/prerelease-notify.yml
  .github/workflows/release-notify.yml
  build.config.base.mjs
  packages/s2-core/__tests__/spreadsheet/tooltip-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/rollup.config.mjs
  packages/s2-core/src/common/constant/theme.ts
  packages/s2-core/src/shared/constant/theme.ts
  packages/s2-core/src/shared/styles/theme/dark.less
  packages/s2-core/src/shared/styles/tooltip/operator.less
  packages/s2-core/src/sheet-type/spread-sheet.ts
  packages/s2-core/src/styles/theme/dark.less
  packages/s2-core/src/ui/tooltip/index.less
  packages/s2-core/src/ui/tooltip/index.ts
  packages/s2-core/src/utils/theme.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/components/sheets/base-sheet/index.tsx
Labels: pr(refactor), 🚨 test failed, next

#2999 fix: 修复 react, vue component 层的 svg 问题 close #2990
  packages/s2-react-components/src/components/common/icons/calendar-icon.tsx
  packages/s2-react-components/src/components/common/icons/col-icon.tsx
  packages/s2-react-components/src/components/common/icons/index.tsx
  packages/s2-react-components/src/components/common/icons/location-icon.tsx
  packages/s2-react-components/src/components/common/icons/row-icon.tsx
  packages/s2-react-components/src/components/common/icons/svg/calendar-icon.svg
  packages/s2-react-components/src/components/common/icons/svg/col-icon.svg
  packages/s2-react-components/src/components/common/icons/svg/location-icon.svg
  packages/s2-react-components/src/components/common/icons/svg/row-icon.svg
  packages/s2-react-components/src/components/common/icons/svg/text-icon.svg
  packages/s2-react-components/src/components/common/icons/svg/value-icon.svg
  packages/s2-react-components/src/components/common/icons/text-icon.tsx
  packages/s2-react-components/src/components/common/icons/value-icon.tsx
  packages/s2-react-components/vite.config.ts
  packages/s2-vue/package.json
  packages/s2-vue/playground/App.vue
  packages/s2-vue/src/components/drill-down/index.vue
  packages/s2-vue/src/icons/calendar-icon.vue
  packages/s2-vue/src/icons/location-icon.vue
  packages/s2-vue/src/icons/text-icon.vue
  packages/s2-vue/src/svg/calendar-icon.svg
  packages/s2-vue/src/svg/location-icon.svg
  packages/s2-vue/src/svg/text-icon.svg
  packages/s2-vue/vite.config.ts
  pnpm-lock.yaml
Labels: pr(fix), next

#3000 fix: 修复行头底部存在多行文本, 初始化和滚动时文本展示溢出的问题
  packages/s2-core/src/cell/row-cell.ts
Labels: pr(fix), next

#3001 fix(tooltip): 修复操作按钮的 visible 对角头和文本溢出场景不生效
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/corner-cell-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/hover-spec.ts
  packages/s2-core/src/interaction/base-event.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/interaction/base-interaction/hover.ts
  packages/s2-react/playground/config.tsx
Labels: pr(fix), next

#2998 feat: 增加树状模式下行头宽度配置 rowCell.treeWidth
  .github/workflows/test.yml
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-cell-style-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/custom-cell-style-spec.ts
  packages/s2-core/__tests__/spreadsheet/custom-tree-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/__tests__/unit/interaction/row-column-resize-spec.ts
  packages/s2-core/src/common/constant/options.ts
  packages/s2-core/src/common/interface/style.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/indexes.ts
  packages/s2-core/src/utils/tooltip.ts
  packages/s2-react-components/__tests__/unit/components/drill-down/__snapshots__/drill-down-spec.tsx.snap
  packages/s2-react/__tests__/spreadsheet/adaptive-spec.tsx
  s2-site/docs/common/style.zh.md
  s2-site/docs/manual/migration-v2.en.md
  s2-site/docs/manual/migration-v2.zh.md
  s2-site/examples/layout/custom/demo/custom-tree-row-width.ts
  s2-site/examples/layout/frozen/demo/pivot-frozen-row-header.ts
Labels: pr(feature), 🚨 test failed, next

#3003 fix: 明细表未指定 dataCfg.fields 配置时不应该渲染空数据占位
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/frozen-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), next
