Repository antvis/S2, pull requests merged in 2025-04, with the labels that each got.

#3142 fix: 明细表自定义列头prefix重复展示异常
  packages/s2-core/__tests__/data/custom-table-col-fields.ts
  packages/s2-core/__tests__/spreadsheet/custom-table-col-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), next

#3132 docs: 官网 SEO 优化
  pnpm-lock.yaml
  s2-site/.dumi/global.ts
  s2-site/.dumi/pages/playground.zh.tsx
  s2-site/.dumirc.ts
  s2-site/.gitignore
  s2-site/docs/api/basic-class/base-cell.en.md
  s2-site/docs/api/basic-class/base-data-set.en.md
  s2-site/docs/api/basic-class/base-facet.en.md
  s2-site/docs/api/basic-class/spreadsheet.en.md
  s2-site/docs/api/basic-class/spreadsheet.zh.md
  s2-site/docs/api/basic-class/store.en.md
  s2-site/docs/api/components/advanced-sort.en.md
  s2-site/docs/api/components/sheet-component.en.md
  s2-site/docs/api/components/sheet-component.zh.md
  s2-site/docs/common/totals.en.md
  s2-site/docs/manual/advanced/custom/cell-align.en.md
  s2-site/docs/manual/advanced/custom/cell-size.en.md
  s2-site/docs/manual/advanced/custom/custom-header.en.md
  s2-site/docs/manual/advanced/custom/custom-header.zh.md
  s2-site/docs/manual/advanced/custom/custom-order.en.md
  s2-site/docs/manual/advanced/sheet/strategy.en.md
  s2-site/docs/manual/advanced/sheet/strategy.zh.md
  s2-site/docs/manual/basic/conditions.en.md
  s2-site/docs/manual/basic/sort/basic.en.md
  s2-site/docs/manual/basic/theme.en.md
  s2-site/docs/manual/basic/tooltip.en.md
  s2-site/docs/manual/basic/totals.en.md
  s2-site/docs/manual/faq.en.md
  s2-site/mako.config.json
  s2-site/package.json
  s2-site/playground/dataset/mock-dataset.json
  s2-site/playground/layouts/index.tsx
  s2-site/playground/sheet-component/config.ts
  s2-site/playground/sheet-component/index.tsx
Labels: pr(documentation), next

#3141 fix: 修复移动端点击事件触发多次
  packages/s2-core/src/common/constant/events/origin.ts
  packages/s2-core/src/interaction/event-controller.ts
Labels: pr(fix), next

#3146 docs: 恢复google analytics
  s2-site/.dumirc.ts
Labels: pr(documentation), next

#3147 chore: Upgrade d3 packages to fix ERR_REQUIRE_ESM
  packages/s2-core/__tests__/util/helpers.ts
  packages/s2-core/package.json
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/mobile/wheelEvent.ts
  packages/s2-react/__tests__/util/helpers.ts
  packages/s2-react/package.json
  pnpm-lock.yaml
Labels: pr(chore), next

#3151 docs: 修正示例文件路径
  s2-site/docs/manual/advanced/adaptive.zh.md
  s2-site/docs/manual/advanced/analysis/drill-down.en.md
  s2-site/docs/manual/advanced/analysis/switcher.en.md
  s2-site/docs/manual/advanced/custom/custom-header.en.md
  s2-site/docs/manual/advanced/custom/custom-icon.en.md
  s2-site/docs/manual/advanced/custom/custom-icon.zh.md
  s2-site/docs/manual/basic/sheet-type/table-mode.en.md
Labels: pr(documentation), next
