Repository antvis/S2, pull requests merged in 2025-02, with the labels that each got.

#3090 chore: 适配 Windows 环境
  package.json
  packages/s2-core/package.json
  packages/s2-react-components/package.json
  packages/s2-react/package.json
  packages/s2-vue/package.json
  pnpm-lock.yaml
Labels: pr(chore), next

#3089 fix: 多行文本二次渲染后少一行
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/cell/base-cell.ts
Labels: pr(fix), next

#3094 docs: 修复官网导航栏跳转异常
  pnpm-lock.yaml
  s2-site/.dumirc.ts
  s2-site/package.json
Labels: pr(documentation), next

#3093 fix: 导出复制时处理特殊字符
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/copy-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/method-spec.ts
  packages/s2-core/src/utils/export/copy/base-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts
  packages/s2-core/src/utils/export/copy/table-copy.ts
  packages/s2-core/src/utils/export/method.ts
  s2-site/docs/common/copy-export.en.md
  s2-site/docs/common/copy-export.zh.md
  s2-site/docs/manual/extended-reading/layout/pivot.zh.md
  s2-site/docs/manual/extended-reading/performance.en.md
  s2-site/docs/manual/extended-reading/performance.zh.md
Labels: pr(fix), next

#3097 fix: 修复移动端禁用外部容器滚动不生效
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), next

#3099 docs: 修复Tooltip相关示例
  s2-site/docs/manual/advanced/chart-with-g2.zh.md
  s2-site/docs/manual/basic/multi-line-text.zh.md
  s2-site/docs/manual/basic/tooltip.en.md
  s2-site/docs/manual/basic/tooltip.zh.md
  s2-site/examples/react-component/tooltip/demo/custom-show-tooltip.tsx
Labels: pr(documentation), next

#3102 fix: 修复透视表尾列隐藏后的展开icon位置异常
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: pr(fix), next

#3103 fix: 修复前后节点都被隐藏的尾列展开icon位置异常和展开节点异常
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: pr(fix), next

#3105 feat: 新增隐藏列展开按钮hover事件
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/shared/interface.ts
  packages/s2-core/src/utils/hide-columns.ts
  packages/s2-react/__tests__/unit/hooks/useEvents-spec.ts
  packages/s2-react/playground/index.tsx
  packages/s2-react/src/hooks/useEvents.ts
Labels: pr(feature), next

#3106 docs: 补充列头展开按钮hover事件文档
  s2-site/docs/manual/advanced/interaction/basic.zh.md
  s2-site/docs/manual/advanced/interaction/hide-columns.zh.md
Labels: pr(documentation), next

#3109 fix: 在ios 14.8.1中正则前瞻和后顾存在兼容问题
  packages/s2-core/src/utils/export/method.ts
Labels: pr(fix), next

#3114 fix: 列头换行，隐藏采样节点后，列头高度异常
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/utils/layout/generate-header-nodes.ts
Labels: pr(fix), next

#3112 fix: 修复隐藏列后变更列顺序，隐藏列展开异常
  packages/s2-core/__tests__/data/mock-dataset-multi-measure.json
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/row-column-click-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts
  packages/s2-core/src/interaction/base-interaction/click/row-column-click.ts
  packages/s2-core/src/utils/hide-columns.ts
Labels: pr(fix), next

#3115 fix: 避免getIntervalScale除0异常
  packages/s2-core/__tests__/unit/utils/condition/condition-spec.ts
  packages/s2-core/src/utils/condition/condition.ts
Labels: pr(fix), next
