Repository antvis/S2, pull requests merged in 2025-01, with the labels that each got.

#3060 fix(g): 修复列宽很小时多行文本渲染错误
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/package.json
  pnpm-lock.yaml
Labels: pr(fix), next

#3061 fix: 修复存在字段标记时, 紧凑模式下有几率显示省略号的问题
  packages/s2-core/__tests__/spreadsheet/compare-layout-spec.ts
  packages/s2-core/src/facet/pivot-facet.ts
Labels: pr(fix), next

#3063 docs: 修复导出组件示例报错 close #3059
  s2-site/docs/manual/advanced/get-instance.zh.md
  s2-site/examples/react-component/export/demo/export-strategy.tsx
  s2-site/examples/react-component/export/demo/export.tsx
Labels: pr(documentation), next

#3064 fix: 修复自定义选中交互主题对行列叶子节点不生效
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/src/interaction/base-interaction/click/corner-cell-click.ts
  packages/s2-core/src/interaction/root.ts
  s2-site/docs/api/basic-class/interaction.zh.md
  s2-site/docs/manual/advanced/interaction/highlight-and-select-cell.zh.md
Labels: pr(fix), next

#3065 fix: 修复表头存在自定义 icon 时, 文本换行高度自适应不准确
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-react/playground/config.tsx
  packages/s2-react/playground/index.tsx
Labels: pr(fix), next

#3066 fix: 修复单元格宽度为浮点数时单元格之间有几率出现多余空隙的问题 close #3014
  packages/s2-core/__tests__/bugs/__snapshots__/issue-446-spec.ts.snap
  packages/s2-core/__tests__/bugs/issue-2501-spec.ts
  packages/s2-core/__tests__/bugs/issue-3014-spec.ts
  packages/s2-core/__tests__/bugs/issue-446-spec.ts
  packages/s2-core/__tests__/spreadsheet/__snapshots__/corner-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-cell-style-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-grid-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/custom-table-col-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/header-action-icons-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/hidden-columns-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/layout-hooks-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/multi-line-text-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/__snapshots__/spread-sheet-frozen-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/compare-layout-spec.ts
  packages/s2-core/__tests__/spreadsheet/header-action-icons-spec.ts
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/__tests__/spreadsheet/interaction-brush-selection-scroll-spec.ts
  packages/s2-core/__tests__/spreadsheet/layout-hooks-spec.ts
  packages/s2-core/__tests__/spreadsheet/miss-dimension-values-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-collapse-spec.ts
  packages/s2-core/__tests__/spreadsheet/spread-sheet-spec.ts
  packages/s2-core/__tests__/spreadsheet/total-group-spec.ts
  packages/s2-core/__tests__/unit/cell/col-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/data-cell-spec.ts
  packages/s2-core/__tests__/unit/cell/row-cell-spec.ts
  packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx
  packages/s2-core/__tests__/unit/dataset/table-dataset-spec.ts
  packages/s2-core/__tests__/unit/facet/__snapshots__/table-facet-spec.ts.snap
  packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts
  packages/s2-core/__tests__/unit/facet/table-facet-spec.ts
  packages/s2-core/__tests__/unit/utils/__snapshots__/hide-columns-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/__snapshots__/indexes-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/__snapshots__/merge-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/__snapshots__/tooltip-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/dataset/__snapshots__/pivot-data-set-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/dataset/pivot-data-set-spec.ts
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/copy-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-table-spec.ts.snap
  packages/s2-core/__tests__/unit/utils/export/copy-spec.ts
  packages/s2-core/__tests__/unit/utils/export/export-table-spec.ts
  packages/s2-core/__tests__/unit/utils/hide-columns-spec.ts
  packages/s2-core/__tests__/unit/utils/indexes-spec.ts
  packages/s2-core/__tests__/unit/utils/math-spec.ts
  packages/s2-core/__tests__/unit/utils/merge-spec.ts
  packages/s2-core/__tests__/unit/utils/tooltip-spec.ts
  packages/s2-core/src/extends/pivot-chart/facet/pivot-chart-facet.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/pivot-facet.ts
  packages/s2-core/src/facet/table-facet.ts
  packages/s2-core/src/interaction/row-column-resize.ts
  packages/s2-core/src/utils/math.ts
Labels: pr(fix), next

#3068 docs: 官网接入 petercart
  pnpm-lock.yaml
  s2-site/.dumirc.ts
  s2-site/package.json
Labels: pr(documentation), next

#3074 docs: 新增透视表 - 树状模式下的连接线示例
  s2-site/examples/custom/custom-shape-and-chart/demo/meta.json
  s2-site/examples/custom/custom-shape-and-chart/demo/pivot-tree-line.ts
Labels: pr(documentation), next

#3075 fix: 修复默认配置对 ChartSheet 不生效
  packages/s2-react/playground/components/ChartSheet.tsx
  packages/s2-react/src/components/sheets/chart-sheet/index.tsx
  s2-site/docs/manual/advanced/chart-with-g2.zh.md
  s2-site/examples/custom/custom-shape-and-chart/demo/custom-g2-chart.ts
  s2-site/examples/react-component/sheet/demo/chart.tsx
Labels: pr(fix), next

#3079 fix: 修复明细表空数据占位符背景穿透的问题 close #3077
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), next

#3081 fix: 修复组件层更新后 G 的 Group 图层累加的问题
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/facet/table-facet.ts
Labels: pr(fix), next

#3084 test: 修复单测卡死的问题
  .github/workflows/test-s2.yml
  jest.config.base.js
  package.json
  packages/s2-core/__tests__/spreadsheet/__snapshots__/table-sheet-spec.ts.snap
  packages/s2-core/__tests__/spreadsheet/table-sheet-spec.ts
  packages/s2-core/__tests__/unit/facet/pivot-facet-spec.ts
  packages/s2-core/package.json
  pnpm-lock.yaml
Labels: pr(test), next

#3085 fix: 修复维值包含 '\t' 制表符时导致复制到 Excel 中数据错列的问题
  packages/s2-core/__tests__/unit/utils/export/export-pivot-spec.ts
  packages/s2-core/__tests__/unit/utils/export/method-spec.ts
  packages/s2-core/src/extends/pivot-chart/cell/pivot-chart-data-cell.ts
  packages/s2-core/src/utils/export/copy/common.ts
  packages/s2-core/src/utils/export/method.ts
Labels: pr(fix), next

#3086 fix: 升级 G 版本, 修复超长文本中含有单词时换行异常
  packages/s2-core/package.json
  pnpm-lock.yaml
  s2-site/package.json
Labels: pr(fix), next
