Repository antvis/S2, pull requests merged in 2025-03, with the labels that each got.

#3116 chore: 修复CI
  pnpm-lock.yaml
Labels: pr(chore), next

#3118 docs: update readme for concise
  README.en-US.md
  README.md
Labels: pr(documentation), next

#3119 fix: 修复单层列头下，隐藏完所有非总计列头后，总计列头高度异常
  packages/s2-core/__tests__/data/single-measure-total.json
  packages/s2-core/__tests__/spreadsheet/hidden-columns-spec.ts
  packages/s2-core/src/facet/base-facet.ts
Labels: pr(fix), next

#3121 fix: 滚动动画，冻结行列滚动位置
  packages/s2-core/__tests__/spreadsheet/scroll-spec.ts
  packages/s2-core/src/facet/base-facet.ts
  packages/s2-core/src/interaction/root.ts
  s2-site/examples/interaction/advanced/demo/scroll-to-cell.ts
Labels: pr(fix), next

#3101 feat: 单元格渲染支持图片、视频
  packages/s2-core/__tests__/unit/common/icons/factory-spec.ts
  packages/s2-core/__tests__/unit/interaction/base-interaction/click/preview-click-spec.ts
  packages/s2-core/__tests__/unit/interaction/root-spec.ts
  packages/s2-core/__tests__/unit/renderer/renderer-factory-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/cell-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/custom-renderer-spec.ts
  packages/s2-core/__tests__/unit/utils/cell/text-scrolling-spec.ts
  packages/s2-core/src/cell/base-cell.ts
  packages/s2-core/src/cell/col-cell.ts
  packages/s2-core/src/cell/corner-cell.ts
  packages/s2-core/src/cell/data-cell.ts
  packages/s2-core/src/cell/header-cell.ts
  packages/s2-core/src/cell/merged-cell.ts
  packages/s2-core/src/cell/row-cell.ts
  packages/s2-core/src/cell/table-col-cell.ts
  packages/s2-core/src/common/constant/events/basic.ts
  packages/s2-core/src/common/constant/interaction.ts
  packages/s2-core/src/common/constant/renderer.ts
  packages/s2-core/src/common/icons/svg/index.ts
  packages/s2-core/src/common/icons/svg/svgs.ts
  packages/s2-core/src/common/interface/basic.ts
  packages/s2-core/src/common/interface/emitter.ts
  packages/s2-core/src/common/interface/index.ts
  packages/s2-core/src/common/interface/renderer.ts
  packages/s2-core/src/common/interface/theme.ts
  packages/s2-core/src/interaction/base-interaction/click/index.ts
  packages/s2-core/src/interaction/base-interaction/click/preview-click.ts
  packages/s2-core/src/interaction/root.ts
  packages/s2-core/src/renderer/BaseRenderer.ts
  packages/s2-core/src/renderer/ImageRenderer.ts
  packages/s2-core/src/renderer/RendererFactory.ts
  packages/s2-core/src/renderer/VideoRenderer.ts
  packages/s2-core/src/renderer/index.ts
  packages/s2-core/src/utils/cell/cell.ts
  packages/s2-core/src/utils/cell/customRenderer.ts
  packages/s2-core/src/utils/cell/text-scrolling.ts
  s2-site/.dumirc.ts
  s2-site/docs/api/general/s2-data-config.en.md
  s2-site/docs/api/general/s2-data-config.zh.md
  s2-site/docs/api/general/s2-event.en.md
  s2-site/docs/api/general/s2-event.zh.md
  s2-site/docs/api/general/s2-theme.zh.md
  s2-site/docs/manual/advanced/cell-render/chart-in-cell.en.md
  s2-site/docs/manual/advanced/cell-render/chart-in-cell.zh.md
  s2-site/docs/manual/advanced/cell-render/chart-with-g2.en.md
  s2-site/docs/manual/advanced/cell-render/chart-with-g2.zh.md
  s2-site/docs/manual/advanced/cell-render/custom.zh.md
  s2-site/docs/manual/advanced/cell-render/image.zh.md
  s2-site/docs/manual/advanced/cell-render/link-jump.en.md
  s2-site/docs/manual/advanced/cell-render/link-jump.zh.md
  s2-site/docs/manual/advanced/cell-render/video.zh.md
  s2-site/examples/custom/custom-renderer/API.en.md
  s2-site/examples/custom/custom-renderer/API.zh.md
  s2-site/examples/custom/custom-renderer/demo/image.ts
  s2-site/examples/custom/custom-renderer/demo/meta.json
  s2-site/examples/custom/custom-renderer/demo/video.ts
  s2-site/examples/custom/custom-renderer/index.en.md
  s2-site/examples/custom/custom-renderer/index.zh.md
Labels: pr(feature), next

#3133 docs: 文档勘误 Update README-adjustTotalNodesCoordinate.md
  packages/s2-core/src/facet/README-adjustTotalNodesCoordinate.md
Labels: pr(documentation), next
